import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-3211-STAN-01")

newPart.addTag('rawParts','"CONN1","HEADER-1X25","HEADER-1X25","1X25_ROUND_70MIL","","",')
newPart.addTag('rawParts','"D1","MBR120","DIODESOD-123","SOD-123","Diode","",')
newPart.addTag('rawParts','"D2","green","LED0805_NOOUTLINE","CHIPLED_0805_NOOUTLINE","LED","",')
newPart.addTag('rawParts','"FID1","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"FID2","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"FID3","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"IC3","MAX4866T","MAX486X/SOT","SOT23-6","","",')
newPart.addTag('rawParts','"JP1","","HEADER-1X376MIL","1X03_ROUND_76","PIN HEADER","",')
newPart.addTag('rawParts','"JP15","","HEADER-2X8_SHROUDED","2X08_SHROUDED","","",')
newPart.addTag('rawParts','"MATRIX_PWR","PINHEAD","PINHEAD","TERMBLOCK508","","",')
newPart.addTag('rawParts','"Q1","AON3414","MOSFET-NPOWERPAK-1212-8","POWERPAK-1212-8","N-Channel Mosfet","",')
newPart.addTag('rawParts','"Q2","AON7401","MOSFET-P-POWERDI3333","POWERDI3333","P-Channel Mosfet","",')
newPart.addTag('rawParts','"R4","1K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R13","1K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"RPI1","RASPBERRYPI_BPLUS_BONNET_THMSMT","RASPBERRYPI_BPLUS_BONNET_THMSMT","PI_BONNET_THMSMT","","",')
newPart.addTag('rawParts','"SJ1","","SOLDERJUMPER_2WAY","SOLDERJUMPER_2WAY_OPEN_NOPASTE","2-Way Solder Jumper","",')
newPart.addTag('rawParts','"U3","74AHCT245","74LCX245","TSSOP20","74LCX245MTC - 5.0V Tolerant Bi-Directional Buffer","",')
newPart.addTag('rawParts','"U5","74AHCT245","74LCX245","TSSOP20","74LCX245MTC - 5.0V Tolerant Bi-Directional Buffer","",')
newPart.addTag('rawParts','"X1","2.1mm DC","DCBARRELPTH","DCJACK_2MM_PTH","DC Barrel Jack","",')