import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-4201-STAN-01")

newPart.addTag('rawParts','"C1","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C2","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C3","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C4","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C5","0.1uF","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"D1","GREEN","LED0603_NOOUTLINE","CHIPLED_0603_NOOUTLINE","LED","",')
newPart.addTag('rawParts','"D2","BLUE","LED0603_NOOUTLINE","CHIPLED_0603_NOOUTLINE","LED","",')
newPart.addTag('rawParts','"D3","RED","LED0603_NOOUTLINE","CHIPLED_0603_NOOUTLINE","LED","",')
newPart.addTag('rawParts','"FID1","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"FID3","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"IC1","74AHC1G125","74AHC1G125","SOT23-5L","","",')
newPart.addTag('rawParts','"JP1","","HEADER-1X12","1X12_ROUND","","",')
newPart.addTag('rawParts','"Q3","BSS138","MOSFET-NWIDE","SOT23-WIDE","N-Channel Mosfet","",')
newPart.addTag('rawParts','"R2","10K","RESISTOR_4PACK","RESPACK_4X0603","Resistor Packs (4 resistors)","",')
newPart.addTag('rawParts','"R6","1K","RESISTOR_4PACK","RESPACK_4X0603","Resistor Packs (4 resistors)","",')
newPart.addTag('rawParts','"U$15","MOUNTINGHOLE2.5","MOUNTINGHOLE2.5","MOUNTINGHOLE_2.5_PLATED","Mounting Hole","EXCLUDE",')
newPart.addTag('rawParts','"U$16","MOUNTINGHOLE2.5","MOUNTINGHOLE2.5","MOUNTINGHOLE_2.5_PLATED","Mounting Hole","EXCLUDE",')
newPart.addTag('rawParts','"U1","AP2112-3.3","VREG_SOT23-5","SOT23-5","SOT23-5 Fixed Voltage Regulators","",')
newPart.addTag('rawParts','"U2","74AHC4050","74HC4050DTSSOP","TSSOP16","6-channel level shifter","",')
newPart.addTag('rawParts','"X1","ESP32_WROOM32","ESP32_WROOM32","WROOM32","","",')