import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-4022-STAN-01")

newPart.addTag('rawParts','"C1","10uf","CAP_CERAMIC0805_10MGAP","0805_10MGAP","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C2","10uF","CAP_CERAMIC0805_10MGAP","0805_10MGAP","Ceramic Capacitors","",')
newPart.addTag('rawParts','"D1","1N4148","DIODESOD-323","SOD-323","Diode","",')
newPart.addTag('rawParts','"FID1","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"FID3","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"JP2","H3","HEADER-1X4ROUND","1X04_ROUND","PIN HEADER","",')
newPart.addTag('rawParts','"JP3","H8","HEADER-1X8ROUND","1X08_ROUND","PIN HEADER","",')
newPart.addTag('rawParts','"Q1","BSS138","MOSFET-N_DUAL","SOT363","Dual N-Channel MOSFET","",')
newPart.addTag('rawParts','"R1","10K","RESISTOR_4PACK_NO","RESPACK_4X0603_NO","Resistor Packs (4 resistors)","",')
newPart.addTag('rawParts','"R2","10K","RESISTOR_4PACK_NO","RESPACK_4X0603_NO","Resistor Packs (4 resistors)","",')
newPart.addTag('rawParts','"U$19","MOUNTINGHOLE2.5","MOUNTINGHOLE2.5","MOUNTINGHOLE_2.5_PLATED","Mounting Hole","EXCLUDE",')
newPart.addTag('rawParts','"U$23","MOUNTINGHOLE2.5","MOUNTINGHOLE2.5","MOUNTINGHOLE_2.5_PLATED","Mounting Hole","EXCLUDE",')
newPart.addTag('rawParts','"U1","MLX90393","MLX90393","QFN16_3MM","MLX90393 - Wide Range 3 Axis Magnetometer","",')
newPart.addTag('rawParts','"U2","AP2112K-3.3","VREG_SOT23-5","SOT23-5","SOT23-5 Fixed Voltage Regulators","",')