import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-13169-STAN-01")

newPart.addTag('rawParts','"FRAME1","FRAME-LETTER","FRAME-LETTER","CREATIVE_COMMONS","Schematic Frame","",')
newPart.addTag('rawParts','"U$1","BLACKBERRY_TRACKBALLER","BLACKBERRY_TRACKBALLER","BLACKBERRY_TRACKBALLER","","PCB-12486",')