import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-4920-STAN-01")

newPart.addTag('rawParts','"C1","22uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C2","22uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C3","22uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C4","120pF","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"D1","green","LED0603_NOOUTLINE","CHIPLED_0603_NOOUTLINE","LED","",')
newPart.addTag('rawParts','"FID1","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"FID2","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"IC2","TPS6282X","TPS6282X","VSON_6","","",')
newPart.addTag('rawParts','"JP1","","HEADER-1X4ROUND","1X04_ROUND","PIN HEADER","",')
newPart.addTag('rawParts','"L1","SDER041H-2R2MS","INDUCTOR_SRP0415","INDUCTOR_4X4MM_SRP0415","Inductors","",')
newPart.addTag('rawParts','"R1","100K","RESISTOR_0603_NOOUT","0603-NO","Resistors","",')
newPart.addTag('rawParts','"R2","450K","RESISTOR_0603_NOOUT","0603-NO","Resistors","",')
newPart.addTag('rawParts','"R3","100K","RESISTOR_0603_NOOUT","0603-NO","Resistors","",')
newPart.addTag('rawParts','"R4","10k","RESISTOR_0603MP","_0603MP","Resistors","",')
newPart.addTag('rawParts','"U$9","MOUNTINGHOLE2.5","MOUNTINGHOLE2.5","MOUNTINGHOLE_2.5_PLATED","Mounting Hole","EXCLUDE",')