import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-10940-STAN-01")

newPart.addTag('oompParts','JP3,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','JP4,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','JP5,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','JP6,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','JP7,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','JP8,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','JP9,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','JP10,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','JP11,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','JP12,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','JP13,UNMATCHED-UNMATCHED-X-UNMATCHED-01')