import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-1571-STAN-01")

newPart.addTag('rawParts','"C1","0.1uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C2","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"D1","1N4148","DIODESOD-323F","SOD-323F","Diode","",')
newPart.addTag('rawParts','"FID1","FIDUCIAL""","FIDUCIAL""","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"FID2","FIDUCIAL""","FIDUCIAL""","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"FID3","FIDUCIAL""","FIDUCIAL""","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"JP1","","HEADER-1X11","1X11_ROUND","","",')
newPart.addTag('rawParts','"JP4","","HEADER-1X2ROUND","1X02_ROUND","PIN HEADER","",')
newPart.addTag('rawParts','"JP5","","HEADER-1X2ROUND","1X02_ROUND","PIN HEADER","",')
newPart.addTag('rawParts','"Q1","BSS138","MOSFET-NREFLOW","SOT23","N-Channel Mosfet","",')
newPart.addTag('rawParts','"Q2","BSS138","MOSFET-NREFLOW","SOT23","N-Channel Mosfet","",')
newPart.addTag('rawParts','"R1","10K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R2","10K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R3","10K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R4","10K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R5","10K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R6","10K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"U$4","MOUNTINGHOLE2.5","MOUNTINGHOLE2.5","MOUNTINGHOLE_2.5_PLATED","Mounting Hole","EXCLUDE",')
newPart.addTag('rawParts','"U$5","MOUNTINGHOLE2.5","MOUNTINGHOLE2.5","MOUNTINGHOLE_2.5_PLATED","Mounting Hole","EXCLUDE",')
newPart.addTag('rawParts','"U$7","FPC_4PIN_12969","FPC_4PIN_12969","FPC_CONN_1MM_DUAL_4P","","",')
newPart.addTag('rawParts','"U1","STMPE610","STMPE610","QFN16_3MM","STMPE610 - 12-Bit Touch Screen Controller","",')
newPart.addTag('rawParts','"U2","MIC5225-3.3","VREG_SOT23-5","SOT23-5","SOT23-5 Fixed Voltage Regulators","",')