import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-11850-STAN-01")

newPart.addTag('oompParts','C1,CAPC-0805-X-UF1-01')
newPart.addTag('oompParts','C2,CAPC-0805-X-UNMATCHED-01')
newPart.addTag('oompParts','C3,CAPC-0805-X-UF1-01')
newPart.addTag('oompParts','C4,CAPC-0805-X-UNMATCHED-01')
newPart.addTag('oompParts','C5,CAPC-0805-X-UF1-01')
newPart.addTag('oompParts','C6,CAPC-0805-X-UNMATCHED-01')
newPart.addTag('oompParts','CH1,TERS-35D-L-PI02-01')
newPart.addTag('oompParts','CH2,TERS-35D-L-PI02-01')
newPart.addTag('oompParts','CH3,TERS-35D-L-PI02-01')
newPart.addTag('oompParts','D1,DIOD-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','D2,DIOD-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','D3,DIOD-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','JP2,TERS-35D-L-PI02-01')
newPart.addTag('oompParts','JP3,HEAD-I01-X-PI02-01')
newPart.addTag('oompParts','JP4,HEAD-I01-X-PI02-01')
newPart.addTag('oompParts','L1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','L2,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','L3,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','R1,RESE-0805-X-UNMATCHED-01')
newPart.addTag('oompParts','R2,RESE-0805-X-UNMATCHED-01')
newPart.addTag('oompParts','R3,RESE-0805-X-UNMATCHED-01')
newPart.addTag('oompParts','R4,RESE-0805-X-UNMATCHED-01')
newPart.addTag('oompParts','R5,RESE-0805-X-UNMATCHED-01')
newPart.addTag('oompParts','R6,RESE-0805-X-UNMATCHED-01')
newPart.addTag('oompParts','SJ1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','SJ2,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','SJ3,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U1,UNMATCHED-SO235-X-UNMATCHED-01')
newPart.addTag('oompParts','U2,UNMATCHED-SO235-X-UNMATCHED-01')
newPart.addTag('oompParts','U3,UNMATCHED-SO235-X-UNMATCHED-01')