import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-2601-STAN-01")

newPart.addTag('rawParts','"JP1","","PINHD-1X8CLEANBIG","1X08-CLEANBIG","PIN HEADER","","","","",')
newPart.addTag('rawParts','"JP2","","HEADER-1X876MIL","1X08_ROUND_76","PIN HEADER","","","","",')
newPart.addTag('rawParts','"JP3","","HEADER-1X876MIL","1X08_ROUND_76","PIN HEADER","","","","",')
newPart.addTag('rawParts','"JP4","","PINHD-1X8CLEANBIG","1X08-CLEANBIG","PIN HEADER","","","","",')
newPart.addTag('rawParts','"JP6","","HEADER-1X1070MIL","1X10_ROUND70","PIN HEADER","","","","",')
newPart.addTag('rawParts','"JP8","","PINHD-1X6CB","1X06-CLEANBIG","PIN HEADER","","","","",')
newPart.addTag('rawParts','"JP15","Shrouded 2x8","HEADER-2X8_SHROUDED","2X08_SHROUDED","","","","","",')
newPart.addTag('rawParts','"MATRIX_PWR","PINHEAD","PINHEAD","TERMBLOCK508","","","","","",')
newPart.addTag('rawParts','"S4","6mm","10-XX","B3F-10XX","OMRON SWITCH","","B3F-1000","176432","36M3542",')
newPart.addTag('rawParts','"SJ1","","SOLDERJUMPERCLOSED","SOLDERJUMPER_CLOSEDWIRE","SMD Solder JUMPER","","","","",')
newPart.addTag('rawParts','"SJ2","","SOLDERJUMPERCLOSED","SOLDERJUMPER_CLOSEDWIRE","SMD Solder JUMPER","","","","",')
newPart.addTag('rawParts','"SJ3","","SOLDERJUMPERCLOSED","SOLDERJUMPER_CLOSEDWIRE","SMD Solder JUMPER","","","","",')
newPart.addTag('rawParts','"SJ4","","SOLDERJUMPERCLOSED","SOLDERJUMPER_CLOSEDWIRE","SMD Solder JUMPER","","","","",')
newPart.addTag('rawParts','"SJ5","","SOLDERJUMPERCLOSED","SOLDERJUMPER_CLOSEDWIRE","SMD Solder JUMPER","","","","",')
newPart.addTag('rawParts','"SJ6","","SOLDERJUMPERCLOSED","SOLDERJUMPER_CLOSEDWIRE","SMD Solder JUMPER","","","","",')
newPart.addTag('rawParts','"SJ7","","SOLDERJUMPERCLOSED","SOLDERJUMPER_CLOSEDWIRE","SMD Solder JUMPER","","","","",')
newPart.addTag('rawParts','"SJ8","","SOLDERJUMPERCLOSED","SOLDERJUMPER_CLOSEDWIRE","SMD Solder JUMPER","","","","",')
newPart.addTag('rawParts','"SJ9","","SOLDERJUMPERCLOSED","SOLDERJUMPER_CLOSEDWIRE","SMD Solder JUMPER","","","","",')
newPart.addTag('rawParts','"SJ10","","SOLDERJUMPERCLOSED","SOLDERJUMPER_CLOSEDWIRE","SMD Solder JUMPER","","","","",')
newPart.addTag('rawParts','"SJ12","","SOLDERJUMPERCLOSED","SOLDERJUMPER_CLOSEDWIRE","SMD Solder JUMPER","","","","",')
newPart.addTag('rawParts','"SJ13","","SOLDERJUMPERCLOSED","SOLDERJUMPER_CLOSEDWIRE","SMD Solder JUMPER","","","","",')
newPart.addTag('rawParts','"SJ14","","SOLDERJUMPERCLOSED","SOLDERJUMPER_CLOSEDWIRE","SMD Solder JUMPER","","","","",')
newPart.addTag('rawParts','"U$41","ARDUINO_R3_ICSP_NODIM","ARDUINO_R3_ICSP_NODIM","ARDUINOR3_ICSP_NODIM","","","","","",')