import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-12898-STAN-01")

newPart.addTag('rawParts','"D1","MBRA140","MBRA140","SMA-DIODE","40V, 1A Schottky rectifier","DIO-08053","",')
newPart.addTag('rawParts','"FID1","FIDUCIALUFIDUCIAL","FIDUCIALUFIDUCIAL","MICRO-FIDUCIAL","Fiducial Alignment Points","","",')
newPart.addTag('rawParts','"FID2","FIDUCIALUFIDUCIAL","FIDUCIALUFIDUCIAL","MICRO-FIDUCIAL","Fiducial Alignment Points","","",')
newPart.addTag('rawParts','"FRAME1","Frame","FRAME-LETTER","CREATIVE_COMMONS","Schematic Frame","","",')
newPart.addTag('rawParts','"J1","MIDI IN","5-PIN-CIRCULAR-DINNEW","5-PIN-DIN-RA-PCB-NEW","5-pin circular DIN connector.","CONN-09481","",')
newPart.addTag('rawParts','"J2","MIDI OUT","5-PIN-CIRCULAR-DINNEW","5-PIN-DIN-RA-PCB-NEW","5-pin circular DIN connector.","CONN-09481","",')
newPart.addTag('rawParts','"J3","UNO_R3_SHIELD","ARDUINO_R3_SHIELD","UNO_R3_SHIELD","Shield form compatible with the Arduino Uno R3.","","",')
newPart.addTag('rawParts','"LED1","RED","LED-RED0603","LED-0603","Assorted Red LEDs","DIO-00819","RED",')
newPart.addTag('rawParts','"LED2","GREEN","LED-GREEN0603","LED-0603","Various green LEDs","DIO-00821","GREEN",')
newPart.addTag('rawParts','"LOGO1","SFE_LOGO_NAME_FLAME.2_INCH","SFE_LOGO_NAME_FLAME.2_INCH","SFE_LOGO_NAME_FLAME_.2","SFE Logo, name and flame","","",')
newPart.addTag('rawParts','"LOGO2","OSHW-LOGOS","OSHW-LOGOS","OSHW-LOGO-S","Open Source Hardware Logo","","",')
newPart.addTag('rawParts','"LOGO3","OSHW-LOGOM","OSHW-LOGOM","OSHW-LOGO-M","Open Source Hardware Logo","","",')
newPart.addTag('rawParts','"LOGO5","SFE_LOGO_FLAME.1_INCH","SFE_LOGO_FLAME.1_INCH","SFE_LOGO_FLAME_.1","SFE Logo, flame only","","",')
newPart.addTag('rawParts','"R1","220","220OHM-1/10W-1%(0603)","0603-RES","RES-07861","RES-07861","220",')
newPart.addTag('rawParts','"R2","220","220OHM-1/10W-1%(0603)","0603-RES","RES-07861","RES-07861","220",')
newPart.addTag('rawParts','"R3","220","220OHM-1/10W-1%(0603)","0603-RES","RES-07861","RES-07861","220",')
newPart.addTag('rawParts','"R4","220","220OHM-1/10W-1%(0603)","0603-RES","RES-07861","RES-07861","220",')
newPart.addTag('rawParts','"R5","330","330OHM1/10W1%(0603)","0603-RES","RES-00818","RES-00818","330",')
newPart.addTag('rawParts','"R6","330","330OHM1/10W1%(0603)","0603-RES","RES-00818","RES-00818","330",')
newPart.addTag('rawParts','"RV1","10k","POT","ALPS_POT","","RES-09177","",')
newPart.addTag('rawParts','"RV2","10k","POT","ALPS_POT","","RES-09177","",')
newPart.addTag('rawParts','"S1","Reset","SWITCH-MOMENTARY-2SMD","TACTILE-SWITCH-SMD","Various NO switches- pushbuttons, reed, etc","SWCH-08247","",')
newPart.addTag('rawParts','"S2","RUN/PROGRAM","SWITCH-SPDTSMD","AYZ0202","SPDT Switch","SWCH-08179","",')
newPart.addTag('rawParts','"S3","SWITCH-MOMENTARY-212MM","SWITCH-MOMENTARY-212MM","TACTILE-PTH-12MM","Various NO switches- pushbuttons, reed, etc","SWCH-09185","",')
newPart.addTag('rawParts','"S4","SWITCH-MOMENTARY-212MM","SWITCH-MOMENTARY-212MM","TACTILE-PTH-12MM","Various NO switches- pushbuttons, reed, etc","SWCH-09185","",')
newPart.addTag('rawParts','"S5","SWITCH-MOMENTARY-212MM","SWITCH-MOMENTARY-212MM","TACTILE-PTH-12MM","Various NO switches- pushbuttons, reed, etc","SWCH-09185","",')
newPart.addTag('rawParts','"SJ1","RX sel","JUMPER-PAD-3-2OF3_NC_BY_TRACE_SMALL","PAD-JUMPER-3-2OF3_NC_BY_TRACE_YES_SILK_FULL_BOX","","","",')
newPart.addTag('rawParts','"SJ2","TX sel","JUMPER-PAD-3-2OF3_NC_BY_TRACE_SMALL","PAD-JUMPER-3-2OF3_NC_BY_TRACE_YES_SILK_FULL_BOX","","","",')
newPart.addTag('rawParts','"SJ3","out/thru","JUMPER-PAD-3-2OF3_NC_BY_TRACE_SMALL","PAD-JUMPER-3-2OF3_NC_BY_TRACE_YES_SILK_FULL_BOX","","","",')
newPart.addTag('rawParts','"SJ4","JUMPER-PAD-2-NOYES_SILK","JUMPER-PAD-2-NOYES_SILK","PAD-JUMPER-2-NO_YES_SILK","","","",')
newPart.addTag('rawParts','"SJ5","JUMPER-PAD-2-NOYES_SILK","JUMPER-PAD-2-NOYES_SILK","PAD-JUMPER-2-NO_YES_SILK","","","",')
newPart.addTag('rawParts','"SJ6","JUMPER-PAD-2-NOYES_SILK","JUMPER-PAD-2-NOYES_SILK","PAD-JUMPER-2-NO_YES_SILK","","","",')
newPart.addTag('rawParts','"SJ7","JUMPER-PAD-2-NOYES_SILK","JUMPER-PAD-2-NOYES_SILK","PAD-JUMPER-2-NO_YES_SILK","","","",')
newPart.addTag('rawParts','"U$1","REVISION","REVISION","REVISION","","","",')
newPart.addTag('rawParts','"U1","6N138M","OPTO_DARL_6N138S","8-SMD","Optoisolator, darlington pair output","IC-09482","6N138M",')
newPart.addTag('rawParts','"U2","74AHC1G125","74AHC1G125","SOT23-5","Single bus buffer gate with 3-state output","IC-11920","",')