import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-9346-STAN-01")

newPart.addTag('rawParts','JP3,,M08LOCK,1X08_LOCK,Header 8,,')
newPart.addTag('rawParts','JP4,,M08LOCK,1X08_LOCK,Header 8,,')
newPart.addTag('rawParts','JP5,,M08LOCK,1X08_LOCK,Header 8,,')
newPart.addTag('rawParts','JP6,,M08LOCK,1X08_LOCK,Header 8,,')
newPart.addTag('rawParts','JP7,,M08LOCK,1X08_LOCK,Header 8,,')
newPart.addTag('rawParts','JP8,M16LOCK,M16LOCK,1X16_LOCK,,,')
newPart.addTag('rawParts','JP9,M16LOCK,M16LOCK,1X16_LOCK,,,')
newPart.addTag('rawParts','JP10,,M06LOCK,1X06_LOCK,Header 6,,')
newPart.addTag('rawParts','JP11,,M02LOCK,1X02_LOCK,Header 2,,')
newPart.addTag('rawParts','JP12,,M02LOCK,1X02_LOCK,Header 2,,')
newPart.addTag('rawParts','LED1,Red,LED5MM,LED5MM,LEDs,,')
newPart.addTag('rawParts','LED2,Green,LED5MM,LED5MM,LEDs,,')
newPart.addTag('rawParts','R1,330,RESISTORPTH1,AXIAL-0.3,Resistor,,')
newPart.addTag('rawParts','R2,330,RESISTORPTH1,AXIAL-0.3,Resistor,,')
newPart.addTag('rawParts','R3,10k,RESISTORPTH1,AXIAL-0.3,Resistor,,')
newPart.addTag('rawParts','S1,,TAC_SWITCHPTH,TACTILE-PTH,Momentary Switch,,')
newPart.addTag('rawParts','U$1,LOGO-SFENEW,LOGO-SFENEW,SFE-NEW-WEBLOGO,Spark Fun Electronics PCB Logo,,')
newPart.addTag('rawParts','U$2,CREATIVE_COMMONS,CREATIVE_COMMONS,CREATIVE_COMMONS,,,')