import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-5165-STAN-01")

newPart.addTag('rawParts','"C1","0.1uF","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C2","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"CONN3","STEMMA_I2C_QT","STEMMA_I2C_QT","JST_SH4","","",')
newPart.addTag('rawParts','"CONN4","STEMMA_I2C_QT","STEMMA_I2C_QT","JST_SH4","","",')
newPart.addTag('rawParts','"D1","GREEN","LED0603_NOOUTLINE","CHIPLED_0603_NOOUTLINE","LED","",')
newPart.addTag('rawParts','"FB1","Ferrite","FERRITE-0603NO","0603-NO","Ferrite Bead","",')
newPart.addTag('rawParts','"FB2","Ferrite","FERRITE-0603NO","0603-NO","Ferrite Bead","",')
newPart.addTag('rawParts','"FID3","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"FID4","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"IC1","MCP9601","MCP9601","VQFN20_5MM","","",')
newPart.addTag('rawParts','"JP3","","HEADER-1X970MIL","1X09_ROUND_70","PIN HEADER","",')
newPart.addTag('rawParts','"R1","10K","RESISTOR_4PACK","RESPACK_4X0603","Resistor Packs (4 resistors)","",')
newPart.addTag('rawParts','"R2","487K","RESISTOR_0603_NOOUT","0603-NO","Resistors","",')
newPart.addTag('rawParts','"R3","2.5M","RESISTOR_0603_NOOUT","0603-NO","Resistors","",')
newPart.addTag('rawParts','"R4","22K","RESISTOR_0603_NOOUT","0603-NO","Resistors","",')
newPart.addTag('rawParts','"R5","100","RESISTOR_0603_NOOUT","0603-NO","Resistors","",')
newPart.addTag('rawParts','"R6","100","RESISTOR_0603_NOOUT","0603-NO","Resistors","",')
newPart.addTag('rawParts','"R7","47K","RESISTOR_0603_NOOUT","0603-NO","Resistors","",')
newPart.addTag('rawParts','"R8","2M","RESISTOR_0603_NOOUT","0603-NO","Resistors","",')
newPart.addTag('rawParts','"SJ1","","SOLDERJUMPER","SOLDERJUMPER_ARROW_NOPASTE","SMD Solder JUMPER","EXCLUDE",')
newPart.addTag('rawParts','"SJ2","","SOLDERJUMPER","SOLDERJUMPER_ARROW_NOPASTE","SMD Solder JUMPER","EXCLUDE",')
newPart.addTag('rawParts','"U$33","MOUNTINGHOLE2.5","MOUNTINGHOLE2.5","MOUNTINGHOLE_2.5_PLATED","Mounting Hole","EXCLUDE",')
newPart.addTag('rawParts','"U$34","MOUNTINGHOLE2.5","MOUNTINGHOLE2.5","MOUNTINGHOLE_2.5_PLATED","Mounting Hole","EXCLUDE",')
newPart.addTag('rawParts','"X1","TERMBLK","TERMBLOCK_1X2_3.5MM","TERMBLOCK_1X2-3.5MM","3.5mm Terminal block","",')