import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-12702-STAN-01")

newPart.addTag('rawParts','"FRAME1","FRAME-LETTER","FRAME-LETTER","CREATIVE_COMMONS","Schematic Frame","",')
newPart.addTag('rawParts','"JP1"," ","M05NO_SILK","1X05_NO_SILK","Header 5","",')
newPart.addTag('rawParts','"JP2"," ","M05NO_SILK","1X05_NO_SILK","Header 5","",')
newPart.addTag('rawParts','"JP3"," ","M05NO_SILK","1X05_NO_SILK","Header 5","",')
newPart.addTag('rawParts','"JP4"," ","M05NO_SILK","1X05_NO_SILK","Header 5","",')
newPart.addTag('rawParts','"JP5"," ","M05NO_SILK","1X05_NO_SILK","Header 5","",')
newPart.addTag('rawParts','"JP6"," ","M05NO_SILK","1X05_NO_SILK","Header 5","",')
newPart.addTag('rawParts','"JP7"," ","M05NO_SILK","1X05_NO_SILK","Header 5","",')
newPart.addTag('rawParts','"JP8"," ","M05NO_SILK","1X05_NO_SILK","Header 5","",')
newPart.addTag('rawParts','"JP9"," ","M05NO_SILK","1X05_NO_SILK","Header 5","",')
newPart.addTag('rawParts','"JP10"," ","M05NO_SILK","1X05_NO_SILK","Header 5","",')
newPart.addTag('rawParts','"JP11"," ","M05NO_SILK","1X05_NO_SILK","Header 5","",')
newPart.addTag('rawParts','"JP12"," ","M05NO_SILK","1X05_NO_SILK","Header 5","",')
newPart.addTag('rawParts','"JP13"," ","M05NO_SILK","1X05_NO_SILK","Header 5","",')
newPart.addTag('rawParts','"JP14"," ","M05NO_SILK","1X05_NO_SILK","Header 5","",')
newPart.addTag('rawParts','"JP15"," ","M05NO_SILK","1X05_NO_SILK","Header 5","",')
newPart.addTag('rawParts','"JP16"," ","M05NO_SILK","1X05_NO_SILK","Header 5","",')
newPart.addTag('rawParts','"JP17"," ","M05NO_SILK","1X05_NO_SILK","Header 5","",')
newPart.addTag('rawParts','"JP18"," ","M05NO_SILK","1X05_NO_SILK","Header 5","",')
newPart.addTag('rawParts','"JP19"," ","M05NO_SILK","1X05_NO_SILK","Header 5","",')
newPart.addTag('rawParts','"JP20"," ","M05NO_SILK","1X05_NO_SILK","Header 5","",')
newPart.addTag('rawParts','"JP21"," ","M05NO_SILK","1X05_NO_SILK","Header 5","",')
newPart.addTag('rawParts','"JP22"," ","M05NO_SILK","1X05_NO_SILK","Header 5","",')
newPart.addTag('rawParts','"JP23"," ","M05NO_SILK","1X05_NO_SILK","Header 5","",')
newPart.addTag('rawParts','"JP24"," ","M05NO_SILK","1X05_NO_SILK","Header 5","",')
newPart.addTag('rawParts','"JP25"," ","M05NO_SILK","1X05_NO_SILK","Header 5","",')
newPart.addTag('rawParts','"JP26"," ","M05NO_SILK","1X05_NO_SILK","Header 5","",')
newPart.addTag('rawParts','"JP27"," ","M05NO_SILK","1X05_NO_SILK","Header 5","",')
newPart.addTag('rawParts','"JP28"," ","M05NO_SILK","1X05_NO_SILK","Header 5","",')
newPart.addTag('rawParts','"JP29"," ","M05NO_SILK","1X05_NO_SILK","Header 5","",')
newPart.addTag('rawParts','"JP30"," ","M05NO_SILK","1X05_NO_SILK","Header 5","",')
newPart.addTag('rawParts','"JP31"," ","M05NO_SILK","1X05_NO_SILK","Header 5","",')
newPart.addTag('rawParts','"JP32"," ","M05NO_SILK","1X05_NO_SILK","Header 5","",')
newPart.addTag('rawParts','"JP33"," ","M05NO_SILK","1X05_NO_SILK","Header 5","",')
newPart.addTag('rawParts','"JP34"," ","M05NO_SILK","1X05_NO_SILK","Header 5","",')
newPart.addTag('rawParts','"LOGO1","SFE_LOGO_NAME.1_INCH","SFE_LOGO_NAME.1_INCH","SFE_LOGO_NAME_.1","SFE Logo, name only","",')
newPart.addTag('rawParts','"LOGO2","OSHW-LOGOM","OSHW-LOGOM","OSHW-LOGO-M","Open Source Hardware Logo This logo indicates the piece of hardware it is found on incorporates a OSHW license and/or adheres to the definition of open source hardware found here: http://freedomdefined.org/OSHW","",')
newPart.addTag('rawParts','"LOGO3","SFE_LOGO_FLAME.1_INCH","SFE_LOGO_FLAME.1_INCH","SFE_LOGO_FLAME_.1","SFE Logo, flame only","",')
newPart.addTag('rawParts','"LOGO4","SFE_LOGO_FLAME.1_INCH","SFE_LOGO_FLAME.1_INCH","SFE_LOGO_FLAME_.1","SFE Logo, flame only","",')