import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-11044-STAN-01")

newPart.addTag('rawParts','C1,1uF,CAP1206,1206,Capacitor,,')
newPart.addTag('rawParts','C2,10uF,CAP1206,1206,Capacitor,,')
newPart.addTag('rawParts','C3,1uF,CAP1206,1206,Capacitor,,')
newPart.addTag('rawParts','C4,1uF,CAP1206,1206,Capacitor,,')
newPart.addTag('rawParts','JP1,POWER,M03PTH,1X03,Header 3,,')
newPart.addTag('rawParts','JP2,IN,M02PTH,1X02,Header 2,,')
newPart.addTag('rawParts','JP3,OUT,M02PTH,1X02,Header 2,,')
newPart.addTag('rawParts','JP4,VOLUME,M03PTH,1X03,Header 3,,')
newPart.addTag('rawParts','JP5,FIDUCIALUFIDUCIAL,FIDUCIALUFIDUCIAL,MICRO-FIDUCIAL,Fiducial Alignment Points,,')
newPart.addTag('rawParts','JP6,FIDUCIALUFIDUCIAL,FIDUCIALUFIDUCIAL,MICRO-FIDUCIAL,Fiducial Alignment Points,,')
newPart.addTag('rawParts','LED1,,LED0603,LED-0603,LEDs,,')
newPart.addTag('rawParts','LOGO1,LOGO-SFENW2,LOGO-SFENW2,SFE-NEW-WEB,Spark Fun Electronics PCB Logo,,')
newPart.addTag('rawParts','LOGO2,LOGO-SFESK,LOGO-SFESK,SFE-LOGO-FLAME,Spark Fun Electronics PCB Logo,,')
newPart.addTag('rawParts','Q1,MMBT2222A,TRANSISTOR_NPNSOT23-3,SOT23-3,Transistor NPN,,')
newPart.addTag('rawParts','R1,150K,RESISTOR0603-RES,0603-RES,Resistor,,')
newPart.addTag('rawParts','R1A,DNP,RESISTORAXIAL-0.3,AXIAL-0.3,Resistor,,')
newPart.addTag('rawParts','R2,150K,RESISTOR0603-RES,0603-RES,Resistor,,')
newPart.addTag('rawParts','R2A,DNP,RESISTORAXIAL-0.3,AXIAL-0.3,Resistor,,')
newPart.addTag('rawParts','R3,10K,RESISTOR0603-RES,0603-RES,Resistor,,')
newPart.addTag('rawParts','R4,330,RESISTOR0603-RES,0603-RES,Resistor,,')
newPart.addTag('rawParts','R5,10K,RESISTOR0603-RES,0603-RES,Resistor,,')
newPart.addTag('rawParts','SJ1,,SOLDERJUMPERNC2,SJ_2S-NOTRACE,Solder Jumper,,')
newPart.addTag('rawParts','U$1,CREATIVE_COMMONS,CREATIVE_COMMONS,CREATIVE_COMMONS,,,')
newPart.addTag('rawParts','U$2,OSHW-LOGOS,OSHW-LOGOS,OSHW-LOGO-S,Open Source Hardware Logo This logo indicates the piece of hardware it is found on incorporates a OSHW license and/or adheres to the definition of open source hardware found here: http://freedomdefined.org/OSHW,,')
newPart.addTag('rawParts','U1,TPA2005D1DRB,TPA2005D1DRB,QFN-8_PAD,1.4W MONO CLASS-D AUDIO POWER AMPLIFIER,,')