import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-10618-STAN-01")

newPart.addTag('oompParts','D1,DIOD-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','J1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','JP1,HEAD-I01-X-UNMATCHED-01')
newPart.addTag('oompParts','JP2,HEAD-I01-X-UNMATCHED-01')
newPart.addTag('oompParts','JP3,HEAD-I01-X-UNMATCHED-01')
newPart.addTag('oompParts','JP4,HEAD-I01-X-UNMATCHED-01')
newPart.addTag('oompParts','JP5,HEAD-I01-X-UNMATCHED-01')
newPart.addTag('oompParts','JP6,TERS-35D-L-PI02-01')
newPart.addTag('oompParts','JP8,HEAD-I01-X-UNMATCHED-01')
newPart.addTag('oompParts','JP9,TERS-35D-L-PI02-01')
newPart.addTag('oompParts','JP10,TERS-35D-L-PI02-01')
newPart.addTag('oompParts','JP11,TERS-35D-L-PI02-01')
newPart.addTag('oompParts','JP12,TERS-35D-L-PI02-01')
newPart.addTag('oompParts','JP13,TERS-35D-L-PI02-01')
newPart.addTag('oompParts','LED1,LEDS-UNMATCHED-R-STAN-01')
newPart.addTag('oompParts','LED2,LEDS-UNMATCHED-Y-STAN-01')
newPart.addTag('oompParts','Q1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','Q2,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','Q3,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','Q4,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','Q5,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','Q6,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','R1,RESE-UNMATCHED-X-O103-01')
newPart.addTag('oompParts','R2,RESE-UNMATCHED-X-O103-01')
newPart.addTag('oompParts','R3,RESE-UNMATCHED-X-O103-01')
newPart.addTag('oompParts','R4,RESE-UNMATCHED-X-O103-01')
newPart.addTag('oompParts','R5,RESE-UNMATCHED-X-O103-01')
newPart.addTag('oompParts','R6,RESE-UNMATCHED-X-O103-01')
newPart.addTag('oompParts','R7,RESE-UNMATCHED-X-O102-01')
newPart.addTag('oompParts','R8,RESE-UNMATCHED-X-O102-01')
newPart.addTag('oompParts','S1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')