import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-12081-STAN-01")

newPart.addTag('rawParts','"C1","0.1uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C2","0.1uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C3","0.1uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C4","0.1uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C5","0.1uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C6","470pF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C7","10uF","CAP_POL1206","EIA3216","Capacitor Polarized","",')
newPart.addTag('rawParts','"C8","0.1uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C9","0.1uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C10","0.1uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C11","0.1uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C12","0.1uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"D1","RED","LED0603","LED-0603","LEDs","",')
newPart.addTag('rawParts','"D2","GREEN","LED0603","LED-0603","LEDs","",')
newPart.addTag('rawParts','"D3","3.6V","DIODE-ZENER-BZT52","SOD-323","Zener Diode","",')
newPart.addTag('rawParts','"D4","3.6V","DIODE-ZENER-BZT52","SOD-323","Zener Diode","",')
newPart.addTag('rawParts','"D5","BAS16","DIODESOD","SOD-323","Diode","",')
newPart.addTag('rawParts','"D6","BAS16","DIODESOD","SOD-323","Diode","",')
newPart.addTag('rawParts','"D7","BAS16","DIODESOD","SOD-323","Diode","",')
newPart.addTag('rawParts','"D8","BAS16","DIODESOD","SOD-323","Diode","",')
newPart.addTag('rawParts','"D9","BAS16","DIODESOD","SOD-323","Diode","",')
newPart.addTag('rawParts','"D10","BAS16","DIODESOD","SOD-323","Diode","",')
newPart.addTag('rawParts','"D11","3.6V","DIODE-ZENER-BZT52","SOD-323","Zener Diode","",')
newPart.addTag('rawParts','"JP1","JST","M02-JST-2MM-SMT","JST-2-SMD","Header 2","",')
newPart.addTag('rawParts','"JP2","1X2","M021X02_NO_SILK","1X02_NO_SILK","Header 2","",')
newPart.addTag('rawParts','"JP3","AVR_Prog","AVR_SPI_PRG_6PTH","2X3","AVR ISP 6 Pin","",')
newPart.addTag('rawParts','"JP4","USBSMD","USBSMD","USB-MINIB","USB Connectors","",')
newPart.addTag('rawParts','"JP5-DNP","BLUESMIRF","M06SIP","1X06","Header 6","",')
newPart.addTag('rawParts','"JP6-DNP","XBEE","XBEE-1B1","XBEE-1","","",')
newPart.addTag('rawParts','"JP7","1X8","M09","1X09","Header 9","",')
newPart.addTag('rawParts','"JP8","1X2","M02PTH","1X02","Header 2","",')
newPart.addTag('rawParts','"JP9-DNP","RJ11-RAIN","RJ11-6PTH","RJ11-6","RJ11 Jack","",')
newPart.addTag('rawParts','"JP10-DNP","RJ11-WIND","RJ11-6PTH","RJ11-6","RJ11 Jack","",')
newPart.addTag('rawParts','"LOGO1","OSHW_LOGO_FILLX0100-NT","OSHW_LOGO_FILLX0100-NT","OSHW_FILLX100_NOTEXT","","",')
newPart.addTag('rawParts','"R1","750","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R2","180","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R3","10K","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R4","4.7K","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R5","4.7K","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R6","3.9K","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R7","1K","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R8","1K","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R9","2.2K","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R10","2.2K","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R11","1K","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R12","1K","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R13","1K","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R14","1K","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R15","1K","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R16","1K","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R17","4.7K","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"S1","POWER","SWITCH-SPSTSMD","AYZ0202","SPST Switch","",')
newPart.addTag('rawParts','"S2","RESET","TAC_SWITCHSMD","TACTILE_SWITCH_SMD","Momentary Switch","",')
newPart.addTag('rawParts','"S3","COM","SWITCH-DPDTSMD","AYZ0202","DPDT Version of the COM-00597","",')
newPart.addTag('rawParts','"SJ1","LIGHT","SOLDERJUMPERNC","SJ_2S","Solder Jumper","",')
newPart.addTag('rawParts','"SJ2","","SOLDERJUMPERNO","SJ_2S-NO","Solder Jumper","",')
newPart.addTag('rawParts','"U$1","LOGO-SFENEW","LOGO-SFENEW","SFE-NEW-WEBLOGO","Spark Fun Electronics PCB Logo","",')
newPart.addTag('rawParts','"U$2","STAND-OFF","STAND-OFF","STAND-OFF","Stand Off","",')
newPart.addTag('rawParts','"U$3","STAND-OFF","STAND-OFF","STAND-OFF","Stand Off","",')
newPart.addTag('rawParts','"U$4","STAND-OFF","STAND-OFF","STAND-OFF","Stand Off","",')
newPart.addTag('rawParts','"U$5","STAND-OFF","STAND-OFF","STAND-OFF","Stand Off","",')
newPart.addTag('rawParts','"U$6","CREATIVE_COMMONS","CREATIVE_COMMONS","CREATIVE_COMMONS","","",')
newPart.addTag('rawParts','"U1","ATMEGA328","AVR-MEGA8-AI","TQFP32-08","MICROCONTROLLER","",')
newPart.addTag('rawParts','"U2","MIC5219-3.3BM5","V_REG_LDOSMD","SOT23-5","Voltage Regulator LDO","VREG-9872",')
newPart.addTag('rawParts','"U3","FT232RL","FT232RL-BASICSSOP","SSOP28DB","USB UART","",')
newPart.addTag('rawParts','"U4","SHT15","SHT1XSMD","SHT1X","SHT1x Humdity Sensor","",')
newPart.addTag('rawParts','"U5","BMP085","BMP085","BMP085","BMP085 Pressure Sensor Great little MEMS pressure sensor. SKU: COM-09603","",')
newPart.addTag('rawParts','"U6","TEMT6000","TEMT6000","TEMT6000-SEN","Ambient Light Sensor","",')
newPart.addTag('rawParts','"Y1","8MHz","RESONATORSMD","RESONATOR-SMD","Resonator","",')