import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-2455-STAN-01")

newPart.addTag('rawParts','"C1","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C2","0.1uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C3","0.1uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C5","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"D1","1n4148","DIODESOD-323","SOD-323","Diode","",')
newPart.addTag('rawParts','"IC5","AXP803","AXP083-SAG","SOT23","","",')
newPart.addTag('rawParts','"JP2","CID:2608","HEADER-2X13-SMT","2X13_SMT_MALE","","",')
newPart.addTag('rawParts','"Q4","BSS138","MOSFET-NWIDE","SOT23-WIDE","N-Channel Mosfet","",')
newPart.addTag('rawParts','"R1","100","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R2","100","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R3","100","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R4","100","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R5","3.9K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R6","10K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R7","10K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R8","DNP","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R9","3.9K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R10","22","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R11","22","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R12","3.9K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R13","3.9K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"RPI1","RASPBERRYPI_BPLUS_HATNOSLOTS","RASPBERRYPI_BPLUS_HATNOSLOTS","PI_HAT_NOSLOTS","","",')
newPart.addTag('rawParts','"SJ1","WP","SOLDERJUMPER_CLOSED","SOLDERJUMPER_CLOSEDWIRE","Solder Jumper - Closed","",')
newPart.addTag('rawParts','"SJ2","BACKLITE","SOLDERJUMPER_CLOSED","SOLDERJUMPER_CLOSEDWIRE","Solder Jumper - Closed","",')
newPart.addTag('rawParts','"SW1","","SWITCH_PUSHBUTTONEVQ-PE","TACT_PANA-EVQ","Buttons","",')
newPart.addTag('rawParts','"SW2","","SWITCH_PUSHBUTTONEVQ-PE","TACT_PANA-EVQ","Buttons","",')
newPart.addTag('rawParts','"SW3","","SWITCH_PUSHBUTTONEVQ-PE","TACT_PANA-EVQ","Buttons","",')
newPart.addTag('rawParts','"SW4","","SWITCH_PUSHBUTTONEVQ-PE","TACT_PANA-EVQ","Buttons","",')
newPart.addTag('rawParts','"SW5","","SWITCH_PUSHBUTTONEVQ-PE","TACT_PANA-EVQ","Buttons","",')
newPart.addTag('rawParts','"U$2","DISP_LCD_240X320_50PIN-2.4IN","DISP_LCD_240X320_50PIN-2.4IN","TFT_2.4IN_240X320_50PIN","","",')
newPart.addTag('rawParts','"U$10","FIDUCIAL""","FIDUCIAL""","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"U$11","FIDUCIAL""","FIDUCIAL""","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"U$18","FIDUCIAL""","FIDUCIAL""","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"U1","CAT24C32","EEPROM_I2C_SOIC8_GENERIC","SOIC8_150MIL","Note: The same pinout is used for many I2C EEPROMs in SOIC8(150mil) from a variety of manufacturers and in various sizes.","",')
newPart.addTag('rawParts','"U2","STMPE610","STMPE610","QFN16_3MM","STMPE610 - 12-Bit Touch Screen Controller","",')