import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-13763-STAN-01")

newPart.addTag('rawParts','C2,0.1uF,0.1UF-25V(+80/-20%)(0603),0603-CAP,CAP-00810,CAP-00810,0.1uF,')
newPart.addTag('rawParts','FRAME2,FRAME-LETTER,FRAME-LETTER,CREATIVE_COMMONS,Schematic Frame,,,')
newPart.addTag('rawParts','JP1,,M04PTH,1X04,Header 4,,,')
newPart.addTag('rawParts','JP3,FIDUCIALUFIDUCIAL,FIDUCIALUFIDUCIAL,MICRO-FIDUCIAL,Fiducial Alignment Points,,,')
newPart.addTag('rawParts','JP4,FIDUCIALUFIDUCIAL,FIDUCIALUFIDUCIAL,MICRO-FIDUCIAL,Fiducial Alignment Points,,,')
newPart.addTag('rawParts','LOGO2,OSHW-LOGOS,OSHW-LOGOS,OSHW-LOGO-S,Open Source Hardware Logo This logo indicates the piece of hardware it is found on incorporates a OSHW license and/or adheres to the definition of open source hardware found here: http://freedomdefined.org/OSHW,,,')
newPart.addTag('rawParts','LOGO3,SFE_LOGO_FLAME.1_INCH,SFE_LOGO_FLAME.1_INCH,SFE_LOGO_FLAME_.1,SFE Logo, flame only,,,')
newPart.addTag('rawParts','LOGO4,SFE_LOGO_NAME.1_INCH,SFE_LOGO_NAME.1_INCH,SFE_LOGO_NAME_.1,SFE Logo, name only,,,')
newPart.addTag('rawParts','R1,4.7K,4.7KOHM-1/10W-1%(0603),0603-RES,RES-07857,RES-07857,4.7K,')
newPart.addTag('rawParts','R2,4.7K,4.7KOHM-1/10W-1%(0603),0603-RES,RES-07857,RES-07857,4.7K,')
newPart.addTag('rawParts','SJ1,,SOLDERJUMPER_2WAYPASTE1&2&3,SJ_3_PASTE1&2&3,Solder Jumper,,,')
newPart.addTag('rawParts','STANDOFF1,STAND-OFF,STAND-OFF,STAND-OFF,#4 Stand Off,,,')
newPart.addTag('rawParts','STANDOFF2,STAND-OFF,STAND-OFF,STAND-OFF,#4 Stand Off,,,')
newPart.addTag('rawParts','U1,SI7021,SI7021,SI7021,The Si7021 is an I2C Humidity and Temperature Sensor,IC-13093,,')