import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-13735-STAN-01")

newPart.addTag('rawParts','"D2","XZM2CRKM2DGFBB45SCCB","SUNLEDSMD1","PLCC4SMDLED","LED-RGB Common Cathode","DIO-13722","XZM2CRKM2DGFBB45SCCB",')
newPart.addTag('rawParts','"FD1","FIDUCIAL1X2","FIDUCIAL1X2","FIDUCIAL-1X2","Fiducial Alignment Points","","",')
newPart.addTag('rawParts','"FD2","FIDUCIAL1X2","FIDUCIAL1X2","FIDUCIAL-1X2","Fiducial Alignment Points","","",')
newPart.addTag('rawParts','"FD3","FIDUCIAL1X2","FIDUCIAL1X2","FIDUCIAL-1X2","Fiducial Alignment Points","","",')
newPart.addTag('rawParts','"FD4","FIDUCIAL1X2","FIDUCIAL1X2","FIDUCIAL-1X2","Fiducial Alignment Points","","",')
newPart.addTag('rawParts','"FRAME1","FRAME-LETTER","FRAME-LETTER","CREATIVE_COMMONS","Schematic Frame - Letter","","",')
newPart.addTag('rawParts','"LOGO1","REVISION","REVISION","REVISION",""Revision By" Text","","",')
newPart.addTag('rawParts','"LOGO2","OSHW-LOGOS","OSHW-LOGOS","OSHW-LOGO-S","Open-Source Hardware (OSHW) Logo","","",')
newPart.addTag('rawParts','"LOGO3","SFE_LOGO_FLAME.1_INCH","SFE_LOGO_FLAME.1_INCH","SFE_LOGO_FLAME_.1","SparkFun Flame Logo","","",')
newPart.addTag('rawParts','"R1","200","200OHM-0603-1/10W-1%","0603","200\xc3\x8e\xc2\xa9 resistor","RES-08220","200",')
newPart.addTag('rawParts','"R2","100","100OHM-0603-1/10W-1%","0603","100\xc3\x8e\xc2\xa9 resistor","RES-07863","100",')
newPart.addTag('rawParts','"R3","100","100OHM-0603-1/10W-1%","0603","100\xc3\x8e\xc2\xa9 resistor","RES-07863","100",')
newPart.addTag('rawParts','"U$1","LOGO-LPLP","LOGO-LPLP","LOGO-LILYPAD","","","",')
newPart.addTag('rawParts','"U$2","SEWTAP-NOHOLE2","SEWTAP-NOHOLE2","PETAL-NOHOLE-2SIDE","","","",')
newPart.addTag('rawParts','"U$3","SEWTAP-NOHOLE2","SEWTAP-NOHOLE2","PETAL-NOHOLE-2SIDE","","","",')
newPart.addTag('rawParts','"U$7","SEWTAP6","SEWTAP6","PETAL-SMALL-2SIDE","","","",')
newPart.addTag('rawParts','"U$8","SEWTAP6","SEWTAP6","PETAL-SMALL-2SIDE","","","",')
newPart.addTag('rawParts','"U$9","SEWTAP6","SEWTAP6","PETAL-SMALL-2SIDE","","","",')
newPart.addTag('rawParts','"U$10","SEWTAP6","SEWTAP6","PETAL-SMALL-2SIDE","","","",')