import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-10252-STAN-01")

newPart.addTag('rawParts','C1,0.1uF,CAP0603-CAP,0603-CAP,Capacitor,,')
newPart.addTag('rawParts','C2,0.1uF,CAP0603-CAP,0603-CAP,Capacitor,,')
newPart.addTag('rawParts','C3,2.2nF,CAP0603-CAP,0603-CAP,Capacitor,,')
newPart.addTag('rawParts','C4,10nF,CAP0603-CAP,0603-CAP,Capacitor,,')
newPart.addTag('rawParts','C5,1uF,CAP0603-CAP,0603-CAP,Capacitor,,')
newPart.addTag('rawParts','C6,0.1uF,CAP0603-CAP,0603-CAP,Capacitor,,')
newPart.addTag('rawParts','C7,470pF,CAP0603-CAP,0603-CAP,Capacitor,,')
newPart.addTag('rawParts','C8,10uF,CAP_POL1206,EIA3216,Capacitor Polarized,,')
newPart.addTag('rawParts','C9,10uF,CAP_POL1206,EIA3216,Capacitor Polarized,,')
newPart.addTag('rawParts','C10,0.1uF,CAP0603-CAP,0603-CAP,Capacitor,,')
newPart.addTag('rawParts','JP1,LOGO-SFENEW,LOGO-SFENEW,SFE-NEW-WEBLOGO,Spark Fun Electronics PCB Logo,,')
newPart.addTag('rawParts','JP2,FIDUCIAL1X2,FIDUCIAL1X2,FIDUCIAL-1X2,Fiducial Alignment Points,,')
newPart.addTag('rawParts','JP3,FIDUCIAL1X2,FIDUCIAL1X2,FIDUCIAL-1X2,Fiducial Alignment Points,,')
newPart.addTag('rawParts','JP4,STAND-OFF,STAND-OFF,STAND-OFF,Stand Off,,')
newPart.addTag('rawParts','JP5,STAND-OFF,STAND-OFF,STAND-OFF,Stand Off,,')
newPart.addTag('rawParts','JP6,STAND-OFF,STAND-OFF,STAND-OFF,Stand Off,,')
newPart.addTag('rawParts','JP7,STAND-OFF,STAND-OFF,STAND-OFF,Stand Off,,')
newPart.addTag('rawParts','JP8,,M07,1X07,Header 7,,')
newPart.addTag('rawParts','JP9,LOGO-SFESK,LOGO-SFESK,SFE-LOGO-FLAME,Spark Fun Electronics PCB Logo,,')
newPart.addTag('rawParts','R1,4.7k,RESISTOR0603-RES,0603-RES,Resistor,,')
newPart.addTag('rawParts','R2,4.7k,RESISTOR0603-RES,0603-RES,Resistor,,')
newPart.addTag('rawParts','U$1,CREATIVE_COMMONS,CREATIVE_COMMONS,CREATIVE_COMMONS,,,')
newPart.addTag('rawParts','U1,IMU3000,IMU3000,QFN-24,,,')
newPart.addTag('rawParts','U2,ADXL345,ADXL345,LGA14,,,')
newPart.addTag('rawParts','U3,3.3V,V_REG_LDOSMD,SOT23-5,Voltage Regulator LDO,,')