import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-11088-STAN-01")

newPart.addTag('rawParts','"C1","10uF","CAP_POL1206","EIA3216","Capacitor Polarized","",')
newPart.addTag('rawParts','"C2","10uF","CAP_POL1206","EIA3216","Capacitor Polarized","",')
newPart.addTag('rawParts','"C3","1uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C4","0.1uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C5","1uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C6","10uF","CAP_POL1206","EIA3216","Capacitor Polarized","",')
newPart.addTag('rawParts','"C7","0.1uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C8","1uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C9","470nF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C10","0.1uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C11","470nF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C12","10uF","CAP_POL1206","EIA3216","Capacitor Polarized","",')
newPart.addTag('rawParts','"C13","1uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C14","10uF","CAP_POL1206","EIA3216","Capacitor Polarized","",')
newPart.addTag('rawParts','"C15","0.1uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C16","470nF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"JP2","","M05PTH","1X05","Header 5","",')
newPart.addTag('rawParts','"JP8","","M06SIP","1X06","Header 6","",')
newPart.addTag('rawParts','"JP10","FIDUCIALUFIDUCIAL","FIDUCIALUFIDUCIAL","MICRO-FIDUCIAL","Fiducial Alignment Points","",')
newPart.addTag('rawParts','"JP11","FIDUCIALUFIDUCIAL","FIDUCIALUFIDUCIAL","MICRO-FIDUCIAL","Fiducial Alignment Points","",')
newPart.addTag('rawParts','"LED1","Red","LED0603","LED-0603","LEDs","",')
newPart.addTag('rawParts','"LED2","Blue","LED0603","LED-0603","LEDs","",')
newPart.addTag('rawParts','"LED3","Green","LED0603","LED-0603","LEDs","",')
newPart.addTag('rawParts','"R1","330","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R2","10K","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R3","330","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R4","330","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"SJ1","","SOLDERJUMPERTRACE","SJ_2S-TRACE","Solder Jumper","",')
newPart.addTag('rawParts','"SJ2","","SOLDERJUMPERTRACE","SJ_2S-TRACE","Solder Jumper","",')
newPart.addTag('rawParts','"U$1","LOGO-SFESK","LOGO-SFESK","SFE-LOGO-FLAME","Spark Fun Electronics PCB Logo","",')
newPart.addTag('rawParts','"U$2","CREATIVE_COMMONS","CREATIVE_COMMONS","CREATIVE_COMMONS","","",')
newPart.addTag('rawParts','"U$3","OSHW-LOGOS","OSHW-LOGOS","OSHW-LOGO-S","Open Source Hardware Logo This logo indicates the piece of hardware it is found on incorporates a OSHW license and/or adheres to the definition of open source hardware found here: http://freedomdefined.org/OSHW","",')
newPart.addTag('rawParts','"U$11","LOGO-SFENEW","LOGO-SFENEW","SFE-NEW-WEBLOGO","Spark Fun Electronics PCB Logo","",')
newPart.addTag('rawParts','"U1","MIC5219-3.3","V_REG_LDOSMD","SOT23-5","Voltage Regulator LDO","",')
newPart.addTag('rawParts','"U2","AP7311-1.8","V_REG_LDOSMD","SOT23-5","Voltage Regulator LDO","",')
newPart.addTag('rawParts','"U3","74HC4050","HEX_CONVERTER","SO016","","",')
newPart.addTag('rawParts','"U4","SPOT-CONNECT","SPOT-CONNECTSMD","SPOT-CONNECT","","",')
newPart.addTag('rawParts','"U5","ARDUINO_SHIELD","ARDUINO_SHIELDNO_SILK","DUEMILANOVE_VIAS","","",')
newPart.addTag('rawParts','"U6","MIC5219-3.0","V_REG_LDOSMD","SOT23-5","Voltage Regulator LDO","",')
newPart.addTag('rawParts','"U7","MIC5219-3.0","V_REG_LDOSMD","SOT23-5","Voltage Regulator LDO","",')