import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-4800-STAN-01")

newPart.addTag('rawParts','"C1","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C2","0.1uF","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C3","10\xc3\x82\xc2\xb5F","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C4","10\xc3\x82\xc2\xb5F","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C5","0.1uF","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C6","1uF","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C7","10\xc3\x82\xc2\xb5F","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C8","10\xc3\x82\xc2\xb5F","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C9","10uF/10V+","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C10","10\xc3\x82\xc2\xb5F","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C11","10\xc3\x82\xc2\xb5F","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C12","1uF","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C13","10\xc3\x82\xc2\xb5F","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C14","1uF","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C15","0.1uF","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C16","0.1uF","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C17","10\xc3\x82\xc2\xb5F","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C18","10\xc3\x82\xc2\xb5F","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C19","1uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C20","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C21","0.1uF","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C23","1uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C24","1uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C25","1uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C26","1uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C27","1uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C28","1uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C29","4.7uF/25V","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C30","1uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C31","1uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"CHG1","ORANGE","LED0603_NOOUTLINE","CHIPLED_0603_NOOUTLINE","LED","","","","","","","","",')
newPart.addTag('rawParts','"CONN1","STEMMA_I2C_QT","STEMMA_I2C_QT","JST_SH4","","","","","","","","","",')
newPart.addTag('rawParts','"D1","3.6V","DIODE-ZENERSOD323","SOD-323","Zener Diode","","","","","","","","",')
newPart.addTag('rawParts','"D2","MBR0530","DIODE-SCHOTTKYSOD-123","SOD-123","","","","","","","","","",')
newPart.addTag('rawParts','"D3","MBR0530","DIODE-SCHOTTKYSOD-123","SOD-123","","","","","","","","","",')
newPart.addTag('rawParts','"D4","MBR540","DIODE-SCHOTTKYSOD-123","SOD-123","","","","","","","","","",')
newPart.addTag('rawParts','"D5","MBR0530","DIODE-SCHOTTKYSOD-123","SOD-123","","","","","","","","","",')
newPart.addTag('rawParts','"D6","3.6V","DIODE-ZENERSOD323","SOD-323","Zener Diode","","","","","","","","",')
newPart.addTag('rawParts','"EINK2","EINK_24PIN_290IN","EINK_24PIN_290IN","EINK_290IN","","","","","","","","","",')
newPart.addTag('rawParts','"FID1","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","","EXCLUDE","","","","","","",')
newPart.addTag('rawParts','"FID2","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","","EXCLUDE","","","","","","",')
newPart.addTag('rawParts','"FID3","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","","EXCLUDE","","","","","","",')
newPart.addTag('rawParts','"FID4","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","","EXCLUDE","","","","","","",')
newPart.addTag('rawParts','"FID5","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","","EXCLUDE","","","","","","",')
newPart.addTag('rawParts','"FID6","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","","EXCLUDE","","","","","","",')
newPart.addTag('rawParts','"IC2","PAM8301","PAM8301","SOT23-6","","","","","","","","","",')
newPart.addTag('rawParts','"IC4","LIS3DH","ACCEL_LIS3DHTR","LGA16_3X3MM","LIS3DHTR 3-Axis Accelerometer with I2C/SPI Interface","","","","","","","","",')
newPart.addTag('rawParts','"JP2","UART","HEADER-1X2ROUND","1X02_ROUND","PIN HEADER","","","","","","","","",')
newPart.addTag('rawParts','"L","RED","LED0603_NOOUTLINE","CHIPLED_0603_NOOUTLINE","LED","","","","","","","","",')
newPart.addTag('rawParts','"L1","10uH","INDUCTORNR401","INDUCTOR_4X4MM_NR401","Inductors","","","","","","","","",')
newPart.addTag('rawParts','"LED2","WS2812B_4020","WS2812B_4020","WS2812B_4020","","","","","","","","","",')
newPart.addTag('rawParts','"LED3","WS2812B_4020","WS2812B_4020","WS2812B_4020","","","","","","","","","",')
newPart.addTag('rawParts','"LED4","WS2812B_4020","WS2812B_4020","WS2812B_4020","","","","","","","","","",')
newPart.addTag('rawParts','"LED5","WS2812B_4020","WS2812B_4020","WS2812B_4020","","","","","","","","","",')
newPart.addTag('rawParts','"ON","GREEN","LED0603_NOOUTLINE","CHIPLED_0603_NOOUTLINE","LED","","","","","","","","",')
newPart.addTag('rawParts','"Q1","DMG3415U-7","MOSFET-P","SOT23-R","P-Channel Mosfet","","","","","","","","",')
newPart.addTag('rawParts','"Q2","DMG3415","MOSFET-P","SOT23-R","P-Channel Mosfet","","","","","","","","",')
newPart.addTag('rawParts','"Q3","DMG3415U-7","MOSFET-P","SOT23-R","P-Channel Mosfet","","","","","","","","",')
newPart.addTag('rawParts','"Q5","IRLML0100","IRLML2060TRPBF","SOT23-3","","","","","","","","","",')
newPart.addTag('rawParts','"R1","10K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R2","10K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R3","5.1K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R4","5.1k","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R5","10K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R6","47K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R7","10K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R8","5.1K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R9","10K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R10","1Meg","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R11","1Meg","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R12","100k","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R13","0.47ohm","RESISTOR0805_10MGAP","0805_10MGAP","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R14","100k","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R15","100K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R16","1K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R17","1Meg","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R18","1K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R19","47K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R20","10K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R21","DNP","RESISTOR0805_10MGAP","0805_10MGAP","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R22","DNP","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R23","DNP","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R24","DNP","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R25","DNP","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R26","100K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R27","100K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"SENSE","JST PH 3","CON_JST_PH_3PIN","JSTPH3","","","","","","","","","",')
newPart.addTag('rawParts','"SENSE1","JST PH 3","CON_JST_PH_3PIN","JSTPH3","","","","","","","","","",')
newPart.addTag('rawParts','"SJ2","","SOLDERJUMPER_2WAY","SOLDERJUMPER_2WAY_OPEN_NOPASTE","2-Way Solder Jumper","","","","","","","","",')
newPart.addTag('rawParts','"SP1","7.5mm SPK","SPEAKER_7.5MM","BUZZER_SMT_7.5MM","SPEAKER Source: BuerklinAdded PS12 (for part # PS1240 piezo) http://www.ladyada.net/library/pcb/eaglelibrary.html","","","","","","","","",')
newPart.addTag('rawParts','"SW1","RA_TACT","SWITCH_SPST_TACT_RA","SPST_TACTILE_RA","Switch - SPST","","","","","","","","",')
newPart.addTag('rawParts','"SW2","","SWITCH_PUSHBUTTON_3.5X6MM","TACTILE_3X6MM","Buttons","","","","","","","","",')
newPart.addTag('rawParts','"SW3","RA_TACT","SWITCH_SPST_TACT_RA","SPST_TACTILE_RA","Switch - SPST","","","","","","","","",')
newPart.addTag('rawParts','"SW4","SPDT R/A","SWITCH_SPDT","SPDT_SMT_SSSS811101","Switch - SPDT","","","","","","","","",')
newPart.addTag('rawParts','"SW5","","SWITCH_PUSHBUTTON_3.5X6MM","TACTILE_3X6MM","Buttons","","","","","","","","",')
newPart.addTag('rawParts','"SW6","","SWITCH_PUSHBUTTON_3.5X6MM","TACTILE_3X6MM","Buttons","","","","","","","","",')
newPart.addTag('rawParts','"SW7","","SWITCH_PUSHBUTTON_3.5X6MM","TACTILE_3X6MM","Buttons","","","","","","","","",')
newPart.addTag('rawParts','"TP1","","TESTPOINTROUND1.5MMNO","TESTPOINT_ROUND_1.5MM_NO","Test Point","","","","","","","","",')
newPart.addTag('rawParts','"TP2","SEWTAP_SMTNUTM3","SEWTAP_SMTNUTM3","SMT_NUT_3MM","","","","","","","","","",')
newPart.addTag('rawParts','"TP3","SEWTAP_SMTNUTM3","SEWTAP_SMTNUTM3","SMT_NUT_3MM","","","","","","","","","",')
newPart.addTag('rawParts','"TP4","SEWTAP_SMTNUTM3","SEWTAP_SMTNUTM3","SMT_NUT_3MM","","","","","","","","","",')
newPart.addTag('rawParts','"TP5","SEWTAP_SMTNUTM3","SEWTAP_SMTNUTM3","SMT_NUT_3MM","","","","","","","","","",')
newPart.addTag('rawParts','"TP6","","TESTPOINTROUND1.5MMNO","TESTPOINT_ROUND_1.5MM_NO","Test Point","","","","","","","","",')
newPart.addTag('rawParts','"TP7","","TESTPOINTROUND1.5MMNO","TESTPOINT_ROUND_1.5MM_NO","Test Point","","","","","","","","",')
newPart.addTag('rawParts','"TP8","","TESTPOINTROUND1.5MMNO","TESTPOINT_ROUND_1.5MM_NO","Test Point","","","","","","","","",')
newPart.addTag('rawParts','"U1","","PHOTOTRANSISTOR_PT19-315C","ALS-PT19-315C","ALS-PT19-315C - Analog Light Sensor","","","","","","","","",')
newPart.addTag('rawParts','"U2","MCP73831T-2ACI/OT","MCP73831/2","SOT23-5","MCP73831/2 LIPO Charger","","","","","","","","",')
newPart.addTag('rawParts','"U3","ESP32-S2-WROVER","ESP32-S2-WROVER","MODULE_ESP32-S2-WROVER","WiFi 802.11b/g/n Transceiver Module 2.4GHz Antenna Not Included Surface Mount Check prices","Warning",""," WiFi 802.11b/g/n Transceiver Module 2.4GHz Antenna Not Included Surface Mount ","https://snapeda.com/shop?store=DigiKey&id=4614060","Espressif Systems","ESP32-S2-WROVER","VFQFN-56 Espressif Systems","None",')
newPart.addTag('rawParts','"U4","AP2112K-3.3","VREG_SOT23-5","SOT23-5","SOT23-5 Fixed Voltage Regulators","","","","","","","","",')
newPart.addTag('rawParts','"X1","JSTPH","CON_JST_PH_2PIN_BATT","JSTPH2_BATT","JST 2-Pin Right-Angle Connector","","","","","","","","",')
newPart.addTag('rawParts','"X4","USB C","USB_C","USB_C_CUSB31-CFM2AX-01-X","USB Type-C USB 2.0 Connector","","","","","","","","",')