import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-802-STAN-01")

newPart.addTag('oompParts','ANALOGS,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','BACKLITE,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','BTN1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','C1,CAPC-0805-X-UF10-V10')
newPart.addTag('oompParts','C2,CAPC-0805-X-UF10-V10')
newPart.addTag('oompParts','C3,CAPC-0805-X-NF100-V50')
newPart.addTag('oompParts','C4,CAPC-0805-X-NF100-V50')
newPart.addTag('oompParts','DIGITALS,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','DIGITALS2,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','IC1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','IC2,VREG-SO235-X-KLP298XS-V33D')
newPart.addTag('oompParts','NAV,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','POWER,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','Q1,UNMATCHED-SO23-X-UNMATCHED-01')
newPart.addTag('oompParts','R1,RESE-0805-X-UNMATCHED-01')
newPart.addTag('oompParts','R2,RESE-0805-X-O102-01')
newPart.addTag('oompParts','R3,RESE-0805-X-UNMATCHED-01')
newPart.addTag('oompParts','R4,RESE-0805-X-UNMATCHED-01')
newPart.addTag('oompParts','R5,RESE-0805-X-UNMATCHED-01')
newPart.addTag('oompParts','R6,RESE-0805-X-O103-01')
newPart.addTag('oompParts','R7,RESE-0805-X-UNMATCHED-01')
newPart.addTag('oompParts','R8,RESE-0805-X-UNMATCHED-01')
newPart.addTag('oompParts','R9,RESE-0805-X-O102-01')
newPart.addTag('oompParts','U$1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U$2,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U$3,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U$4,UNMATCHED-UNMATCHED-X-UNMATCHED-01')