import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-91-STAN-01")

newPart.addTag('oompParts','C1,CAPC-0805-X-NF100-V50')
newPart.addTag('oompParts','C2,CAPX-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','C3,CAPC-0805-X-NF100-V50')
newPart.addTag('oompParts','C4,CAPC-0805-X-NF100-V50')
newPart.addTag('oompParts','C5,CAPC-0805-X-UNMATCHED-01')
newPart.addTag('oompParts','C6,CAPC-0805-X-UNMATCHED-01')
newPart.addTag('oompParts','D1,LEDS-0805-G-STAN-01')
newPart.addTag('oompParts','D2,LEDS-0805-G-STAN-01')
newPart.addTag('oompParts','IC1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','IC2,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','JA1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','JD1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','JD2,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','JP3,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','JP4,HEAD-I01-X-PI04-01')
newPart.addTag('oompParts','L1,UNMATCHED-1206-X-UNMATCHED-01')
newPart.addTag('oompParts','R1,RESE-0805-X-O103-01')
newPart.addTag('oompParts','R2,RESE-0805-X-UNMATCHED-01')
newPart.addTag('oompParts','R3,RESE-0805-X-UNMATCHED-01')
newPart.addTag('oompParts','R4,RESE-0805-X-O102-01')
newPart.addTag('oompParts','R5,RESE-0805-X-UNMATCHED-01')
newPart.addTag('oompParts','R6,RESE-0805-X-UNMATCHED-01')
newPart.addTag('oompParts','RX,LEDS-0805-G-STAN-01')
newPart.addTag('oompParts','S1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','TX,LEDS-0805-G-STAN-01')
newPart.addTag('oompParts','USB,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','X1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')