import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-3133-STAN-01")

newPart.addTag('rawParts','"B1","CR1220","BATTERYCR1220_2","CR1220-2","CR1220 SMT - Digikey: 3001K-ND","",')
newPart.addTag('rawParts','"C1","0.1uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C2","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"FB1","Ferrite","FERRITE-0805NO","0805-NO","Ferrite Bead","",')
newPart.addTag('rawParts','"FID1","FIDUCIAL""","FIDUCIAL""","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"FID2","FIDUCIAL""","FIDUCIAL""","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"JP1","","HEADER-1X4ROUND","1X04_ROUND","PIN HEADER","",')
newPart.addTag('rawParts','"JP2","","HEADER-1X570MIL","1X05_ROUND_70","PIN HEADER","",')
newPart.addTag('rawParts','"JP3","","HEADER-1X2ROUND","1X02_ROUND","PIN HEADER","",')
newPart.addTag('rawParts','"JP4","","HEADER-1X10ROUND","1X10_ROUND","PIN HEADER","",')
newPart.addTag('rawParts','"LED1","RED","LED0805_NOOUTLINE","CHIPLED_0805_NOOUTLINE","LED","",')
newPart.addTag('rawParts','"MS1","FEATHERWING","FEATHERWING","FEATHERWING","","",')
newPart.addTag('rawParts','"Q1","DMG3415U-7 ","MOSFET-PWIDE","SOT23-WIDE","P-Channel Mosfet","",')
newPart.addTag('rawParts','"R1","470 ohm","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R2","100K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"SJ1","","SOLDERJUMPER","SOLDERJUMPER_ARROW_NOPASTE","SMD Solder JUMPER","EXCLUDE",')
newPart.addTag('rawParts','"SJ2","","SOLDERJUMPERCLOSED","SOLDERJUMPER_CLOSEDWIRE","SMD Solder JUMPER","",')
newPart.addTag('rawParts','"SJ3","","SOLDERJUMPERCLOSED","SOLDERJUMPER_CLOSEDWIRE","SMD Solder JUMPER","",')
newPart.addTag('rawParts','"SW1","KMR2","SWITCH_TACT_SMT4.6X2.8","BTN_KMR2_4.6X2.8","SMT Tact Switches","",')
newPart.addTag('rawParts','"TP1","","TESTPOINTROUND1.5MM","TESTPOINT_ROUND_1.5MM","Test Point","",')
newPart.addTag('rawParts','"U1","FGPMMOPA6H","GPS_FGPMMOPA6H","FGPMMOPA6H","GPS Module - MTK MT3339 Chipset, -165dBm sensitivity, 22 channels, 10Hz, auto-select external antenna options","",')
newPart.addTag('rawParts','"X1","uFL","ANTENNA_U.FL","U.FL","U.FL Antenna Connector","",')