import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-2857-STAN-01")

newPart.addTag('rawParts','C5,10uF,CAP_CERAMIC0805-NOOUTLINE,0805-NO,Ceramic Capacitors,,')
newPart.addTag('rawParts','C6,0.1uF,CAP_CERAMIC0603_NO,0603-NO,Ceramic Capacitors,,')
newPart.addTag('rawParts','CONN3,STEMMA_I2C_QT,STEMMA_I2C_QT,JST_SH4,,,')
newPart.addTag('rawParts','CONN4,STEMMA_I2C_QT,STEMMA_I2C_QT,JST_SH4,,,')
newPart.addTag('rawParts','D1,GREEN,LED0603_NOOUTLINE,CHIPLED_0603_NOOUTLINE,LED,,')
newPart.addTag('rawParts','FID3,FIDUCIAL_1MM,FIDUCIAL_1MM,FIDUCIAL_1MM,Fiducial Alignment Points,EXCLUDE,')
newPart.addTag('rawParts','FID4,FIDUCIAL_1MM,FIDUCIAL_1MM,FIDUCIAL_1MM,Fiducial Alignment Points,EXCLUDE,')
newPart.addTag('rawParts','JP1,,HEADER-1X770MIL,1X07_ROUND_70,PIN HEADER,,')
newPart.addTag('rawParts','R1,10K,RESISTOR_0603_NOOUT,0603-NO,Resistors,,')
newPart.addTag('rawParts','R5,10K,RESISTOR_4PACK,RESPACK_4X0603,Resistor Packs (4 resistors),,')
newPart.addTag('rawParts','SJ1,,SOLDERJUMPER,SOLDERJUMPER_ARROW_NOPASTE,SMD Solder JUMPER,EXCLUDE,')
newPart.addTag('rawParts','U$19,MOUNTINGHOLE2.5,MOUNTINGHOLE2.5,MOUNTINGHOLE_2.5_PLATED,Mounting Hole,EXCLUDE,')
newPart.addTag('rawParts','U$20,MOUNTINGHOLE2.5,MOUNTINGHOLE2.5,MOUNTINGHOLE_2.5_PLATED,Mounting Hole,EXCLUDE,')
newPart.addTag('rawParts','U2,,SHT3X,SHT3X,SHT3x - Digital Temperature and Humidity Sensor,,')