import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-10743-STAN-01")

newPart.addTag('rawParts','"C2","0.1uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C3","0.1uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C4","0.1uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C5","0.1uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C6","0.1uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C7","10uF","CAP_POL1206","EIA3216","Capacitor Polarized","",')
newPart.addTag('rawParts','"C8","10uF","CAP_POL1206","EIA3216","Capacitor Polarized","",')
newPart.addTag('rawParts','"C9","0.1uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C10","0.1uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"F1","PTCSMD","PTCSMD","PTC-1206","Resettable Fuse PTC","",')
newPart.addTag('rawParts','"J1","ISP","AVR_SPI_PRG_6PTH","2X3","AVR ISP 6 Pin","",')
newPart.addTag('rawParts','"JP1","LiPo","M02-JST-2MM-SMT","JST-2-SMD","Header 2","",')
newPart.addTag('rawParts','"JP2","PWMH","M08BM08B-SRSS-TB","BM08B-SRSS-TB","Header 8","",')
newPart.addTag('rawParts','"JP3","ADCH","M08BM08B-SRSS-TB","BM08B-SRSS-TB","Header 8","",')
newPart.addTag('rawParts','"JP4","ADCL","M08BM08B-SRSS-TB","BM08B-SRSS-TB","Header 8","",')
newPart.addTag('rawParts','"JP5","XIOH1","M08BM08B-SRSS-TB","BM08B-SRSS-TB","Header 8","",')
newPart.addTag('rawParts','"JP6","XIOH2","M08BM08B-SRSS-TB","BM08B-SRSS-TB","Header 8","",')
newPart.addTag('rawParts','"JP7","COMM","M08BM08B-SRSS-TB","BM08B-SRSS-TB","Header 8","",')
newPart.addTag('rawParts','"JP8","PWML","M08BM08B-SRSS-TB","BM08B-SRSS-TB","Header 8","",')
newPart.addTag('rawParts','"JP9","XIOL2","M08BM08B-SRSS-TB","BM08B-SRSS-TB","Header 8","",')
newPart.addTag('rawParts','"JP10","XIOL1","M08BM08B-SRSS-TB","BM08B-SRSS-TB","Header 8","",')
newPart.addTag('rawParts','"JP11","STAND-OFF","STAND-OFF","STAND-OFF","Stand Off","",')
newPart.addTag('rawParts','"JP12","POWER","M08BM08B-SRSS-TB","BM08B-SRSS-TB","Header 8","",')
newPart.addTag('rawParts','"JP13","STAND-OFF","STAND-OFF","STAND-OFF","Stand Off","",')
newPart.addTag('rawParts','"JP14","STAND-OFF","STAND-OFF","STAND-OFF","Stand Off","",')
newPart.addTag('rawParts','"JP15","STAND-OFF","STAND-OFF","STAND-OFF","Stand Off","",')
newPart.addTag('rawParts','"JP16","LOGO-SFENEW","LOGO-SFENEW","SFE-NEW-WEBLOGO","Spark Fun Electronics PCB Logo","",')
newPart.addTag('rawParts','"JP17","LOGO-SFESK","LOGO-SFESK","SFE-LOGO-FLAME","Spark Fun Electronics PCB Logo","",')
newPart.addTag('rawParts','"JP18","RAW","M02PTH","1X02","Header 2","",')
newPart.addTag('rawParts','"JP19","FTDI","ARDUINO_SERIAL_PROGRAMSMD","1X06-SMD","","",')
newPart.addTag('rawParts','"JP20","FIDUCIAL1X2.5","FIDUCIAL1X2.5","FIDUCIAL-1X2.5","Fiducial Alignment Points","",')
newPart.addTag('rawParts','"JP21","FIDUCIAL1X2.5","FIDUCIAL1X2.5","FIDUCIAL-1X2.5","Fiducial Alignment Points","",')
newPart.addTag('rawParts','"LED1","yellow","LED0603","LED-0603","LEDs","",')
newPart.addTag('rawParts','"LED2","green","LED0603","LED-0603","LEDs","",')
newPart.addTag('rawParts','"R1","1k","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R2","10k","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R3","10k","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R4","10k","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R7","1k","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"S1","SWITCH-MOMENTARY-2SMD","SWITCH-MOMENTARY-2SMD","TACTILE_SWITCH_SMD","","",')
newPart.addTag('rawParts','"SJ1","RESET-EN","SOLDERJUMPERNC","SJ_2S","Solder Jumper","",')
newPart.addTag('rawParts','"U$9","OSHW-LOGOL","OSHW-LOGOL","OSHW-LOGO-L","Open Source Hardware Logo This logo indicates the piece of hardware it is found on incorporates a OSHW license and/or adheres to the definition of open source hardware found here: http://freedomdefined.org/OSHW","",')
newPart.addTag('rawParts','"U1","ATMEGA2560AU","ATMEGA2560AU","TQFP100","MICROCONTROLLER","",')
newPart.addTag('rawParts','"U2","V_REG_3.3V","V_REG_LDOSMD","SOT23-5","Voltage Regulator LDO","",')
newPart.addTag('rawParts','"Y1","RESONATORSMD","RESONATORSMD","RESONATOR-SMD","Resonator","",')