import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-4745-STAN-01")

newPart.addTag('rawParts','"3VON","GREEN","LED0805_NOOUTLINE","CHIPLED_0805_NOOUTLINE","LED","",')
newPart.addTag('rawParts','"5VON","GREEN","LED0805_NOOUTLINE","CHIPLED_0805_NOOUTLINE","LED","",')
newPart.addTag('rawParts','"C1","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C2","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C3","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C4","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C5","0.1uF","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C6",".1u","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C7","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C8",".1u","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C9","1uF","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C10",".1u","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C11",".1u","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C13","0.1uF","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C14",".1u","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C15",".1u","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C16",".1u","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C17","0.1uF","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C18","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C19","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C20","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"CONN1","STEMMA_I2C_QT","STEMMA_I2C_QT","JST_SH4","","",')
newPart.addTag('rawParts','"D2","3.6V","DIODE-ZENERSOD323","SOD-323","Zener Diode","",')
newPart.addTag('rawParts','"DOWN","TL3330AF260QG","SWITCH_SPST_TACT_RA","SPST_TACTILE_RA","Switch - SPST","",')
newPart.addTag('rawParts','"FID1","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"FID2","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"FID3","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"FID4","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"JP1","","HEADER-1X11","1X11_ROUND","","",')
newPart.addTag('rawParts','"L","RED","LED0603_NOOUTLINE","CHIPLED_0603_NOOUTLINE","LED","",')
newPart.addTag('rawParts','"LED1","WS2812B3535","WS2812B3535","LED3535","","",')
newPart.addTag('rawParts','"PC2","47uF+/6.3V+","CAP_ELECTROLYTICPANASONIC_D","PANASONIC_D","Electrolytic Capacitors","",')
newPart.addTag('rawParts','"R1","10K","RESISTOR_0603_NOOUT","0603-NO","Resistors","",')
newPart.addTag('rawParts','"R2","10K","RESISTOR_0603_NOOUT","0603-NO","Resistors","",')
newPart.addTag('rawParts','"R3","5.1K","RESISTOR_0603_NOOUT","0603-NO","Resistors","",')
newPart.addTag('rawParts','"R4","1K","RESISTOR_0603_NOOUT","0603-NO","Resistors","",')
newPart.addTag('rawParts','"R5","10K","RESISTOR_0603_NOOUT","0603-NO","Resistors","",')
newPart.addTag('rawParts','"R6","10K","RESISTOR_0603_NOOUT","0603-NO","Resistors","",')
newPart.addTag('rawParts','"R7","10K","RESISTOR_0603_NOOUT","0603-NO","Resistors","",')
newPart.addTag('rawParts','"R8","5.1K","RESISTOR_0603_NOOUT","0603-NO","Resistors","",')
newPart.addTag('rawParts','"R9","1K","RESISTOR_0603_NOOUT","0603-NO","Resistors","",')
newPart.addTag('rawParts','"R10","5.1K","RESISTOR_4PACK","RESPACK_4X0603","Resistor Packs (4 resistors)","",')
newPart.addTag('rawParts','"R15","10K","RESISTOR_0603_NOOUT","0603-NO","Resistors","",')
newPart.addTag('rawParts','"RST","TL3330AF260QG","SWITCH_SPST_TACT_RA","SPST_TACTILE_RA","Switch - SPST","",')
newPart.addTag('rawParts','"SENSE","JST PH 3","CON_JST_PH_3PIN","JSTPH3","","",')
newPart.addTag('rawParts','"SJ1","","SOLDERJUMPER_2WAY","SOLDERJUMPER_2WAY_OPEN_NOPASTE","2-Way Solder Jumper","",')
newPart.addTag('rawParts','"SJ2","","SOLDERJUMPER_2WAY","SOLDERJUMPER_2WAY_OPEN_NOPASTE","2-Way Solder Jumper","",')
newPart.addTag('rawParts','"TP1","SEWTAP_SMTNUTM3","SEWTAP_SMTNUTM3","SMT_NUT_3MM","","",')
newPart.addTag('rawParts','"TP2","SEWTAP_SMTNUTM3","SEWTAP_SMTNUTM3","SMT_NUT_3MM","","",')
newPart.addTag('rawParts','"U$1","ATSAMD51J19","ATSAMD51J","PQFN64-1","ATSAMD51J cortex m4 microcontroller","",')
newPart.addTag('rawParts','"U1","74AHCT245","74LCX245","TSSOP20","74LCX245MTC - 5.0V Tolerant Bi-Directional Buffer","",')
newPart.addTag('rawParts','"U2","AP2112K-3.3","LP2985-XXDBVR33","SOT23-DBV","ULTRALOW-POWER 50-mA LOW-DROPOUT LINEAR REGULATORS","",')
newPart.addTag('rawParts','"U3","GD25Q16","SPIFLASH_8PIN208MIL","SOIC8_208MIL","SOIC8 SPI Flash","",')
newPart.addTag('rawParts','"U4","LIS3DHTR","ACCEL_LIS3DHTR","LGA16_3X3MM","LIS3DHTR 3-Axis Accelerometer with I2C/SPI Interface","",')
newPart.addTag('rawParts','"U5","74AHCT245","74LCX245","TSSOP20","74LCX245MTC - 5.0V Tolerant Bi-Directional Buffer","",')
newPart.addTag('rawParts','"UP","TL3330AF260QG","SWITCH_SPST_TACT_RA","SPST_TACTILE_RA","Switch - SPST","",')
newPart.addTag('rawParts','"X1","RGBMATRIX_THMSMT","RGBMATRIX_THMSMT","2X08_SMTTHM_RGBMATRIX","","",')
newPart.addTag('rawParts','"X5","USB TYPE C","USB_C","USB_C_CUSB31-CFM2AX-01-X","USB Type-C USB 2.0 Connector","",')
newPart.addTag('rawParts','"X6","ESP32_WROOM32","ESP32_WROOM32","WROOM32","","",')