import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-4683-STAN-01")

newPart.addTag('oompParts','C1,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')
newPart.addTag('oompParts','C2,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')
newPart.addTag('oompParts','IC1,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')
newPart.addTag('oompParts','JP1,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')
newPart.addTag('oompParts','R1,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')
newPart.addTag('oompParts','R2,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')
newPart.addTag('oompParts','R3,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')