import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-11018-STAN-01")

newPart.addTag('rawParts','C1,10uF,CAP_POL1206,EIA3216,Capacitor Polarized,,')
newPart.addTag('rawParts','C2,0.1uF,CAP0402-CAP,0402-CAP,Capacitor,,')
newPart.addTag('rawParts','C3,0.1uF,CAP0402-CAP,0402-CAP,Capacitor,,')
newPart.addTag('rawParts','C4,470pF,CAP0402-CAP,0402-CAP,Capacitor,,')
newPart.addTag('rawParts','JP1,,M01PTH,1X01,Header 1,,')
newPart.addTag('rawParts','JP2,Antenna,M01PTH,1X01,Header 1,,')
newPart.addTag('rawParts','JP3,,M01PTH,1X01,Header 1,,')
newPart.addTag('rawParts','JP4,,M01PTH,1X01,Header 1,,')
newPart.addTag('rawParts','JP5,,M01PTH,1X01,Header 1,,')
newPart.addTag('rawParts','JP6,,M01PTH,1X01,Header 1,,')
newPart.addTag('rawParts','JP7,FIDUCIALUFIDUCIAL,FIDUCIALUFIDUCIAL,MICRO-FIDUCIAL,Fiducial Alignment Points,,')
newPart.addTag('rawParts','JP8,FIDUCIALUFIDUCIAL,FIDUCIALUFIDUCIAL,MICRO-FIDUCIAL,Fiducial Alignment Points,,')
newPart.addTag('rawParts','LED1,Red,LED0603,LED-0603,LEDs,,')
newPart.addTag('rawParts','R1,10K,RESISTOR0402-RES,0402-RES,Resistor,,')
newPart.addTag('rawParts','R2,330,RESISTOR0402-RES,0402-RES,Resistor,,')
newPart.addTag('rawParts','S2,Reset,SWITCH-MOMENTARY-2SMD,TACTILE_SWITCH_SMD,,,')
newPart.addTag('rawParts','SJ1,NC,SOLDERJUMPERTRACE,SJ_2S-TRACE,Solder Jumper,,')
newPart.addTag('rawParts','SJ2,NO,SOLDERJUMPERNO,SJ_2S-NO,Solder Jumper,,')
newPart.addTag('rawParts','SJ3,NC,SOLDERJUMPERTRACE,SJ_2S-TRACE,Solder Jumper,,')
newPart.addTag('rawParts','SJ4,NC,SOLDERJUMPERTRACE,SJ_2S-TRACE,Solder Jumper,,')
newPart.addTag('rawParts','U$1,OSHW-LOGOS,OSHW-LOGOS,OSHW-LOGO-S,Open Source Hardware Logo This logo indicates the piece of hardware it is found on incorporates a OSHW license and/or adheres to the definition of open source hardware found here: http://freedomdefined.org/OSHW,,')
newPart.addTag('rawParts','U$3,CREATIVE_COMMONS,CREATIVE_COMMONS,CREATIVE_COMMONS,,,')
newPart.addTag('rawParts','U$7,LOGO-SFENEW,LOGO-SFENEW,SFE-NEW-WEBLOGO,Spark Fun Electronics PCB Logo,,')
newPart.addTag('rawParts','U$8,LOGO-SFENEW,LOGO-SFENEW,SFE-NEW-WEBLOGO,Spark Fun Electronics PCB Logo,,')
newPart.addTag('rawParts','U1,MIC5202-3.3V,V_REG_LDOSMD,SOT23-5,Voltage Regulator LDO,,')
newPart.addTag('rawParts','U2,RFM22,RFM22SMD,RFM22-XXX-S2,Description: The RFM22 is a low-power, low cost radio that is capable of operating in the 434MHz and 900MHz open bands. Its frequency is software defined and there are some very good libraries written for it.,,')
newPart.addTag('rawParts','U3,74HC4050 LVL CONVERTER,HEX_CONVERTER,SO016,,,')
newPart.addTag('rawParts','U4,ARDUINO_SHIELD,ARDUINO_SHIELDNOHOLES,DUEMILANOVE_SHIELD_NOHOLES,,,')