import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-4428-STAN-01")

newPart.addTag('rawParts','BUSY,TPTP15SQ,TPTP15SQ,TP15SQ,Test pad,,0,,')
newPart.addTag('rawParts','C1,10uF,CAP_CERAMIC0805-NOOUTLINE,0805-NO,Ceramic Capacitors,,,,')
newPart.addTag('rawParts','C2,10uF,CAP_CERAMIC0805-NOOUTLINE,0805-NO,Ceramic Capacitors,,,,')
newPart.addTag('rawParts','C3,10uF/10V+,CAP_CERAMIC0805-NOOUTLINE,0805-NO,Ceramic Capacitors,,,,')
newPart.addTag('rawParts','C5,1uF/10V,CAP_CERAMIC0805-NOOUTLINE,0805-NO,Ceramic Capacitors,,,,')
newPart.addTag('rawParts','C6,1uF/25V,CAP_CERAMIC0805-NOOUTLINE,0805-NO,Ceramic Capacitors,,,,')
newPart.addTag('rawParts','C7,1uF/25V,CAP_CERAMIC0805-NOOUTLINE,0805-NO,Ceramic Capacitors,,,,')
newPart.addTag('rawParts','C8,10uF/25V,CAP_CERAMIC0805-NOOUTLINE,0805-NO,Ceramic Capacitors,,,,')
newPart.addTag('rawParts','C9,1uF,CAP_CERAMIC0805-NOOUTLINE,0805-NO,Ceramic Capacitors,,,,')
newPart.addTag('rawParts','C10,1uF/10V,CAP_CERAMIC0805-NOOUTLINE,0805-NO,Ceramic Capacitors,,,,')
newPart.addTag('rawParts','C13,1uF,CAP_CERAMIC0805-NOOUTLINE,0805-NO,Ceramic Capacitors,,,,')
newPart.addTag('rawParts','C15,10uF,CAP_CERAMIC0805-NOOUTLINE,0805-NO,Ceramic Capacitors,,,,')
newPart.addTag('rawParts','C16,1uF,CAP_CERAMIC0805-NOOUTLINE,0805-NO,Ceramic Capacitors,,,,')
newPart.addTag('rawParts','C22,1uF/25V,CAP_CERAMIC0805-NOOUTLINE,0805-NO,Ceramic Capacitors,,,,')
newPart.addTag('rawParts','C23,1uF/25V,CAP_CERAMIC0805-NOOUTLINE,0805-NO,Ceramic Capacitors,,,,')
newPart.addTag('rawParts','C24,1uF,CAP_CERAMIC0805-NOOUTLINE,0805-NO,Ceramic Capacitors,,,,')
newPart.addTag('rawParts','D1,3.6V,DIODE-ZENERSOD323,SOD-323,Zener Diode,,,,')
newPart.addTag('rawParts','D2,3.6V,DIODE-ZENERSOD323,SOD-323,Zener Diode,,,,')
newPart.addTag('rawParts','D3,MBR0530,DIODE-SCHOTTKYSOD-123,SOD-123,,,,,')
newPart.addTag('rawParts','D4,MBR0530,DIODE-SCHOTTKYSOD-123,SOD-123,,,,,')
newPart.addTag('rawParts','D5,MBR0530,DIODE-SCHOTTKYSOD-123,SOD-123,,,,,')
newPart.addTag('rawParts','EINK2,EINK_24PIN_154IN,EINK_24PIN_154IN,EINK_154IN,,,,,')
newPart.addTag('rawParts','L1,10uH,INDUCTORNR401,INDUCTOR_4X4MM_NR401,Inductors,,,,')
newPart.addTag('rawParts','LEFT,JST PH 3,CON_JST_PH_3PIN,JSTPH3,,,,,')
newPart.addTag('rawParts','Q5,IRLML0100,IRLML2060TRPBF,SOT23-3,,,,,')
newPart.addTag('rawParts','R2,1K,RESISTOR_0603_NOOUT,0603-NO,Resistors,,,,')
newPart.addTag('rawParts','R5,1K,RESISTOR_0603_NOOUT,0603-NO,Resistors,,,,')
newPart.addTag('rawParts','R6,.47ohm,RESISTOR0805_10MGAP,0805_10MGAP,Resistors,,,,')
newPart.addTag('rawParts','R7,100K,RESISTOR_0603_NOOUT,0603-NO,Resistors,,,,')
newPart.addTag('rawParts','R12,100,RESISTOR_0603_NOOUT,0603-NO,Resistors,,,,')
newPart.addTag('rawParts','R13,100,RESISTOR_0603_NOOUT,0603-NO,Resistors,,,,')
newPart.addTag('rawParts','RIGHT,JST PH 3,CON_JST_PH_3PIN,JSTPH3,,,,,')
newPart.addTag('rawParts','TP1,,TESTPOINTROUND1.5MMNO,TESTPOINT_ROUND_1.5MM_NO,Test Point,,,,')
newPart.addTag('rawParts','TP2,SEWTAP_SMTNUTM3,SEWTAP_SMTNUTM3,SMT_NUT_3MM,,,,,')
newPart.addTag('rawParts','TP3,SEWTAP_SMTNUTM3,SEWTAP_SMTNUTM3,SMT_NUT_3MM,,,,,')
newPart.addTag('rawParts','TP4,SEWTAP_SMTNUTM3,SEWTAP_SMTNUTM3,SMT_NUT_3MM,,,,,')
newPart.addTag('rawParts','TP5,SEWTAP_SMTNUTM3,SEWTAP_SMTNUTM3,SMT_NUT_3MM,,,,,')
newPart.addTag('rawParts','TP6,SEWTAP_SMTNUTM3,SEWTAP_SMTNUTM3,SMT_NUT_3MM,,,,,')
newPart.addTag('rawParts','TP7,SEWTAP_SMTNUTM3,SEWTAP_SMTNUTM3,SMT_NUT_3MM,,,,,')
newPart.addTag('rawParts','TP8,SEWTAP_SMTNUTM3,SEWTAP_SMTNUTM3,SMT_NUT_3MM,,,,,')
newPart.addTag('rawParts','TP9,SEWTAP_SMTNUTM3,SEWTAP_SMTNUTM3,SMT_NUT_3MM,,,,,')
newPart.addTag('rawParts','TP10,SEWTAP_SMTNUTM3,SEWTAP_SMTNUTM3,SMT_NUT_3MM,,,,,')
newPart.addTag('rawParts','TP11,SEWTAP_SMTNUTM3,SEWTAP_SMTNUTM3,SMT_NUT_3MM,,,,,')
newPart.addTag('rawParts','TP12,SEWTAP_SMTNUTM3,SEWTAP_SMTNUTM3,SMT_NUT_3MM,,,,,')
newPart.addTag('rawParts','TP13,SEWTAP_SMTNUTM3,SEWTAP_SMTNUTM3,SMT_NUT_3MM,,,,,')
newPart.addTag('rawParts','TP14,,TESTPOINTROUND1.5MMNO,TESTPOINT_ROUND_1.5MM_NO,Test Point,,,,')
newPart.addTag('rawParts','TP15,,TESTPOINTROUND1.5MMNO,TESTPOINT_ROUND_1.5MM_NO,Test Point,,,,')
newPart.addTag('rawParts','TP16,,TESTPOINTROUND1.5MMNO,TESTPOINT_ROUND_1.5MM_NO,Test Point,,,,')
newPart.addTag('rawParts','TP17,,TESTPOINTROUND1.5MMNO,TESTPOINT_ROUND_1.5MM_NO,Test Point,,,,')
newPart.addTag('rawParts','TP18,,TESTPOINTROUND1.5MMNO,TESTPOINT_ROUND_1.5MM_NO,Test Point,,,,')
newPart.addTag('rawParts','U$1,CON_MOLEX_2P,CON_MOLEX_2P,53398-0271,,,,,')
newPart.addTag('rawParts','U$2,FIDUCIAL_1MM,FIDUCIAL_1MM,FIDUCIAL_1MM,Fiducial Alignment Points,EXCLUDE,,,')
newPart.addTag('rawParts','U$3,FIDUCIAL_1MM,FIDUCIAL_1MM,FIDUCIAL_1MM,Fiducial Alignment Points,EXCLUDE,,,')
newPart.addTag('rawParts','U$6,FIDUCIAL_1MM,FIDUCIAL_1MM,FIDUCIAL_1MM,Fiducial Alignment Points,EXCLUDE,,,')
newPart.addTag('rawParts','U5,PAM8302AASCR,AUDIOAMP_PAM8302A,MSOP8_0.65MM,PAM8302A - 2.5W Class-D Mono Audio Amplifier,,,,')
newPart.addTag('rawParts','VR2,10K trim,TRIMPOT3303W/X,TRIMPOT_BOURNS_3303W,3-Pin SMT Trimpots,,,,')