import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-2717-STAN-01")

newPart.addTag('rawParts','"A0","","SOLDERJUMPER","SOLDERJUMPER_ARROW_NOPASTE","SMD Solder JUMPER","EXCLUDE",')
newPart.addTag('rawParts','"A1","","SOLDERJUMPER","SOLDERJUMPER_ARROW_NOPASTE","SMD Solder JUMPER","EXCLUDE",')
newPart.addTag('rawParts','"A2","","SOLDERJUMPER","SOLDERJUMPER_ARROW_NOPASTE","SMD Solder JUMPER","EXCLUDE",')
newPart.addTag('rawParts','"C1","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"FID1","FIDUCIAL""","FIDUCIAL""","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"FID3","FIDUCIAL""","FIDUCIAL""","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"JP1","","HEADER-1X12","1X12_ROUND","","",')
newPart.addTag('rawParts','"JP3","","HEADER-1X12","1X12_ROUND","","",')
newPart.addTag('rawParts','"R1","10K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R2","10K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R3","10K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R4","10K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R5","10K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R6","10K","RESISTOR_0805MP","_0805MP","Resistors","",')
newPart.addTag('rawParts','"SCLPU","","SOLDERJUMPERCLOSED","SOLDERJUMPER_CLOSEDWIRE","SMD Solder JUMPER","",')
newPart.addTag('rawParts','"SDAPU","","SOLDERJUMPERCLOSED","SOLDERJUMPER_CLOSEDWIRE","SMD Solder JUMPER","",')
newPart.addTag('rawParts','"U$4","MOUNTINGHOLE2.5","MOUNTINGHOLE2.5","MOUNTINGHOLE_2.5_PLATED","Mounting Hole","EXCLUDE",')
newPart.addTag('rawParts','"U$5","MOUNTINGHOLE2.5","MOUNTINGHOLE2.5","MOUNTINGHOLE_2.5_PLATED","Mounting Hole","EXCLUDE",')
newPart.addTag('rawParts','"U1"," TCA9548APWR","TCA9548A","TSSOP24","TCA9548A I2C Multiplexer","",')