import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-12055-STAN-01")

newPart.addTag('rawParts','"C1","0.1uF","0.1UF-25V(+80/-20%)(0603)","0603-CAP","CAP-00810","CAP-00810","0.1uF",')
newPart.addTag('rawParts','"FID1","FIDUCIALUFIDUCIAL","FIDUCIALUFIDUCIAL","MICRO-FIDUCIAL","Fiducial Alignment Points","","",')
newPart.addTag('rawParts','"FID2","FIDUCIALUFIDUCIAL","FIDUCIALUFIDUCIAL","MICRO-FIDUCIAL","Fiducial Alignment Points","","",')
newPart.addTag('rawParts','"FRAME1","FRAME-LETTER","FRAME-LETTER","CREATIVE_COMMONS","Schematic Frame","","",')
newPart.addTag('rawParts','"JP1","","M05NO_SILK","1X05_NO_SILK","Header 5","","",')
newPart.addTag('rawParts','"LOGO1","OSHW-LOGOS","OSHW-LOGOS","OSHW-LOGO-S","Open Source Hardware Logo This logo indicates the piece of hardware it is found on incorporates a OSHW license and/or adheres to the definition of open source hardware found here: http://freedomdefined.org/OSHW","","",')
newPart.addTag('rawParts','"LOGO2","LOGO-SFENW2","LOGO-SFENW2","SFE-NEW-WEB","Spark Fun Electronics PCB Logo","","",')
newPart.addTag('rawParts','"LOGO3","SFE_LOGO_FLAME.1_INCH","SFE_LOGO_FLAME.1_INCH","SFE_LOGO_FLAME_.1","SFE Logo, flame only","","",')
newPart.addTag('rawParts','"R1","10K","10KOHM-1/10W-1%(0603)0603","0603-RES","RES-00824","RES-00824","10K",')
newPart.addTag('rawParts','"R2","4.7K","4.7KOHM-1/10W-1%(0603)","0603-RES","RES-07857","RES-07857","4.7K",')
newPart.addTag('rawParts','"R3","4.7K","4.7KOHM-1/10W-1%(0603)","0603-RES","RES-07857","RES-07857","4.7K",')
newPart.addTag('rawParts','"R4","10K","10KOHM-1/10W-1%(0603)0603","0603-RES","RES-00824","RES-00824","10K",')
newPart.addTag('rawParts','"SJ1","JUMPER-PAD-3-NC_BY_PASTE","JUMPER-PAD-3-NC_BY_PASTE","PAD-JUMPER-3-NC_BY_PASTE_YES_SILK_FULL_BOX","","","",')
newPart.addTag('rawParts','"SJ2","","SOLDERJUMPER_2WAYS","SJ_3","Solder Jumper","","",')
newPart.addTag('rawParts','"STANDOFF1","STAND-OFF","STAND-OFF","STAND-OFF","#4 Stand Off","","",')
newPart.addTag('rawParts','"STANDOFF2","STAND-OFF","STAND-OFF","STAND-OFF","#4 Stand Off","","",')
newPart.addTag('rawParts','"U1","TSL2561FN","TSL2561FN","FN-6","TSL2561 illumination sensor","IC-11791","",')