import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-9598-STAN-01")

newPart.addTag('rawParts','D1,,DIODESMA,SMA-DIODE,Diode,,')
newPart.addTag('rawParts','JP1,FIDUCIAL1X2,FIDUCIAL1X2,FIDUCIAL-1X2,Fiducial Alignment Points,,')
newPart.addTag('rawParts','JP2,FIDUCIAL1X2,FIDUCIAL1X2,FIDUCIAL-1X2,Fiducial Alignment Points,,')
newPart.addTag('rawParts','JP3,LOGO-SFENEW,LOGO-SFENEW,SFE-NEW-WEBLOGO,Spark Fun Electronics PCB Logo,,')
newPart.addTag('rawParts','JP4,,M06SIP,1X06,Header 6,,')
newPart.addTag('rawParts','JP5,,M06SIP,1X06,Header 6,,')
newPart.addTag('rawParts','JP6,,M06SIP,1X06,Header 6,,')
newPart.addTag('rawParts','JP7,,M06SIP,1X06,Header 6,,')
newPart.addTag('rawParts','JP8,,M06SIP,1X06,Header 6,,')
newPart.addTag('rawParts','JP9,,M06SIP,1X06,Header 6,,')
newPart.addTag('rawParts','JP10,,M06SIP,1X06,Header 6,,')
newPart.addTag('rawParts','JP11,LOGO-SFENEW,LOGO-SFENEW,SFE-NEW-WEBLOGO,Spark Fun Electronics PCB Logo,,')
newPart.addTag('rawParts','R1,220,RESISTOR0402-RES,0402-RES,Resistor,,')
newPart.addTag('rawParts','R2,220,RESISTOR0402-RES,0402-RES,Resistor,,')
newPart.addTag('rawParts','R3,220,RESISTOR0402-RES,0402-RES,Resistor,,')
newPart.addTag('rawParts','R4,220,RESISTOR0402-RES,0402-RES,Resistor,,')
newPart.addTag('rawParts','R5,220,RESISTOR0402-RES,0402-RES,Resistor,,')
newPart.addTag('rawParts','R6,220,RESISTOR0402-RES,0402-RES,Resistor,,')
newPart.addTag('rawParts','S3,,TAC_SWITCHSMD,TACTILE_SWITCH_SMD,Momentary Switch,,')
newPart.addTag('rawParts','S5,,SWITCH-SPSTSMD,AYZ0202,SPST Switch,,')
newPart.addTag('rawParts','U$1,ARDUINO_VIAS_ONLY,ARDUINO_VIAS_ONLY,DUEMILANOVE_VIAS,,,')
newPart.addTag('rawParts','U$2,MIDI_CONN_FEMALE_SUPPORT,MIDI_CONN_FEMALE_SUPPORT,DIN_5_FEMALE_SUPPORT,,,')
newPart.addTag('rawParts','U$3,MIDI_CONN_FEMALE_SUPPORT,MIDI_CONN_FEMALE_SUPPORT,DIN_5_FEMALE_SUPPORT,,,')
newPart.addTag('rawParts','U$5,MIDI_CONN_FEMALE_SUPPORT,MIDI_CONN_FEMALE_SUPPORT,DIN_5_FEMALE_SUPPORT,,,')
newPart.addTag('rawParts','U$6,OPTO_DARL_6N138S,OPTO_DARL_6N138S,8-SMD,,,')