import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-11117-STAN-01")

newPart.addTag('rawParts','"C1","0.1uF","CAP0603-CAP","0603-CAP","Capacitor","",')
newPart.addTag('rawParts','"C2","18pF","CAP0603-CAP","0603-CAP","Capacitor","",')
newPart.addTag('rawParts','"C3","18pF","CAP0603-CAP","0603-CAP","Capacitor","",')
newPart.addTag('rawParts','"C4","1uF","CAP0603-CAP","0603-CAP","Capacitor","",')
newPart.addTag('rawParts','"C5","1uF","CAP0603-CAP","0603-CAP","Capacitor","",')
newPart.addTag('rawParts','"C6","0.1uF","CAP0603-CAP","0603-CAP","Capacitor","",')
newPart.addTag('rawParts','"C7","0.1uF","CAP0603-CAP","0603-CAP","Capacitor","",')
newPart.addTag('rawParts','"C8","10uF","CAP_POL1206","EIA3216","Capacitor Polarized","",')
newPart.addTag('rawParts','"C9","0.1uF","CAP0603-CAP","0603-CAP","Capacitor","",')
newPart.addTag('rawParts','"F1","PTCSMD","PTCSMD","PTC-1206","Resettable Fuse PTC","",')
newPart.addTag('rawParts','"J1","AVR_SPI_PRG","AVR_SPI_PRG_6PTH","2X3","AVR ISP 6 Pin","",')
newPart.addTag('rawParts','"JP1","M12PTH","M12PTH","1X12","Header 12","",')
newPart.addTag('rawParts','"JP2","M12PTH","M12PTH","1X12","Header 12","",')
newPart.addTag('rawParts','"JP3","","M06SIP","1X06","Header 6","",')
newPart.addTag('rawParts','"JP6","FIDUCIAL1X2","FIDUCIAL1X2","FIDUCIAL-1X2","Fiducial Alignment Points","",')
newPart.addTag('rawParts','"JP7","FIDUCIAL1X2","FIDUCIAL1X2","FIDUCIAL-1X2","Fiducial Alignment Points","",')
newPart.addTag('rawParts','"JP8","LOGO-SFENEW","LOGO-SFENEW","SFE-NEW-WEBLOGO","Spark Fun Electronics PCB Logo","",')
newPart.addTag('rawParts','"LED1","Power","LED0603","LED-0603","LEDs","",')
newPart.addTag('rawParts','"R1","10k","RESISTOR0603-RES","0603-RES","Resistor","",')
newPart.addTag('rawParts','"R2","22","RESISTOR0603-RES","0603-RES","Resistor","",')
newPart.addTag('rawParts','"R3","22","RESISTOR0603-RES","0603-RES","Resistor","",')
newPart.addTag('rawParts','"R4","1k","RESISTOR0603-RES","0603-RES","Resistor","",')
newPart.addTag('rawParts','"S1","SWITCH-SMD","SWITCH-MOMENTARY-2SMD","TACTILE_SWITCH_SMD","","",')
newPart.addTag('rawParts','"SJ1","Power Select","SOLDERJUMPER_2WAYPASTE2&3","SJ_3_PASTE2&3","Solder Jumper","",')
newPart.addTag('rawParts','"U$6","OSHW-LOGOM","OSHW-LOGOM","OSHW-LOGO-M","Open Source Hardware Logo This logo indicates the piece of hardware it is found on incorporates a OSHW license and/or adheres to the definition of open source hardware found here: http://freedomdefined.org/OSHW","",')
newPart.addTag('rawParts','"U1","ATMEGA32U4","ATMEGA32U41:1","QFN-44-NOPAD_1:1","Atmel 44-pin 8-bit Microcontroller with 32KBytes of ISP Flash and USB Controller","",')
newPart.addTag('rawParts','"U2","3.3V_REG_LDOSMD","V_REG_LDOSMD","SOT23-5","Voltage Regulator LDO","",')
newPart.addTag('rawParts','"X1","USBSMD","USBSMD","USB-MINIB","USB Connectors","",')
newPart.addTag('rawParts','"Y1","16MHz","CRYSTAL5X3","CRYSTAL-SMD-5X3","Crystals","",')