import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-11282-STAN-01")

newPart.addTag('rawParts','"C1","0.1uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C2","0.1uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"JP1","","M06SIP","1X06","Header 6","",')
newPart.addTag('rawParts','"JP2","LOGO-SFENW2","LOGO-SFENW2","SFE-NEW-WEB","Spark Fun Electronics PCB Logo","",')
newPart.addTag('rawParts','"JP3","FIDUCIALUFIDUCIAL","FIDUCIALUFIDUCIAL","MICRO-FIDUCIAL","Fiducial Alignment Points","",')
newPart.addTag('rawParts','"JP4","FIDUCIALUFIDUCIAL","FIDUCIALUFIDUCIAL","MICRO-FIDUCIAL","Fiducial Alignment Points","",')
newPart.addTag('rawParts','"LOGO1","LOGO-SFESK","LOGO-SFESK","SFE-LOGO-FLAME","Spark Fun Electronics PCB Logo","",')
newPart.addTag('rawParts','"R1","4.7k","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R2","4.7k","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"SJ1","","SOLDERJUMPER_2WAYPASTE1&2&3","SJ_3_PASTE1&2&3","Solder Jumper","",')
newPart.addTag('rawParts','"STANDOFF1","STAND-OFF","STAND-OFF","STAND-OFF","#4 Stand Off","",')
newPart.addTag('rawParts','"STANDOFF2","STAND-OFF","STAND-OFF","STAND-OFF","#4 Stand Off","",')
newPart.addTag('rawParts','"U1","BMP085","BMP085","BMP085","BMP085 Pressure Sensor Great little MEMS pressure sensor. SKU: COM-09603","",')