import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-11525-STAN-01")

newPart.addTag('rawParts','C1,0.1uF,CAP0402-CAP,0402-CAP,Capacitor,,')
newPart.addTag('rawParts','C2,10uF,CAP_POL1206,EIA3216,Capacitor Polarized,,')
newPart.addTag('rawParts','C3,10uF,CAP_POL1206,EIA3216,Capacitor Polarized,,')
newPart.addTag('rawParts','C4,0.1uF,CAP0402-CAP,0402-CAP,Capacitor,,')
newPart.addTag('rawParts','FRAME1,FRAME-LETTER,FRAME-LETTER,CREATIVE_COMMONS,Schematic Frame,,')
newPart.addTag('rawParts','JP1,PropPlug,M04PTH,1X04,Header 4,,')
newPart.addTag('rawParts','JP2,M20,M20,1X20,1x20 .1 header,,')
newPart.addTag('rawParts','JP3,M20,M20,1X20,1x20 .1 header,,')
newPart.addTag('rawParts','JP4,FIDUCIALUFIDUCIAL,FIDUCIALUFIDUCIAL,MICRO-FIDUCIAL,Fiducial Alignment Points,,')
newPart.addTag('rawParts','JP5,LOGO-SFENEW,LOGO-SFENEW,SFE-NEW-WEBLOGO,Spark Fun Electronics PCB Logo,,')
newPart.addTag('rawParts','JP7,LOGO-SFESK,LOGO-SFESK,SFE-LOGO-FLAME,Spark Fun Electronics PCB Logo,,')
newPart.addTag('rawParts','JP9,FTDI_BASICPTH,FTDI_BASICPTH,FTDI_BASIC,FTDI Basic header with labels,,')
newPart.addTag('rawParts','JP10,STAND-OFF,STAND-OFF,STAND-OFF,#4 Stand Off,,')
newPart.addTag('rawParts','JP11,STAND-OFF,STAND-OFF,STAND-OFF,#4 Stand Off,,')
newPart.addTag('rawParts','JP12,STAND-OFF,STAND-OFF,STAND-OFF,#4 Stand Off,,')
newPart.addTag('rawParts','JP13,STAND-OFF,STAND-OFF,STAND-OFF,#4 Stand Off,,')
newPart.addTag('rawParts','JP14,LOGO-SFENW2,LOGO-SFENW2,SFE-NEW-WEB,Spark Fun Electronics PCB Logo,,')
newPart.addTag('rawParts','JP15,FIDUCIALUFIDUCIAL,FIDUCIALUFIDUCIAL,MICRO-FIDUCIAL,Fiducial Alignment Points,,')
newPart.addTag('rawParts','LED1,red,LED0603,LED-0603,LEDs,,')
newPart.addTag('rawParts','LED2,yellow,LED0603,LED-0603,LEDs,,')
newPart.addTag('rawParts','R1,330,RESISTOR0402-RES,0402-RES,Resistor,,')
newPart.addTag('rawParts','R2,330,RESISTOR0402-RES,0402-RES,Resistor,,')
newPart.addTag('rawParts','R3,10k,RESISTOR0402-RES,0402-RES,Resistor,,')
newPart.addTag('rawParts','R4,240,RESISTOR0402-RES,0402-RES,Resistor,,')
newPart.addTag('rawParts','R5,390,RESISTOR0402-RES,0402-RES,Resistor,,')
newPart.addTag('rawParts','R6,10k,RESISTOR0402-RES,0402-RES,Resistor,,')
newPart.addTag('rawParts','SJ1,SOLDERJUMPERTRACE,SOLDERJUMPERTRACE,SJ_2S-TRACE,Solder Jumper,,')
newPart.addTag('rawParts','U$1,OSHW-LOGOS,OSHW-LOGOS,OSHW-LOGO-S,Open Source Hardware Logo This logo indicates the piece of hardware it is found on incorporates a OSHW license and/or adheres to the definition of open source hardware found here: http://freedomdefined.org/OSHW,,')
newPart.addTag('rawParts','U1,,P8X32A-Q44,P8X32A-Q44,Propellor uC,,')
newPart.addTag('rawParts','U3,EEPROM-I2CEIAJ,EEPROM-I2CEIAJ,SO08-EIAJ,I2C EEPROM chips, 24LC256 (and others),,')
newPart.addTag('rawParts','U4,V_REG_317SMD,V_REG_317SMD,SOT223,Voltage Regulator,,')
newPart.addTag('rawParts','Y1,,CRYSTALHC49UV,HC49U-V,Various standard crystals. Proven footprints. Spark Fun Electronics SKU : COM-00534,,')