import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-5020-STAN-01")

newPart.addTag('oompParts','C3,CAPC-0805-X-UF10-V10')
newPart.addTag('oompParts','C4,CAPC-0603-X-UF1-01')
newPart.addTag('oompParts','C5,CAPC-0603-X-UF1-01')
newPart.addTag('oompParts','C8,CAPC-0805-X-UF10-V10')
newPart.addTag('oompParts','CN1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','IC3,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','LED1,LEDS-3535-RGB-K2812-01')
newPart.addTag('oompParts','RESET,BUTA-4628-X-STAN-01')
newPart.addTag('oompParts','RST,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','SW1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','SWC,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','SWD,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U1,VREG-SO235-X-KAP2112K-V33D')