import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-4074-STAN-01")

newPart.addTag('rawParts','C1,10uF,CAP_CERAMIC0805-NOOUTLINE,0805-NO,Ceramic Capacitors,,')
newPart.addTag('rawParts','C2,10uF,CAP_CERAMIC0805-NOOUTLINE,0805-NO,Ceramic Capacitors,,')
newPart.addTag('rawParts','C3,10uF,CAP_CERAMIC0805-NOOUTLINE,0805-NO,Ceramic Capacitors,,')
newPart.addTag('rawParts','C4,0.1uF,CAP_CERAMIC0603_NO,0603-NO,Ceramic Capacitors,,')
newPart.addTag('rawParts','C5,1uF,CAP_CERAMIC0603_NO,0603-NO,Ceramic Capacitors,,')
newPart.addTag('rawParts','C6,1uF,CAP_CERAMIC0603_NO,0603-NO,Ceramic Capacitors,,')
newPart.addTag('rawParts','C8,10uF,CAP_CERAMIC0805-NOOUTLINE,0805-NO,Ceramic Capacitors,,')
newPart.addTag('rawParts','C9,10uF,CAP_CERAMIC0805-NOOUTLINE,0805-NO,Ceramic Capacitors,,')
newPart.addTag('rawParts','CONN1,HEADER-1X25,HEADER-1X25,1X25_ROUND_70MIL,,,')
newPart.addTag('rawParts','CS,,SOLDERJUMPERCLOSED,SOLDERJUMPER_CLOSEDWIRE,SMD Solder JUMPER,,')
newPart.addTag('rawParts','DIO0,,SOLDERJUMPERCLOSED,SOLDERJUMPER_CLOSEDWIRE,SMD Solder JUMPER,,')
newPart.addTag('rawParts','DIO1,,SOLDERJUMPERCLOSED,SOLDERJUMPER_CLOSEDWIRE,SMD Solder JUMPER,,')
newPart.addTag('rawParts','DIO2,,SOLDERJUMPERCLOSED,SOLDERJUMPER_CLOSEDWIRE,SMD Solder JUMPER,,')
newPart.addTag('rawParts','FID1,FIDUCIAL_1MM,FIDUCIAL_1MM,FIDUCIAL_1MM,Fiducial Alignment Points,EXCLUDE,')
newPart.addTag('rawParts','FID2,FIDUCIAL_1MM,FIDUCIAL_1MM,FIDUCIAL_1MM,Fiducial Alignment Points,EXCLUDE,')
newPart.addTag('rawParts','IC5,APX803,AXP083-SAG,SOT23,,,')
newPart.addTag('rawParts','JP1,,HEADER-1X570MIL,1X05_ROUND_70,PIN HEADER,,')
newPart.addTag('rawParts','JP2,,HEADER-1X3ROUND,1X03_ROUND,PIN HEADER,,')
newPart.addTag('rawParts','JP3,,HEADER-1X570MIL,1X05_ROUND_70,PIN HEADER,,')
newPart.addTag('rawParts','JP6,,HEADER-1X1ROUND,1X01_ROUND,PIN HEADER,,')
newPart.addTag('rawParts','LCD1,OLED 128x32,DISP_OLED_UG-2832HSWEG02,UG-2832HSWEG02_WRAPUNDER,128x32 I2C 0.91 Monochrome OLED Display,,')
newPart.addTag('rawParts','MISO,,SOLDERJUMPERCLOSED,SOLDERJUMPER_CLOSEDWIRE,SMD Solder JUMPER,,')
newPart.addTag('rawParts','MOSI,,SOLDERJUMPERCLOSED,SOLDERJUMPER_CLOSEDWIRE,SMD Solder JUMPER,,')
newPart.addTag('rawParts','R3,390K,RESISTOR_0603_NOOUT,0603-NO,Resistors,,')
newPart.addTag('rawParts','R5,10K,RESISTOR_4PACK,RESPACK_4X0603,Resistor Packs (4 resistors),,')
newPart.addTag('rawParts','RPI1,RASPBERRYPI_BPLUS_BONNET_THMSMT,RASPBERRYPI_BPLUS_BONNET_THMSMT,PI_BONNET_THMSMT,,,')
newPart.addTag('rawParts','RST,,SOLDERJUMPERCLOSED,SOLDERJUMPER_CLOSEDWIRE,SMD Solder JUMPER,,')
newPart.addTag('rawParts','SCK,,SOLDERJUMPERCLOSED,SOLDERJUMPER_CLOSEDWIRE,SMD Solder JUMPER,,')
newPart.addTag('rawParts','SW1,6mm,SWITCH_TACT_SMT_EVQQ2_SMALL,EVQ-Q2_SMALLER,SMT Tact Switches,,')
newPart.addTag('rawParts','SW2,6mm,SWITCH_TACT_SMT_EVQQ2_SMALL,EVQ-Q2_SMALLER,SMT Tact Switches,,')
newPart.addTag('rawParts','SW3,6mm,SWITCH_TACT_SMT_EVQQ2_SMALL,EVQ-Q2_SMALLER,SMT Tact Switches,,')
newPart.addTag('rawParts','U1,AP2112K-3.3,VREG_SOT23-5,SOT23-5,SOT23-5 Fixed Voltage Regulators,,')
newPart.addTag('rawParts','U4,RFM69/9x,RFM69HCW_SMT,RFMHCW_SMT,RFM69HCW - ISM Band RF Transceiver,,')
newPart.addTag('rawParts','X1,uFL/SMA,SMACONNECTOR_EDGE_UFL,SMA_EDGELAUNCH_UFL,SMA Connector,,')