import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-14890-STAN-01")

newPart.addTag('rawParts','"D2","RED","LED-RED1206","LED-1206","Red SMD LED","DIO-09912","RED",')
newPart.addTag('rawParts','"D3","WHITE","LED-WHITE1206","LED-1206","White SMD LED","DIO-09955","WHITE",')
newPart.addTag('rawParts','"D4","BLUE","LED-BLUE1206","LED-1206","Blue SMD LED","DIO-09911","BLUE",')
newPart.addTag('rawParts','"D5","Yellow","LED-YELLOWLILYPAD","LED-1206","Yellow SMD LED","DIO-09909","Yellow",')
newPart.addTag('rawParts','"D6","GREEN","LED-GREEN1206","LED-1206","Green SMD LED","DIO-00862","GREEN",')
newPart.addTag('rawParts','"D9","WHITE","LED-WHITE1206","LED-1206","White SMD LED","DIO-09955","WHITE",')
newPart.addTag('rawParts','"FD1","FIDUCIALUFIDUCIAL","FIDUCIALUFIDUCIAL","FIDUCIAL-MICRO","Fiducial Alignment Points","","",')
newPart.addTag('rawParts','"FD2","FIDUCIALUFIDUCIAL","FIDUCIALUFIDUCIAL","FIDUCIAL-MICRO","Fiducial Alignment Points","","",')
newPart.addTag('rawParts','"FD3","FIDUCIALUFIDUCIAL","FIDUCIALUFIDUCIAL","FIDUCIAL-MICRO","Fiducial Alignment Points","","",')
newPart.addTag('rawParts','"FD4","FIDUCIALUFIDUCIAL","FIDUCIALUFIDUCIAL","FIDUCIAL-MICRO","Fiducial Alignment Points","","",')
newPart.addTag('rawParts','"FRAME1","FRAME-LETTER","FRAME-LETTER","CREATIVE_COMMONS","Schematic Frame - Letter","","",')
newPart.addTag('rawParts','"LOGO1","SFE_LOGO_FLAME.1_INCH","SFE_LOGO_FLAME.1_INCH","SFE_LOGO_FLAME_.1","SparkFun Flame Logo","","",')
newPart.addTag('rawParts','"LOGO2","OSHW-LOGOMINI","OSHW-LOGOMINI","OSHW-LOGO-MINI","Open-Source Hardware (OSHW) Logo","","",')
newPart.addTag('rawParts','"LOGO8","REVISION","REVISION","REVISION",""Revision By" Text","","",')
newPart.addTag('rawParts','"LOGO15","OSHW-LOGOMINI","OSHW-LOGOMINI","OSHW-LOGO-MINI","Open-Source Hardware (OSHW) Logo","","",')
newPart.addTag('rawParts','"LOGO16","SFE_LOGO_NAME.1_INCH","SFE_LOGO_NAME.1_INCH","SFE_LOGO_NAME_.1","SparkFun Font Logo","","",')
newPart.addTag('rawParts','"R2","330","330OHM-0603-1/10W-1%","0603","330\xc3\x8e\xc2\xa9 resistor","RES-00818","330",')
newPart.addTag('rawParts','"R3","330","330OHM-0603-1/10W-1%","0603","330\xc3\x8e\xc2\xa9 resistor","RES-00818","330",')
newPart.addTag('rawParts','"R4","150","150OHM-0603-1/10W-1%","0603","150\xc3\x8e\xc2\xa9 resistor","RES-11028","150",')
newPart.addTag('rawParts','"R5","330","330OHM-0603-1/10W-1%","0603","330\xc3\x8e\xc2\xa9 resistor","RES-00818","330",')
newPart.addTag('rawParts','"R6","150","150OHM-0603-1/10W-1%","0603","150\xc3\x8e\xc2\xa9 resistor","RES-11028","150",')
newPart.addTag('rawParts','"R7","330","330OHM-0603-1/10W-1%","0603","330\xc3\x8e\xc2\xa9 resistor","RES-00818","330",')
newPart.addTag('rawParts','"U$1","TAB_GATOR_MINI","TAB_GATOR_MINI","TAB_GATOR_MINI","","","",')
newPart.addTag('rawParts','"U$2","TAB_GATOR_MINI","TAB_GATOR_MINI","TAB_GATOR_MINI","","","",')
newPart.addTag('rawParts','"U$3","TAB_GATOR_MINI","TAB_GATOR_MINI","TAB_GATOR_MINI","","","",')
newPart.addTag('rawParts','"U$6","TAB_GATOR_MINI","TAB_GATOR_MINI","TAB_GATOR_MINI","","","",')
newPart.addTag('rawParts','"U$7","TAB_GATOR_MINI","TAB_GATOR_MINI","TAB_GATOR_MINI","","","",')
newPart.addTag('rawParts','"U$8","TAB_GATOR_MINI","TAB_GATOR_MINI","TAB_GATOR_MINI","","","",')
newPart.addTag('rawParts','"U$10","TAB_GATOR_MINI","TAB_GATOR_MINI","TAB_GATOR_MINI","","","",')
newPart.addTag('rawParts','"U$11","TAB_GATOR_MINI","TAB_GATOR_MINI","TAB_GATOR_MINI","","","",')
newPart.addTag('rawParts','"U$13","TAB_GATOR_MINI","TAB_GATOR_MINI","TAB_GATOR_MINI","","","",')
newPart.addTag('rawParts','"U$16","TAB_GATOR_MINI","TAB_GATOR_MINI","TAB_GATOR_MINI","","","",')
newPart.addTag('rawParts','"U$18","TAB_GATOR_MINI","TAB_GATOR_MINI","TAB_GATOR_MINI","","","",')
newPart.addTag('rawParts','"U$19","TAB_GATOR_MINI","TAB_GATOR_MINI","TAB_GATOR_MINI","","","",')
newPart.addTag('rawParts','"U$20","TAB_GATOR_MINI","TAB_GATOR_MINI","TAB_GATOR_MINI","","","",')
newPart.addTag('rawParts','"U$21","TAB_GATOR_MINI","TAB_GATOR_MINI","TAB_GATOR_MINI","","","",')
newPart.addTag('rawParts','"U$28","TAB_GATOR_MINI","TAB_GATOR_MINI","TAB_GATOR_MINI","","","",')
newPart.addTag('rawParts','"U$30","TAB_GATOR_MINI","TAB_GATOR_MINI","TAB_GATOR_MINI","","","",')
newPart.addTag('rawParts','"U$32","TAB_GATOR_MINI","TAB_GATOR_MINI","TAB_GATOR_MINI","","","",')
newPart.addTag('rawParts','"U$33","TAB_GATOR_MINI","TAB_GATOR_MINI","TAB_GATOR_MINI","","","",')
newPart.addTag('rawParts','"U$34","TAB_GATOR_MINI","TAB_GATOR_MINI","TAB_GATOR_MINI","","","",')
newPart.addTag('rawParts','"U$38","TAB_GATOR_MINI","TAB_GATOR_MINI","TAB_GATOR_MINI","","","",')