import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-1777-STAN-01")

newPart.addTag('rawParts','"C1","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C2","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"FID1","FIDUCIAL""","FIDUCIAL""","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"FID2","FIDUCIAL""","FIDUCIAL""","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"JP1","","HEADER-1X770MIL","1X07_ROUND_70","PIN HEADER","",')
newPart.addTag('rawParts','"Q1","BSS138","MOSFET-NWIDE","SOT23-WIDE","N-Channel Mosfet","",')
newPart.addTag('rawParts','"Q2","BSS138","MOSFET-NWIDE","SOT23-WIDE","N-Channel Mosfet","",')
newPart.addTag('rawParts','"R1","10K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R2","10K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R3","10K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R4","10K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R5","10K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"U$5","MOUNTINGHOLE2.5","MOUNTINGHOLE2.5","MOUNTINGHOLE_2.5_PLATED","Mounting Hole","EXCLUDE",')
newPart.addTag('rawParts','"U$6","MOUNTINGHOLE2.5","MOUNTINGHOLE2.5","MOUNTINGHOLE_2.5_PLATED","Mounting Hole","EXCLUDE",')
newPart.addTag('rawParts','"U1","SI1145","SI114X","SI114X","Si1145/1146/1147 Proximity/UV/Ambient Light Sensor","",')
newPart.addTag('rawParts','"U2","MIC5225-3.3","VREG_SOT23-5","SOT23-5","SOT23-5 Fixed Voltage Regulators","",')