import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-11129-STAN-01")

newPart.addTag('rawParts','"C1","22nF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C2","0.1uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C3","0.39uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C4","0.39uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C5","22pF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C6","22pF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C8","47uF","CAP_POL3528","EIA3528","Capacitor Polarized","",')
newPart.addTag('rawParts','"C9","47uF","CAP_POL3528","EIA3528","Capacitor Polarized","",')
newPart.addTag('rawParts','"C10","0.1uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C11","0.1uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"D1","CM1213","CM1213","SOT23-3","","",')
newPart.addTag('rawParts','"FRAME1","FRAME-LETTER","FRAME-LETTER","CREATIVE_COMMONS","Schematic Frame","",')
newPart.addTag('rawParts','"J3","OUTPUT","M081X08","1X08","Header 8","",')
newPart.addTag('rawParts','"J4","ANT","M02PTH","1X02","Header 2","",')
newPart.addTag('rawParts','"JP1","LOGO-SFENEW","LOGO-SFENEW","SFE-NEW-WEBLOGO","Spark Fun Electronics PCB Logo","",')
newPart.addTag('rawParts','"JP2","LOGO-SFESK","LOGO-SFESK","SFE-LOGO-FLAME","Spark Fun Electronics PCB Logo","",')
newPart.addTag('rawParts','"JP3","","M03PTH","1X03","Header 3","",')
newPart.addTag('rawParts','"JP4","FIDUCIALUFIDUCIAL","FIDUCIALUFIDUCIAL","MICRO-FIDUCIAL","Fiducial Alignment Points","",')
newPart.addTag('rawParts','"JP5","FIDUCIALUFIDUCIAL","FIDUCIALUFIDUCIAL","MICRO-FIDUCIAL","Fiducial Alignment Points","",')
newPart.addTag('rawParts','"L1","56nH","INDUCTOR0603","0603","Inductors","",')
newPart.addTag('rawParts','"L2","Ferrite 2.5k","INDUCTOR0402","C0402","Inductors","",')
newPart.addTag('rawParts','"L3","Ferrite 2.5k","INDUCTOR0402","C0402","Inductors","",')
newPart.addTag('rawParts','"R1","2k","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R2","2k","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R3","2k","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R4","2k","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R5","4.7k","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R6","4.7k","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R7","10k","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R8","10k","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R9","20k","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R10","20k","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R11","47k","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R12","47k","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"SJ2","","SOLDERJUMPER_2WAYS","SJ_3","Solder Jumper","",')
newPart.addTag('rawParts','"U$2","OSHW-LOGOS","OSHW-LOGOS","OSHW-LOGO-S","Open Source Hardware Logo This logo indicates the piece of hardware it is found on incorporates a OSHW license and/or adheres to the definition of open source hardware found here: http://freedomdefined.org/OSHW","",')
newPart.addTag('rawParts','"U1","","SI4707","SI470X","Silicon Labs Si4707 Weather Band and SAME Data Receiver","",')
newPart.addTag('rawParts','"U2","","AUDIO-JACKSMD2","AUDIO-JACK-3.5MM-SMD","3.5mm Audio Jack","",')
newPart.addTag('rawParts','"U3","TPA6111","SPARKFUN_TPA6111SMD","SPARKFUN_SO08","","",')
newPart.addTag('rawParts','"Y1","32.768kHz","CRYSTAL32-SMD","CRYSTAL-32KHZ-SMD","Various standard crystals. Proven footprints. Spark Fun Electronics SKU : COM-00534","",')