import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-11178-STAN-01")

newPart.addTag('oompParts','BAT,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','C1,CAPX-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','C2,CAPX-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','JP1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','LED1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','R1,RESE-UNMATCHED-X-O1003-01')
newPart.addTag('oompParts','S1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U$2,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','Y1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')