import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-1981-STAN-01")

newPart.addTag('rawParts','"C2","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"FID1","FIDUCIAL""","FIDUCIAL""","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"FID2","FIDUCIAL""","FIDUCIAL""","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"GND","SEWTAP0.5IN","SEWTAP0.5IN","SEWINGTAP_0.5","","",')
newPart.addTag('rawParts','"R2","10K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R3","10K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"SCL1","SEWTAP0.5IN","SEWTAP0.5IN","SEWINGTAP_0.5","","",')
newPart.addTag('rawParts','"SCL2","SEWTAP0.5IN","SEWTAP0.5IN","SEWINGTAP_0.5","","",')
newPart.addTag('rawParts','"SDA1","SEWTAP0.5IN","SEWTAP0.5IN","SEWINGTAP_0.5","","",')
newPart.addTag('rawParts','"SDA2","SEWTAP0.5IN","SEWTAP0.5IN","SEWINGTAP_0.5","","",')
newPart.addTag('rawParts','"U1","SI1145","SI114X","SI114X","Si1145/1146/1147 Proximity/UV/Ambient Light Sensor","",')
newPart.addTag('rawParts','"VCC","SEWTAP0.5IN","SEWTAP0.5IN","SEWINGTAP_0.5","","",')