import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-1032-STAN-01")

newPart.addTag('rawParts','"C1","0.1uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C3","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C4","0.1uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C5","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"D1","1N4148","DIODESOD-323F","SOD-323F","Diode","",')
newPart.addTag('rawParts','"IC1","MIC5225-3.3","LP298XS","SOT23-5L","","",')
newPart.addTag('rawParts','"IC2","LGD20H","GYRO_L3GD20H","L3GD20H_LGA16L","L3GD20H - 3 Axis Gyro","",')
newPart.addTag('rawParts','"JP1","","HEADER-1X976MIL","1X09_ROUND_76","PIN HEADER","",')
newPart.addTag('rawParts','"Q1","BSS138","MOSFET-NREFLOW","SOT23","N-Channel Mosfet","",')
newPart.addTag('rawParts','"Q2","BSS138","MOSFET-NREFLOW","SOT23","N-Channel Mosfet","",')
newPart.addTag('rawParts','"R2","10K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R3","10K","RESISTOR_0805MP","_0805MP","Resistors","",')
newPart.addTag('rawParts','"R4","10K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R5","10K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R6","10K","RESISTOR_0805MP","_0805MP","Resistors","",')
newPart.addTag('rawParts','"R7","10K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"U$11","MOUNTINGHOLE2.0","MOUNTINGHOLE2.0","MOUNTINGHOLE_2.0_PLATED","Mounting Hole","EXCLUDE",')
newPart.addTag('rawParts','"U$12","MOUNTINGHOLE2.0","MOUNTINGHOLE2.0","MOUNTINGHOLE_2.0_PLATED","Mounting Hole","EXCLUDE",')
newPart.addTag('rawParts','"U$13","MOUNTINGHOLE2.0","MOUNTINGHOLE2.0","MOUNTINGHOLE_2.0_PLATED","Mounting Hole","EXCLUDE",')
newPart.addTag('rawParts','"U$14","MOUNTINGHOLE2.0","MOUNTINGHOLE2.0","MOUNTINGHOLE_2.0_PLATED","Mounting Hole","EXCLUDE",')
newPart.addTag('rawParts','"U$15","FIDUCIAL","FIDUCIAL","FIDUCIAL_1MM","For use by pick and place machines to calibrate the vision/machine, 1mm","",')
newPart.addTag('rawParts','"U$16","FIDUCIAL","FIDUCIAL","FIDUCIAL_1MM","For use by pick and place machines to calibrate the vision/machine, 1mm","",')