import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-1222-STAN-01")

newPart.addTag('oompParts','3V3,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','B0,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','B1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','B2,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','BOOT,LEDS-0805-G-STAN-01')
newPart.addTag('oompParts','C1,CAPC-0805-X-UF10-V10')
newPart.addTag('oompParts','C8,CAPC-0805-X-UF10-V10')
newPart.addTag('oompParts','CN1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','D2,DIOD-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','D3,DIOD-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','GND,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','IC2,VREG-SO235-X-KMIC5225-V33D')
newPart.addTag('oompParts','IC3,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','PWR,LEDS-0805-G-STAN-01')
newPart.addTag('oompParts','Q1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','R1,RESE-0603-X-UNMATCHED-01')
newPart.addTag('oompParts','R2,RESE-0603-X-UNMATCHED-01')
newPart.addTag('oompParts','R3,RESE-0603-X-UNMATCHED-01')
newPart.addTag('oompParts','R4,RESE-0603-X-UNMATCHED-01')
newPart.addTag('oompParts','R5,RESE-0603-X-UNMATCHED-01')
newPart.addTag('oompParts','TP1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','VBAT,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','X2,UNMATCHED-UNMATCHED-X-UNMATCHED-01')