import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-4775-STAN-01")

newPart.addTag('rawParts','"AD","20609","HEADER-1X6OVALWAVE","1X06_OVALWAVE","PIN HEADER","","","","","","","","",')
newPart.addTag('rawParts','"C1","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C2","0.1uF","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C3","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C4","10\xc3\x82\xc2\xb5F","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C5","0.1uF","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C6","1uF","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C7","10\xc3\x82\xc2\xb5F","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C8","10\xc3\x82\xc2\xb5F","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C10","10\xc3\x82\xc2\xb5F","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C11","10\xc3\x82\xc2\xb5F","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C12","0.1uF","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C13","10\xc3\x82\xc2\xb5F","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C14","1uF","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C15","0.1uF","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C17","10\xc3\x82\xc2\xb5F","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C18","10\xc3\x82\xc2\xb5F","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"CHG1","ORANGE","LED0603_NOOUTLINE","CHIPLED_0603_NOOUTLINE","LED","","","","","","","","",')
newPart.addTag('rawParts','"CONN1","STEMMA_I2C_QT","STEMMA_I2C_QT","JST_SH4","","","","","","","","","",')
newPart.addTag('rawParts','"D1","MBR540","DIODE-SCHOTTKYSOD-123","SOD-123","","","","","","","","","",')
newPart.addTag('rawParts','"D4","MBR540","DIODE-SCHOTTKYSOD-123","SOD-123","","","","","","","","","",')
newPart.addTag('rawParts','"F2","500mA","PTC1206","1206","PTC (Resettable Fuse)","","","","","","","","",')
newPart.addTag('rawParts','"FD1","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","","EXCLUDE","","","","","","",')
newPart.addTag('rawParts','"FD2","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","","EXCLUDE","","","","","","",')
newPart.addTag('rawParts','"FD3","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","","EXCLUDE","","","","","","",')
newPart.addTag('rawParts','"IC2","LC709203F","LC709203F","WDFN8_3X4_0.65","","","","","","","","","",')
newPart.addTag('rawParts','"ICSP","3x2 M","HEADER-2X3","2X03_ROUND_70MIL","PIN HEADER","","","","","","","","",')
newPart.addTag('rawParts','"IOH","20611","HEADER-1X10OVALWAVE","1X10_OVALWAVE","PIN HEADER","","","","","","","","",')
newPart.addTag('rawParts','"IOL","20610","HEADER-1X8OVALWAVE","1X08_OVALWAVE","PIN HEADER","","","","","","","","",')
newPart.addTag('rawParts','"JP2","UART","HEADER-1X2ROUND","1X02_ROUND","PIN HEADER","","","","","","","","",')
newPart.addTag('rawParts','"L","RED","LED0603_NOOUTLINE","CHIPLED_0603_NOOUTLINE","LED","","","","","","","","",')
newPart.addTag('rawParts','"LED1","WS2812B3535","WS2812B3535","LED3535","","","","","","","","","",')
newPart.addTag('rawParts','"ON","GREEN","LED0603_NOOUTLINE","CHIPLED_0603_NOOUTLINE","LED","","","","","","","","",')
newPart.addTag('rawParts','"PC1","47uF/25V","CAP_ELECTROLYTICPANASONIC_D","PANASONIC_D","Electrolytic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"PC2","47uF+/6.3V+","CAP_ELECTROLYTICPANASONIC_D","PANASONIC_D","Electrolytic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"POWER","20610","HEADER-1X8OVALWAVE","1X08_OVALWAVE","PIN HEADER","","","","","","","","",')
newPart.addTag('rawParts','"Q1","DMG3415U-7","MOSFET-P","SOT23-R","P-Channel Mosfet","","","","","","","","",')
newPart.addTag('rawParts','"Q2","DMG3415U-7","MOSFET-P","SOT23-R","P-Channel Mosfet","","","","","","","","",')
newPart.addTag('rawParts','"R1","10K","RESISTOR_4PACK","RESPACK_4X0603","Resistor Packs (4 resistors)","","","","","","","","",')
newPart.addTag('rawParts','"R2","10K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R3","5.1K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R4","2.2K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R6","10K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R8","5.1K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R9","10K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R12","100K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R14","100k","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R15","100K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R16","100K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R17","1Meg","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"SJ1","","SOLDERJUMPER_CLOSED","SOLDERJUMPER_CLOSEDWIRE","Solder Jumper - Closed","","","","","","","","",')
newPart.addTag('rawParts','"SW1","RA_TACT","SWITCH_SPST_TACT_RA","SPST_TACTILE_RA","Switch - SPST","","","","","","","","",')
newPart.addTag('rawParts','"SW3","RA_TACT","SWITCH_SPST_TACT_RA","SPST_TACTILE_RA","Switch - SPST","","","","","","","","",')
newPart.addTag('rawParts','"SW4","SPDT R/A","SWITCH_SPDT","SPDT_SMT_SSSS811101","Switch - SPDT","","","","","","","","",')
newPart.addTag('rawParts','"TP1","","TESTPOINTROUND1.5MMNO","TESTPOINT_ROUND_1.5MM_NO","Test Point","","","","","","","","",')
newPart.addTag('rawParts','"U1","NCP1117ST50T3G","LM1117SOT223-REFLOW","SOT223-R","LM1117 Voltage Regulator","","","","","","","","",')
newPart.addTag('rawParts','"U2","MCP73831T-2ACI/OT","MCP73831/2","SOT23-5","MCP73831/2 LIPO Charger","","","","","","","","",')
newPart.addTag('rawParts','"U3","ESP32-S2-WROVER","ESP32-S2-WROVER","MODULE_ESP32-S2-WROVER","WiFi 802.11b/g/n Transceiver Module 2.4GHz Antenna Not Included Surface Mount Check prices","Warning",""," WiFi 802.11b/g/n Transceiver Module 2.4GHz Antenna Not Included Surface Mount ","https://snapeda.com/shop?store=DigiKey&id=4614060","Espressif Systems","ESP32-S2-WROVER","VFQFN-56 Espressif Systems","None",')
newPart.addTag('rawParts','"U4","AP2112(3.3V)","VREG_SOT23-5","SOT23-5","SOT23-5 Fixed Voltage Regulators","","","","","","","","",')
newPart.addTag('rawParts','"X1","JSTPH","CON_JST_PH_2PIN_BATT","JSTPH2_BATT","JST 2-Pin Right-Angle Connector","","","","","","","","",')
newPart.addTag('rawParts','"X2","4u20317","JTAG-CORTEXBOXPOSTS","2X05_1.27MM_BOX_POSTS","Serial Wire (SW-DP) Connector","","","","","","","","",')
newPart.addTag('rawParts','"X4","USB C","USB_C","USB_C_CUSB31-CFM2AX-01-X","USB Type-C USB 2.0 Connector","","","","","","","","",')
newPart.addTag('rawParts','"X5","2.1mm","DCBARRELPTH","DCJACK_2MM_PTH","DC Barrel Jack","","","","","","","","",')