import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-12052-STAN-01")

newPart.addTag('rawParts','C1,4.7uF,CAP0603-CAP,0603-CAP,Capacitor,,')
newPart.addTag('rawParts','C2,4.7uF,CAP0603-CAP,0603-CAP,Capacitor,,')
newPart.addTag('rawParts','FID1,FIDUCIAL1X2,FIDUCIAL1X2,FIDUCIAL-1X2,Fiducial Alignment Points,,')
newPart.addTag('rawParts','FID2,FIDUCIAL1X2,FIDUCIAL1X2,FIDUCIAL-1X2,Fiducial Alignment Points,,')
newPart.addTag('rawParts','FRAME1,FRAME-LETTER,FRAME-LETTER,CREATIVE_COMMONS,Schematic Frame,,')
newPart.addTag('rawParts','JP1,JST,M02-JST-2MM-SMT,JST-2-SMD,Standard 2-pin 0.1 header. Use with,CONN-08352,')
newPart.addTag('rawParts','JP2,IN,M02PTH,1X02,Standard 2-pin 0.1 header. Use with,,')
newPart.addTag('rawParts','JP3,OUT,M02PTH,1X02,Standard 2-pin 0.1 header. Use with,,')
newPart.addTag('rawParts','JP4,,M06SIP,1X06,Header 6,,')
newPart.addTag('rawParts','LOGO1,OSHW-LOGOS,OSHW-LOGOS,OSHW-LOGO-S,Open Source Hardware Logo This logo indicates the piece of hardware it is found on incorporates a OSHW license and/or adheres to the definition of open source hardware found here: http://freedomdefined.org/OSHW,,')
newPart.addTag('rawParts','LOGO2,LOGO-SFENW2,LOGO-SFENW2,SFE-NEW-WEB,Spark Fun Electronics PCB Logo,,')
newPart.addTag('rawParts','LOGO3,LOGO-SFESK,LOGO-SFESK,SFE-LOGO-FLAME,Spark Fun Electronics PCB Logo,,')
newPart.addTag('rawParts','R1,0.05,RESISTOR1206,1206,Resistor,,')
newPart.addTag('rawParts','R2,DNP,RESISTORAXIAL-0.3,AXIAL-0.3,Resistor,,')
newPart.addTag('rawParts','R3,75K,RESISTOR0603-RES,0603-RES,Resistor,,')
newPart.addTag('rawParts','R4,47K,RESISTOR0603-RES,0603-RES,Resistor,,')
newPart.addTag('rawParts','R5,3.3K,RESISTOR0603-RES,0603-RES,Resistor,,')
newPart.addTag('rawParts','R6,75K,RESISTOR0603-RES,0603-RES,Resistor,,')
newPart.addTag('rawParts','R7,3.3K,RESISTOR0603-RES,0603-RES,Resistor,,')
newPart.addTag('rawParts','R8,47K,RESISTOR0603-RES,0603-RES,Resistor,,')
newPart.addTag('rawParts','R9,3.3K,RESISTOR0603-RES,0603-RES,Resistor,,')
newPart.addTag('rawParts','SJ1,,SOLDERJUMPERNC,SJ_2S,Solder Jumper,,')
newPart.addTag('rawParts','SJ2,,SOLDERJUMPERNO,SJ_2S-NO,Solder Jumper,,')
newPart.addTag('rawParts','SJ3,,SOLDERJUMPERNO,SJ_2S-NO,Solder Jumper,,')
newPart.addTag('rawParts','U1,LTC4150,LTC4150,MSOP10,,,')