import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-12761-STAN-01")

newPart.addTag('rawParts','"C1","0.1uF","0.1UF-25V-5%(0603)","0603-CAP","CAP-08604","CAP-08604","0.1uF",')
newPart.addTag('rawParts','"C2","0.1uF","0.1UF-25V-5%(0603)","0603-CAP","CAP-08604","CAP-08604","0.1uF",')
newPart.addTag('rawParts','"C3","10uF","10UF-6.3V-20%(0603)","0603-CAP","CAP-11015","CAP-11015","10uF",')
newPart.addTag('rawParts','"FRAME1","FRAME-LETTER","FRAME-LETTER","CREATIVE_COMMONS","Schematic Frame","","",')
newPart.addTag('rawParts','"J1","AVR_SPI_PRG_6NS","AVR_SPI_PRG_6NS","2X3-NS","AVR ISP 6 Pin","","",')
newPart.addTag('rawParts','"JP1","SFE_LOGO_NAME_FLAME.1_INCH","SFE_LOGO_NAME_FLAME.1_INCH","SFE_LOGO_NAME_FLAME_.1","SFE Logo, name and flame","","",')
newPart.addTag('rawParts','"JP2","FIDUCIAL1X2","FIDUCIAL1X2","FIDUCIAL-1X2","Fiducial Alignment Points","","",')
newPart.addTag('rawParts','"JP3","FIDUCIAL1X2","FIDUCIAL1X2","FIDUCIAL-1X2","Fiducial Alignment Points","","",')
newPart.addTag('rawParts','"JP4","","M08","1X08","Header 8","","",')
newPart.addTag('rawParts','"JP5","M10"","M10"","1X10","Header 10","","",')
newPart.addTag('rawParts','"JP6","","M06SIP","1X06","Header 6","","",')
newPart.addTag('rawParts','"JP7","","M081X08","1X08","Header 8","","",')
newPart.addTag('rawParts','"LED1","Red","LED0603","LED-0603","LEDs","","",')
newPart.addTag('rawParts','"LOGO1","OSHW-LOGOM","OSHW-LOGOM","OSHW-LOGO-M","Open Source Hardware Logo This logo indicates the piece of hardware it is found on incorporates a OSHW license and/or adheres to the definition of open source hardware found here: http://freedomdefined.org/OSHW","","",')
newPart.addTag('rawParts','"LOGO2","SFE_LOGO_FLAME.6_INCH","SFE_LOGO_FLAME.6_INCH","SFE_LOGO_FLAME_.6","SFE Logo, flame only","","",')
newPart.addTag('rawParts','"R1","1k","RESISTOR0603-RES","0603-RES","Resistor","","",')
newPart.addTag('rawParts','"S1","","TAC_SWITCHSMD","TACTILE_SWITCH_SMD","Momentary Switch","","",')
newPart.addTag('rawParts','"SJ1","SOLDERJUMPERNC","SOLDERJUMPERNC","SJ_2S","Solder Jumper","","",')
newPart.addTag('rawParts','"SJ2","SOLDERJUMPERNC","SOLDERJUMPERNC","SJ_2S","Solder Jumper","","",')
newPart.addTag('rawParts','"U$1","REVISION","REVISION","REVISION","","","",')
newPart.addTag('rawParts','"U1","USD-SOCKETNEW","USD-SOCKETNEW","MICRO-SD-SOCKET-PP","microSD Socket","","",')
newPart.addTag('rawParts','"U2","ARDUINO_R3_SHIELDNOLABELS","ARDUINO_R3_SHIELDNOLABELS","UNO_R3_SHIELD_NOLABELS","Shield form compatible with the Arduino Uno R3.","","",')
newPart.addTag('rawParts','"U3","HEX_CONVERTER","HEX_CONVERTER","SO016","","","",')