import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-14459-STAN-01")

newPart.addTag('rawParts','"C1","1.0uF","1.0UF-0603-16V-10%","0603","1\xc3\x82\xc2\xb5F ceramic capacitors","CAP-00868","1.0uF",')
newPart.addTag('rawParts','"C3","1.0uF","1.0UF-0603-16V-10%","0603","1\xc3\x82\xc2\xb5F ceramic capacitors","CAP-00868","1.0uF",')
newPart.addTag('rawParts','"FD1","FIDUCIAL1X2","FIDUCIAL1X2","FIDUCIAL-1X2","Fiducial Alignment Points","","",')
newPart.addTag('rawParts','"FD2","FIDUCIAL1X2","FIDUCIAL1X2","FIDUCIAL-1X2","Fiducial Alignment Points","","",')
newPart.addTag('rawParts','"FD3","FIDUCIAL1X2","FIDUCIAL1X2","FIDUCIAL-1X2","Fiducial Alignment Points","","",')
newPart.addTag('rawParts','"FD4","FIDUCIAL1X2","FIDUCIAL1X2","FIDUCIAL-1X2","Fiducial Alignment Points","","",')
newPart.addTag('rawParts','"FRAME1","FRAME-LETTER","FRAME-LETTER","CREATIVE_COMMONS","Schematic Frame","","",')
newPart.addTag('rawParts','"J1","Qwiic Right Angle","I2C_STANDARDQWIIC","1X04_1MM_RA","SparkFun I2C Standard Pinout Header","CONN-13694","Qwiic Right Angle",')
newPart.addTag('rawParts','"J2","","CONN_021X02_NO_SILK","1X02_NO_SILK","Multi connection point. Often used as Generic Header-pin footprint for 0.1 inch spaced/style header connections","","",')
newPart.addTag('rawParts','"J3","","CONN_041X04_NO_SILK","1X04_NO_SILK","Multi connection point. Often used as Generic Header-pin footprint for 0.1 inch spaced/style header connections","CONN-09696","",')
newPart.addTag('rawParts','"J4","","CONN_06NO_SILK_FEMALE_PTH","1X06_NO_SILK","Multi connection point. Often used as Generic Header-pin footprint for 0.1 inch spaced/style header connections","CONN-08437","",')
newPart.addTag('rawParts','"J5","","CONN_041X04_NO_SILK","1X04_NO_SILK","Multi connection point. Often used as Generic Header-pin footprint for 0.1 inch spaced/style header connections","CONN-09696","",')
newPart.addTag('rawParts','"J6","Qwiic Right Angle","I2C_STANDARDQWIIC","1X04_1MM_RA","SparkFun I2C Standard Pinout Header","CONN-13694","Qwiic Right Angle",')
newPart.addTag('rawParts','"J7","Qwiic Right Angle","I2C_STANDARDQWIIC","1X04_1MM_RA","SparkFun I2C Standard Pinout Header","CONN-13694","Qwiic Right Angle",')
newPart.addTag('rawParts','"J8","Qwiic Right Angle","I2C_STANDARDQWIIC","1X04_1MM_RA","SparkFun I2C Standard Pinout Header","CONN-13694","Qwiic Right Angle",')
newPart.addTag('rawParts','"J12","","CONN_021X02_NO_SILK","1X02_NO_SILK","Multi connection point. Often used as Generic Header-pin footprint for 0.1 inch spaced/style header connections","","",')
newPart.addTag('rawParts','"LOGO1","OSHW-LOGOMINI","OSHW-LOGOMINI","OSHW-LOGO-MINI","Open Source Hardware Logo","","",')
newPart.addTag('rawParts','"LOGO2","REVISION","REVISION","REVISION",""Revision By" Text","","",')
newPart.addTag('rawParts','"U$1","SFE_LOGO_FLAME.1_INCH","SFE_LOGO_FLAME.1_INCH","SFE_LOGO_FLAME_.1","SparkFun Flame Logo","","",')
newPart.addTag('rawParts','"U$2","SFE_LOGO_NAME.1_INCH","SFE_LOGO_NAME.1_INCH","SFE_LOGO_NAME_.1","SparkFun Font Logo","","",')
newPart.addTag('rawParts','"U2","3.3V/600mA","V_REG_AP2112K-3.3V","SOT23-5","AP2112 - 600mA CMOS LDO Regulator w/ Enable","VREG-12457","3.3V",')
newPart.addTag('rawParts','"U3","","RASPBERRY_PI_40BTM-NOHOLES","RASPBERRY_PI_SHIELD_BOTTOM_ENTRY_NOHOLES","","CONN-13790","",')