import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-11820-STAN-01")

newPart.addTag('oompParts','C1,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')
newPart.addTag('oompParts','FRAME1,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')
newPart.addTag('oompParts','JP1,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')
newPart.addTag('oompParts','JP2,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')
newPart.addTag('oompParts','JP4,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')
newPart.addTag('oompParts','JP15,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')
newPart.addTag('oompParts','LOGO1,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')
newPart.addTag('oompParts','LOGO2,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')
newPart.addTag('oompParts','U1,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')