import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-20170-STAN-01")

newPart.addTag('rawParts','C1,0.1uF,0.1UF-0402T-6.3V-10%-X7R,0402-TIGHT,0.1\xc3\x82\xc2\xb5F ceramic capacitors,,CAP-14993,,0.1uF,')
newPart.addTag('rawParts','D1,RED,LED-RED_0402,LED-0402,Red SMD LED,,DIO-16757,,RED,')
newPart.addTag('rawParts','FD1,FIDUCIALUFIDUCIAL,FIDUCIALUFIDUCIAL,FIDUCIAL-MICRO,Fiducial Alignment Points,,,,,')
newPart.addTag('rawParts','FD2,FIDUCIALUFIDUCIAL,FIDUCIALUFIDUCIAL,FIDUCIAL-MICRO,Fiducial Alignment Points,,,,,')
newPart.addTag('rawParts','FD3,FIDUCIALUFIDUCIAL,FIDUCIALUFIDUCIAL,FIDUCIAL-MICRO,Fiducial Alignment Points,,,,,')
newPart.addTag('rawParts','FD4,FIDUCIALUFIDUCIAL,FIDUCIALUFIDUCIAL,FIDUCIAL-MICRO,Fiducial Alignment Points,,,,,')
newPart.addTag('rawParts','FRAME1,FRAME-LETTER,FRAME-LETTER,CREATIVE_COMMONS,Schematic Frame - Letter,,,,,')
newPart.addTag('rawParts','H1,STAND-OFF,STAND-OFF,STAND-OFF,Stand Off,,,,,')
newPart.addTag('rawParts','J1,QWIIC_RIGHT_ANGLE,QWIIC_CONNECTORJS-1MM,JST04_1MM_RA,SparkFun I2C Standard Qwiic Connector,,CONN-13694,,QWIIC_RIGHT_ANGLE,')
newPart.addTag('rawParts','J2,,CONN_01_1MM,1X01_1MM_NO_SILK,Single connection point. Often used as Generic Header-pin footprint for 0.1 inch spaced/style header connections,,,,,')
newPart.addTag('rawParts','J3,,CONN_01_1MM,1X01_1MM_NO_SILK,Single connection point. Often used as Generic Header-pin footprint for 0.1 inch spaced/style header connections,,,,,')
newPart.addTag('rawParts','JP1,ADR,JUMPER-SMT_3_1-NC_TRACE_SILK,SMT-JUMPER_3_1-NC_TRACE_SILK,Normally closed trace jumper (1 of 2 connections),,,,,')
newPart.addTag('rawParts','JP2,I2C,JUMPER-SMT_3_2-NC_TRACE_SILK,SMT-JUMPER_3_2-NC_TRACE_SILK,Normally closed trace jumper (2 of 2 connections),,,,,')
newPart.addTag('rawParts','JP3,LED,JUMPER-SMT_2_NC_TRACE_SILK,SMT-JUMPER_2_NC_TRACE_SILK,Normally closed trace jumper,,,,,')
newPart.addTag('rawParts','LOGO1,OSHW-LOGOMINI,OSHW-LOGOMINI,OSHW-LOGO-MINI,Open-Source Hardware (OSHW) Logo,,,,,')
newPart.addTag('rawParts','LOGO2,SFE_LOGO_FLAME.1_INCH,SFE_LOGO_FLAME.1_INCH,SFE_LOGO_FLAME_.1,SparkFun Flame Logo,,,,,')
newPart.addTag('rawParts','LOGO3,QWIIC_LOGO_3MM,QWIIC_LOGO_3MM,QWIIC_3MM,Qwiic Logos for placement on schematic and PCB. The 5.5mm silk logo is best for placing next to Qwiic connector.,,,,,')
newPart.addTag('rawParts','LOGO4,SFE_LOGO_NAMEBLANK,SFE_LOGO_NAMEBLANK,BLANK,SparkFun Font Logo,,,,,')
newPart.addTag('rawParts','R1,2.2k,2.2KOHM-0402T-1/16W-1%,0402-TIGHT,2.2k\xc3\x8e\xc2\xa9 resistor,,RES-14341,,2.2k,')
newPart.addTag('rawParts','R2,2.2k,2.2KOHM-0402T-1/16W-1%,0402-TIGHT,2.2k\xc3\x8e\xc2\xa9 resistor,,RES-14341,,2.2k,')
newPart.addTag('rawParts','R3,10K,10KOHM-0402-1/10W-0.1%,0402-TIGHT,10k\xc3\x8e\xc2\xa9 resistor,,RES-16147,,10K,')
newPart.addTag('rawParts','R4,10K,10KOHM-0402-1/10W-0.1%,0402-TIGHT,10k\xc3\x8e\xc2\xa9 resistor,,RES-16147,,10K,')
newPart.addTag('rawParts','R5,1k,1KOHM-0402T-1/16W-1%,0402-TIGHT,1k\xc3\x8e\xc2\xa9 resistor,,RES-14342,,1k,')
newPart.addTag('rawParts','TP1,TEST-POINT3,TEST-POINT3,PAD.03X.03,SparkFun Test Points,,,,,')
newPart.addTag('rawParts','TP2,TEST-POINT3,TEST-POINT3,PAD.03X.03,SparkFun Test Points,,,,,')
newPart.addTag('rawParts','TP3,TEST-POINT3,TEST-POINT3,PAD.03X.03,SparkFun Test Points,,,,,')
newPart.addTag('rawParts','TP4,TEST-POINT3,TEST-POINT3,PAD.03X.03,SparkFun Test Points,,,,,')
newPart.addTag('rawParts','U1,BMP581,BMP581,BMP581,Bosch BMP581 Pressure Sensor,,IC-16798,,,')