import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-11569-STAN-01")

newPart.addTag('rawParts','"FRAME1","FRAME-LETTER","FRAME-LETTER","CREATIVE_COMMONS","Schematic Frame","",')
newPart.addTag('rawParts','"JP1","","M04PTH","1X04","Header 4","",')
newPart.addTag('rawParts','"JP2","","M081X08","1X08","Header 8","",')
newPart.addTag('rawParts','"JP3","DB15","DB15","DB15","DB15 / VGA right angle through-hole female connector.","",')
newPart.addTag('rawParts','"JP4","FIDUCIALUFIDUCIAL","FIDUCIALUFIDUCIAL","MICRO-FIDUCIAL","Fiducial Alignment Points","",')
newPart.addTag('rawParts','"JP5","FIDUCIALUFIDUCIAL","FIDUCIALUFIDUCIAL","MICRO-FIDUCIAL","Fiducial Alignment Points","",')
newPart.addTag('rawParts','"JP6","LOGO-SFENEW","LOGO-SFENEW","SFE-NEW-WEBLOGO","Spark Fun Electronics PCB Logo","",')
newPart.addTag('rawParts','"JP7","LOGO-SFESK","LOGO-SFESK","SFE-LOGO-FLAME","Spark Fun Electronics PCB Logo","",')
newPart.addTag('rawParts','"R1","82.5","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R2","82.5","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R3","270","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R4","270","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R5","270","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R6","270","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R7","270","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R8","270","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"U$1","OSHW-LOGOS","OSHW-LOGOS","OSHW-LOGO-S","Open Source Hardware Logo This logo indicates the piece of hardware it is found on incorporates a OSHW license and/or adheres to the definition of open source hardware found here: http://freedomdefined.org/OSHW","",')