import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-9101-STAN-01")

newPart.addTag('rawParts','GND,SEWTAP9,SEWTAP9,PETAL-LONG-1-2SIDE,,,')
newPart.addTag('rawParts','JP1,,M01SMDNS,1X01NS,Header 1,,')
newPart.addTag('rawParts','JP2,,M01SMDNS,1X01NS,Header 1,,')
newPart.addTag('rawParts','JP3,,M01SMDNS,1X01NS,Header 1,,')
newPart.addTag('rawParts','JP4,,M01SMDNS,1X01NS,Header 1,,')
newPart.addTag('rawParts','JP5,,M01SMDNS,1X01NS,Header 1,,')
newPart.addTag('rawParts','JP6,,M01SMDNS,1X01NS,Header 1,,')
newPart.addTag('rawParts','JP7,,M01SMDNS,1X01NS,Header 1,,')
newPart.addTag('rawParts','JP8,,M01SMDNS,1X01NS,Header 1,,')
newPart.addTag('rawParts','JP9,,M01SMDNS,1X01NS,Header 1,,')
newPart.addTag('rawParts','JP10,,M01SMDNS,1X01NS,Header 1,,')
newPart.addTag('rawParts','JP11,,M01SMDNS,1X01NS,Header 1,,')
newPart.addTag('rawParts','JP12,,M01SMDNS,1X01NS,Header 1,,')
newPart.addTag('rawParts','JP13,,M01SMDNS,1X01NS,Header 1,,')
newPart.addTag('rawParts','JP14,,M01SMDNS,1X01NS,Header 1,,')
newPart.addTag('rawParts','JP15,,M01SMDNS,1X01NS,Header 1,,')
newPart.addTag('rawParts','JP16,,M01SMDNS,1X01NS,Header 1,,')
newPart.addTag('rawParts','JP17,,M01SMDNS,1X01NS,Header 1,,')
newPart.addTag('rawParts','JP18,,M01SMDNS,1X01NS,Header 1,,')
newPart.addTag('rawParts','JP19,,M01SMDNS,1X01NS,Header 1,,')
newPart.addTag('rawParts','JP20,,M01SMDNS,1X01NS,Header 1,,')
newPart.addTag('rawParts','JP21,,M01SMDNS,1X01NS,Header 1,,')
newPart.addTag('rawParts','JP22,,M01SMDNS,1X01NS,Header 1,,')
newPart.addTag('rawParts','U$2,LOGO-LPL,LOGO-LPL,LOGO-L,,,')
newPart.addTag('rawParts','U$4,SEWTAP9,SEWTAP9,PETAL-LONG-1-2SIDE,,,')
newPart.addTag('rawParts','U$30,SEWTAP9,SEWTAP9,PETAL-LONG-1-2SIDE,,,')
newPart.addTag('rawParts','U$31,SEWTAP9,SEWTAP9,PETAL-LONG-1-2SIDE,,,')
newPart.addTag('rawParts','U$32,SEWTAP9,SEWTAP9,PETAL-LONG-1-2SIDE,,,')
newPart.addTag('rawParts','U$33,SEWTAP9,SEWTAP9,PETAL-LONG-1-2SIDE,,,')
newPart.addTag('rawParts','U$34,SEWTAP9,SEWTAP9,PETAL-LONG-1-2SIDE,,,')
newPart.addTag('rawParts','U$35,SEWTAP9,SEWTAP9,PETAL-LONG-1-2SIDE,,,')
newPart.addTag('rawParts','U$36,SEWTAP9,SEWTAP9,PETAL-LONG-1-2SIDE,,,')
newPart.addTag('rawParts','U$37,SEWTAP9,SEWTAP9,PETAL-LONG-1-2SIDE,,,')
newPart.addTag('rawParts','U$38,SEWTAP9,SEWTAP9,PETAL-LONG-1-2SIDE,,,')
newPart.addTag('rawParts','U$39,SEWTAP9,SEWTAP9,PETAL-LONG-1-2SIDE,,,')
newPart.addTag('rawParts','U$40,SEWTAP9,SEWTAP9,PETAL-LONG-1-2SIDE,,,')
newPart.addTag('rawParts','U$41,SEWTAP9,SEWTAP9,PETAL-LONG-1-2SIDE,,,')
newPart.addTag('rawParts','U$42,SEWTAP9,SEWTAP9,PETAL-LONG-1-2SIDE,,,')
newPart.addTag('rawParts','U$43,SEWTAP9,SEWTAP9,PETAL-LONG-1-2SIDE,,,')
newPart.addTag('rawParts','U$44,SEWTAP9,SEWTAP9,PETAL-LONG-1-2SIDE,,,')
newPart.addTag('rawParts','U$45,SEWTAP9,SEWTAP9,PETAL-LONG-1-2SIDE,,,')
newPart.addTag('rawParts','U$46,SEWTAP9,SEWTAP9,PETAL-LONG-1-2SIDE,,,')
newPart.addTag('rawParts','U$47,SEWTAP9,SEWTAP9,PETAL-LONG-1-2SIDE,,,')
newPart.addTag('rawParts','U$48,SEWTAP9,SEWTAP9,PETAL-LONG-1-2SIDE,,,')
newPart.addTag('rawParts','U$51,SEWTAP9,SEWTAP9,PETAL-LONG-1-2SIDE,,,')