import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-4701-STAN-01")

newPart.addTag('rawParts','ANT1,NFC_ANTENNA_25X15,NFC_ANTENNA_25X15,NFCANT_25X15,,,')
newPart.addTag('rawParts','C1,0.1uF,CAP_CERAMIC0603_NO,0603-NO,Ceramic Capacitors,,')
newPart.addTag('rawParts','C3,10uF,CAP_CERAMIC0805-NOOUTLINE,0805-NO,Ceramic Capacitors,,')
newPart.addTag('rawParts','CONN3,STEMMA_I2C_QT,STEMMA_I2C_QT,JST_SH4,,,')
newPart.addTag('rawParts','CONN4,STEMMA_I2C_QT,STEMMA_I2C_QT,JST_SH4,,,')
newPart.addTag('rawParts','D1,GREEN,LED0603_NOOUTLINE,CHIPLED_0603_NOOUTLINE,LED,,')
newPart.addTag('rawParts','FID3,FIDUCIAL_1MM,FIDUCIAL_1MM,FIDUCIAL_1MM,Fiducial Alignment Points,EXCLUDE,')
newPart.addTag('rawParts','FID4,FIDUCIAL_1MM,FIDUCIAL_1MM,FIDUCIAL_1MM,Fiducial Alignment Points,EXCLUDE,')
newPart.addTag('rawParts','JP1,,HEADER-1X670MIL,1X06_ROUND_70,PIN HEADER,,')
newPart.addTag('rawParts','R3,10K,RESISTOR_4PACK,RESPACK_4X0603,Resistor Packs (4 resistors),,')
newPart.addTag('rawParts','RF1,ST25DVXX_TSSOP,ST25DVXX_TSSOP,TSSOP8-4.4MM,,,')
newPart.addTag('rawParts','U$19,MOUNTINGHOLE2.5,MOUNTINGHOLE2.5,MOUNTINGHOLE_2.5_PLATED,Mounting Hole,EXCLUDE,')
newPart.addTag('rawParts','U$21,MOUNTINGHOLE2.5,MOUNTINGHOLE2.5,MOUNTINGHOLE_2.5_PLATED,Mounting Hole,EXCLUDE,')