import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-196-STAN-01")

newPart.addTag('oompParts','CN1,TERS-35D-L-UNMATCHED-01')
newPart.addTag('oompParts','J1,TERS-35D-L-PI02-01')
newPart.addTag('oompParts','JP1,TERS-35D-L-UNMATCHED-01')
newPart.addTag('oompParts','JP2,HEAD-I01-X-PI06-01')
newPart.addTag('oompParts','JP3,HEAD-I01-X-PI08-01')
newPart.addTag('oompParts','JP4,HEAD-I01-X-PI08-01')
newPart.addTag('oompParts','JP5,TERS-35D-L-UNMATCHED-01')
newPart.addTag('oompParts','JP6,TERS-35D-L-UNMATCHED-01')
newPart.addTag('oompParts','JP7,TERS-35D-L-UNMATCHED-01')
newPart.addTag('oompParts','JP8,HEAD-I01-X-PI06-01')
newPart.addTag('oompParts','JP9,HEAD-I01-X-PI01-01')
newPart.addTag('oompParts','LED,LEDS-UNMATCHED-G-STAN-01')
newPart.addTag('oompParts','POWER,LEDS-UNMATCHED-G-STAN-01')
newPart.addTag('oompParts','R1,RESE-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','R2,RESE-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','RESET,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U$1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','W,HEAD-I01-X-PI01-01')
newPart.addTag('oompParts','X,HEAD-I01-X-PI01-01')
newPart.addTag('oompParts','Y,HEAD-I01-X-PI01-01')
newPart.addTag('oompParts','Z,HEAD-I01-X-PI01-01')