import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-196-STAN-01")

newPart.addTag('rawParts','"CN1","1X4-3.5MM","1X4-3.5MM","1X04-3.5MM","4-pin connector","",')
newPart.addTag('rawParts','"J1","1X2-3.5MM","1X2-3.5MM","1X2-3.5MM","3.5mm Terminal block","",')
newPart.addTag('rawParts','"JP1","","PINHD-1X6-3.5MM","1X06-3.5MM","PIN HEADER","",')
newPart.addTag('rawParts','"JP2","","PINHD-1X6CB","1X06-CLEANBIG","PIN HEADER","",')
newPart.addTag('rawParts','"JP3","","PINHD-1X8CLEANBIG","1X08-CLEANBIG","PIN HEADER","",')
newPart.addTag('rawParts','"JP4","","PINHD-1X8CLEANBIG","1X08-CLEANBIG","PIN HEADER","",')
newPart.addTag('rawParts','"JP5","","PINHD-1X8-3.5MM","1X08-3.5MM","PIN HEADER","",')
newPart.addTag('rawParts','"JP6","","PINHD-1X8-3.5MM","1X08-3.5MM","PIN HEADER","",')
newPart.addTag('rawParts','"JP7","","PINHD-1X8-3.5MM","1X08-3.5MM","PIN HEADER","",')
newPart.addTag('rawParts','"JP8","","PINHD-1X6CB","1X06-CLEANBIG","PIN HEADER","",')
newPart.addTag('rawParts','"JP9","","PINHD-1X1","1X01","Pin header 1x1 for 0.1" spacing","",')
newPart.addTag('rawParts','"LED","","LED3MM","LED3MM","LED","",')
newPart.addTag('rawParts','"POWER","","LED3MM","LED3MM","LED","",')
newPart.addTag('rawParts','"R1","","R-US_0207/10","0207/10","RESISTOR, American symbol","",')
newPart.addTag('rawParts','"R2","","R-US_0207/10","0207/10","RESISTOR, American symbol","",')
newPart.addTag('rawParts','"RESET","","10-XX","B3F-10XX","OMRON SWITCH","",')
newPart.addTag('rawParts','"U$1","ARDUINO-BPLACE","ARDUINO-BPLACE","ARDUINO-BPLACE","Arduino Diecimila/Duemilanove","",')
newPart.addTag('rawParts','"W","","PINHD-1X1","1X01","Pin header 1x1 for 0.1" spacing","",')
newPart.addTag('rawParts','"X","","PINHD-1X1","1X01","Pin header 1x1 for 0.1" spacing","",')
newPart.addTag('rawParts','"Y","","PINHD-1X1","1X01","Pin header 1x1 for 0.1" spacing","",')
newPart.addTag('rawParts','"Z","","PINHD-1X1","1X01","Pin header 1x1 for 0.1" spacing","",')