import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-11201-STAN-01")

newPart.addTag('rawParts','"1","SEWTAP-NOHOLE2","SEWTAP-NOHOLE2","PETAL-NOHOLE-2SIDE","","",')
newPart.addTag('rawParts','"2","SEWTAP-NOHOLE2","SEWTAP-NOHOLE2","PETAL-NOHOLE-2SIDE","","",')
newPart.addTag('rawParts','"3","SEWTAP-NOHOLE2","SEWTAP-NOHOLE2","PETAL-NOHOLE-2SIDE","","",')
newPart.addTag('rawParts','"4","SEWTAP-NOHOLE2","SEWTAP-NOHOLE2","PETAL-NOHOLE-2SIDE","","",')
newPart.addTag('rawParts','"A2/16","SEWTAP9","SEWTAP9","PETAL-LONG-1-2SIDE","","",')
newPart.addTag('rawParts','"A3/17","SEWTAP9","SEWTAP9","PETAL-LONG-1-2SIDE","","",')
newPart.addTag('rawParts','"A4/18","SEWTAP9","SEWTAP9","PETAL-LONG-1-2SIDE","","",')
newPart.addTag('rawParts','"A5/19","SEWTAP9","SEWTAP9","PETAL-LONG-1-2SIDE","","",')
newPart.addTag('rawParts','"B1","Buzzer","BUZZERSMD2","BUZZER-CCV","Buzzer 12mm","",')
newPart.addTag('rawParts','"C1","0.1uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C2","47uF","CAP_POL3528","EIA3528","Capacitor Polarized","",')
newPart.addTag('rawParts','"C3","1.0uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C4","0.1uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C9","4.7uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C10","4.7uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"D1","Status","LED0603","LED-0603","LEDs","",')
newPart.addTag('rawParts','"D4","Yellow","LED0603","LED-0603","LEDs","",')
newPart.addTag('rawParts','"JP1","LiPo","M02-JST-2MM-SMT","JST-2-SMD","Header 2","",')
newPart.addTag('rawParts','"JP2","","ARDUINO_SERIAL_PROGRAMSMD","1X06-SMD","","",')
newPart.addTag('rawParts','"JP3","FIDUCIAL1X2","FIDUCIAL1X2","FIDUCIAL-1X2","Fiducial Alignment Points","",')
newPart.addTag('rawParts','"JP4","FIDUCIAL1X2","FIDUCIAL1X2","FIDUCIAL-1X2","Fiducial Alignment Points","",')
newPart.addTag('rawParts','"LED","White","LED1206","LED-1206","LEDs","",')
newPart.addTag('rawParts','"LED+","SEWTAP6","SEWTAP6","PETAL-SMALL-2SIDE","","",')
newPart.addTag('rawParts','"LED+1","SEWTAP6","SEWTAP6","PETAL-SMALL-2SIDE","","",')
newPart.addTag('rawParts','"LED+2","SEWTAP6","SEWTAP6","PETAL-SMALL-2SIDE","","",')
newPart.addTag('rawParts','"LED+3","SEWTAP6","SEWTAP6","PETAL-SMALL-2SIDE","","",')
newPart.addTag('rawParts','"LED-","SEWTAP6","SEWTAP6","PETAL-SMALL-2SIDE","","",')
newPart.addTag('rawParts','"LED-1","SEWTAP6","SEWTAP6","PETAL-SMALL-2SIDE","","",')
newPart.addTag('rawParts','"LED-2","SEWTAP6","SEWTAP6","PETAL-SMALL-2SIDE","","",')
newPart.addTag('rawParts','"LED-3","SEWTAP6","SEWTAP6","PETAL-SMALL-2SIDE","","",')
newPart.addTag('rawParts','"LED1","White","LED1206","LED-1206","LEDs","",')
newPart.addTag('rawParts','"LED2","White","LED1206","LED-1206","LEDs","",')
newPart.addTag('rawParts','"LED3","White","LED1206","LED-1206","LEDs","",')
newPart.addTag('rawParts','"LOGO","LOGO-LPLPA","LOGO-LPLPA","LOGO-LPA","","",')
newPart.addTag('rawParts','"PP-GND","","TEST-POINT3X5","PAD.03X.05","","",')
newPart.addTag('rawParts','"PP-MISO","","TEST-POINT3X5","PAD.03X.05","","",')
newPart.addTag('rawParts','"PP-RST","","TEST-POINT3X5","PAD.03X.05","","",')
newPart.addTag('rawParts','"PP-SCK","","TEST-POINT3X5","PAD.03X.05","","",')
newPart.addTag('rawParts','"R1","330","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R2","10K","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R7","100","RESISTOR0603-RES","0603-RES","Resistor","",')
newPart.addTag('rawParts','"R8","100","RESISTOR0603-RES","0603-RES","Resistor","",')
newPart.addTag('rawParts','"R9","100","RESISTOR0603-RES","0603-RES","Resistor","",')
newPart.addTag('rawParts','"R10","100","RESISTOR0603-RES","0603-RES","Resistor","",')
newPart.addTag('rawParts','"R12","330","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R13","10k","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"S1","On/Off","AYZ0202","AYZ0202","SPDT Slide Switch","",')
newPart.addTag('rawParts','"S4","Reset","SWITCH-MOMENTARY-2SMD","TACTILE_SWITCH_SMD","","",')
newPart.addTag('rawParts','"TP-DTR","","TEST-POINT3X5","PAD.03X.05","","",')
newPart.addTag('rawParts','"TP-RX","","TEST-POINT3X5","PAD.03X.05","","",')
newPart.addTag('rawParts','"TP-TX","","TEST-POINT3X5","PAD.03X.05","","",')
newPart.addTag('rawParts','"TP1","","TEST-POINT3X5","PAD.03X.05","","",')
newPart.addTag('rawParts','"TP2","","TEST-POINT3X5","PAD.03X.05","","",')
newPart.addTag('rawParts','"U$1","SEWTAP9","SEWTAP9","PETAL-LONG-1-2SIDE","","",')
newPart.addTag('rawParts','"U$2","OSHW-LOGOS","OSHW-LOGOS","OSHW-LOGO-S","Open Source Hardware Logo This logo indicates the piece of hardware it is found on incorporates a OSHW license and/or adheres to the definition of open source hardware found here: http://freedomdefined.org/OSHW","",')
newPart.addTag('rawParts','"U$4","SEWTAP9","SEWTAP9","PETAL-LONG-1-2SIDE","","",')
newPart.addTag('rawParts','"U$32-","SEWTAP6","SEWTAP4","PETAL-SMALL","","",')
newPart.addTag('rawParts','"U$33+","SEWTAP6","SEWTAP4","PETAL-SMALL","","",')
newPart.addTag('rawParts','"U$37","SEWTAP9","SEWTAP9","PETAL-LONG-1-2SIDE","","",')
newPart.addTag('rawParts','"U$39","SEWTAP9","SEWTAP9","PETAL-LONG-1-2SIDE","","",')
newPart.addTag('rawParts','"U$41","SEWTAP9","SEWTAP9","PETAL-LONG-1-2SIDE","","",')
newPart.addTag('rawParts','"U$43","SEWTAP9","SEWTAP9","PETAL-LONG-1-2SIDE","","",')
newPart.addTag('rawParts','"U$45","SEWTAP9","SEWTAP9","PETAL-LONG-1-2SIDE","","",')
newPart.addTag('rawParts','"U1","ATMEGA328","ATMEGA168","TQFP32-08","","",')
newPart.addTag('rawParts','"U4","MCP73831","MCP73831","SOT23-5","Microchips MCP73831","",')
newPart.addTag('rawParts','"Y1","8MHz","RESONATORSMD","RESONATOR-SMD","Resonator","",')