import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-10941-STAN-01")

newPart.addTag('rawParts','BAT1,,BATTERY110-TABS,LIPO-110-TABS,Battery Holders,,')
newPart.addTag('rawParts','C1,0.1uF,CAP0402-CAP,0402-CAP,Capacitor,,')
newPart.addTag('rawParts','C2,47uF,CAP_POL3528,EIA3528,Capacitor Polarized,,')
newPart.addTag('rawParts','C3,1.0uF,CAP0402-CAP,0402-CAP,Capacitor,,')
newPart.addTag('rawParts','C4,0.1uF,CAP0402-CAP,0402-CAP,Capacitor,,')
newPart.addTag('rawParts','C9,4.7uF,CAP0402-CAP,0402-CAP,Capacitor,,')
newPart.addTag('rawParts','C10,4.7uF,CAP0402-CAP,0402-CAP,Capacitor,,')
newPart.addTag('rawParts','D2,Status,LED0603,LED-0603,LEDs,,')
newPart.addTag('rawParts','D4,Yellow,LED0603,LED-0603,LEDs,,')
newPart.addTag('rawParts','JP1,FIDUCIALUFIDUCIAL,FIDUCIALUFIDUCIAL,MICRO-FIDUCIAL,Fiducial Alignment Points,,')
newPart.addTag('rawParts','JP2,,ARDUINO_SERIAL_PROGRAMSMD,1X06-SMD,,,')
newPart.addTag('rawParts','JP3,M01SNAP-FEMALE_LARGE,M01SNAP-FEMALE,SNAP-FEMALE,Header 1,,')
newPart.addTag('rawParts','JP4,M01SNAP-FEMALE_LARGE,M01SNAP-FEMALE,SNAP-FEMALE,Header 1,,')
newPart.addTag('rawParts','JP5,M01SNAP-FEMALE_LARGE,M01SNAP-FEMALE,SNAP-FEMALE,Header 1,,')
newPart.addTag('rawParts','JP6,M01SNAP-FEMALE_LARGE,M01SNAP-FEMALE,SNAP-FEMALE,Header 1,,')
newPart.addTag('rawParts','JP7,M01SNAP-FEMALE_LARGE,M01SNAP-FEMALE,SNAP-FEMALE,Header 1,,')
newPart.addTag('rawParts','JP8,M01SNAP-FEMALE_LARGE,M01SNAP-FEMALE,SNAP-FEMALE,Header 1,,')
newPart.addTag('rawParts','JP9,M01SNAP-FEMALE_LARGE,M01SNAP-FEMALE,SNAP-FEMALE,Header 1,,')
newPart.addTag('rawParts','JP10,M01SNAP-FEMALE_LARGE,M01SNAP-FEMALE,SNAP-FEMALE,Header 1,,')
newPart.addTag('rawParts','JP11,M01SNAP-FEMALE_LARGE,M01SNAP-FEMALE,SNAP-FEMALE,Header 1,,')
newPart.addTag('rawParts','JP12,M01SNAP-FEMALE_LARGE,M01SNAP-FEMALE,SNAP-FEMALE,Header 1,,')
newPart.addTag('rawParts','JP13,M01SNAP-FEMALE_LARGE,M01SNAP-FEMALE,SNAP-FEMALE,Header 1,,')
newPart.addTag('rawParts','JP14,FIDUCIALUFIDUCIAL,FIDUCIALUFIDUCIAL,MICRO-FIDUCIAL,Fiducial Alignment Points,,')
newPart.addTag('rawParts','JP15,FIDUCIALUFIDUCIAL,FIDUCIALUFIDUCIAL,MICRO-FIDUCIAL,Fiducial Alignment Points,,')
newPart.addTag('rawParts','JP16,FIDUCIALUFIDUCIAL,FIDUCIALUFIDUCIAL,MICRO-FIDUCIAL,Fiducial Alignment Points,,')
newPart.addTag('rawParts','PP-GND,,TEST-POINT3X5,PAD.03X.05,,,')
newPart.addTag('rawParts','PP-MISO,,TEST-POINT3X5,PAD.03X.05,,,')
newPart.addTag('rawParts','PP-MOSI,,TEST-POINT3X5,PAD.03X.05,,,')
newPart.addTag('rawParts','PP-RST,,TEST-POINT3X5,PAD.03X.05,,,')
newPart.addTag('rawParts','PP-SCK,,TEST-POINT3X5,PAD.03X.05,,,')
newPart.addTag('rawParts','PP-VCC,,TEST-POINT3X5,PAD.03X.05,,,')
newPart.addTag('rawParts','R1,330,RESISTOR0402-RES,0402-RES,Resistor,,')
newPart.addTag('rawParts','R2,10k,RESISTOR0402-RES,0402-RES,Resistor,,')
newPart.addTag('rawParts','R3,10K,RESISTOR0402-RES,0402-RES,Resistor,,')
newPart.addTag('rawParts','R9,330,RESISTOR0402-RES,0402-RES,Resistor,,')
newPart.addTag('rawParts','S2,On/Off,AYZ0202,AYZ0202,SPDT Slide Switch,,')
newPart.addTag('rawParts','S3,Reset,SWITCH-MOMENTARY-2SMD,TACTILE_SWITCH_SMD,,,')
newPart.addTag('rawParts','TP-DTR,,TEST-POINT3X5,PAD.03X.05,,,')
newPart.addTag('rawParts','TP-FTDI_VCC,,TEST-POINT3X5,PAD.03X.05,,,')
newPart.addTag('rawParts','TP-RX,,TEST-POINT3X5,PAD.03X.05,,,')
newPart.addTag('rawParts','TP-TX,,TEST-POINT3X5,PAD.03X.05,,,')
newPart.addTag('rawParts','U$2,LOGO-LPLP,LOGO-LPLP,LOGO-LILYPAD,,,')
newPart.addTag('rawParts','U1,ATMEGA328,ATMEGA168,TQFP32-08,,,')
newPart.addTag('rawParts','U2,MCP73831,MCP73831,SOT23-5,Microchips MCP73831,,')
newPart.addTag('rawParts','Y1,8MHz,RESONATORSMD,RESONATOR-SMD,Resonator,,')