import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-10101-STAN-01")

newPart.addTag('rawParts','"C1",".1uF","CAP0603-CAP","0603-CAP","Capacitor","",')
newPart.addTag('rawParts','"IC1","LMV358","OPAMP-DUALU","SO08","Operational Amplifier","",')
newPart.addTag('rawParts','"JP2","","M06SIP","1X06","Header 6","",')
newPart.addTag('rawParts','"Q1","mmbt2222","TRANSISTOR_NPNSOT23-3","SOT23-3","Transistor NPN","",')
newPart.addTag('rawParts','"Q2","mmbt2222","TRANSISTOR_NPNSOT23-3","SOT23-3","Transistor NPN","",')
newPart.addTag('rawParts','"R1","10K","TRIMPOTSMD","TRIMPOT-3MM","","",')
newPart.addTag('rawParts','"R2","10K","TRIMPOTSMD","TRIMPOT-3MM","","",')
newPart.addTag('rawParts','"R3","10K","RESISTOR0603-RES","0603-RES","Resistor","",')
newPart.addTag('rawParts','"R4","330","RESISTOR0603-RES","0603-RES","Resistor","",')
newPart.addTag('rawParts','"R5","10K","RESISTOR0603-RES","0603-RES","Resistor","",')
newPart.addTag('rawParts','"R6","20K","RESISTOR0603-RES","0603-RES","Resistor","",')
newPart.addTag('rawParts','"R7","2K","RESISTOR0603-RES","0603-RES","Resistor","",')
newPart.addTag('rawParts','"STAT","","LED0603","LED-0603","LEDs","",')
newPart.addTag('rawParts','"U$3","LOGO-SFENEW","LOGO-SFENEW","SFE-NEW-WEBLOGO","Spark Fun Electronics PCB Logo","",')