import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-13281-STAN-01")

newPart.addTag('rawParts','"FRAME1","","FRAME-LETTER","CREATIVE_COMMONS","Schematic Frame","N. Seidle","","","v02",')
newPart.addTag('rawParts','"JP1","UL","M03PTH","1X03","Header 3","","","","",')
newPart.addTag('rawParts','"JP2","UR","M03PTH","1X03","Header 3","","","","",')
newPart.addTag('rawParts','"JP3","LL","M03PTH","1X03","Header 3","","","","",')
newPart.addTag('rawParts','"JP4","LR","M03PTH","1X03","Header 3","","","","",')
newPart.addTag('rawParts','"JP5","","M05PTH","1X05","Header 5","","","","",')
newPart.addTag('rawParts','"JP6","RJ45","RJ45-8PTH","RJ45-8","RJ45 Jack","","CONN-08506","RJ45","",')
newPart.addTag('rawParts','"JP7","","M03PTH","1X03","Header 3","","","","",')
newPart.addTag('rawParts','"LOGO3","SFE_LOGO_FLAME.1_INCH","SFE_LOGO_FLAME.1_INCH","SFE_LOGO_FLAME_.1","SFE Logo, flame only","","","","",')
newPart.addTag('rawParts','"STANDOFF1","STAND-OFF","STAND-OFF","STAND-OFF","#4 Stand Off","","","","",')
newPart.addTag('rawParts','"STANDOFF2","STAND-OFF","STAND-OFF","STAND-OFF","#4 Stand Off","","","","",')
newPart.addTag('rawParts','"STANDOFF3","STAND-OFF","STAND-OFF","STAND-OFF","#4 Stand Off","","","","",')
newPart.addTag('rawParts','"STANDOFF4","STAND-OFF","STAND-OFF","STAND-OFF","#4 Stand Off","","","","",')
newPart.addTag('rawParts','"U$7","OSHW-LOGOS","OSHW-LOGOS","OSHW-LOGO-S","Open Source Hardware Logo","","","","",')