import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-5189-STAN-01")

newPart.addTag('rawParts','B1,CR1220,BATTERYCR1220_SMT,CR1220,CR1220 SMT - Digikey: 3001K-ND,,')
newPart.addTag('rawParts','C1,10uF,CAP_CERAMIC0805-NOOUTLINE,0805-NO,Ceramic Capacitors,,')
newPart.addTag('rawParts','C2,10uF,CAP_CERAMIC0805-NOOUTLINE,0805-NO,Ceramic Capacitors,,')
newPart.addTag('rawParts','FID1,FIDUCIAL,FIDUCIAL,FIDUCIAL_1MM,Fiducial Alignment Points,EXCLUDE,')
newPart.addTag('rawParts','FID2,FIDUCIAL,FIDUCIAL,FIDUCIAL_1MM,Fiducial Alignment Points,EXCLUDE,')
newPart.addTag('rawParts','IC1,RTC_PCF8523T,RTC_PCF8523T,SOIC8_150MIL,,,')
newPart.addTag('rawParts','JP2,,HEADER-1X576MIL,1X05_ROUND_76,PIN HEADER,,')
newPart.addTag('rawParts','Q1,32.768,CRYSTAL8.0X3.8,CRYSTAL_8X3.8,Crystals,,')
newPart.addTag('rawParts','R1,10K,RESISTOR0805_NOOUTLINE,0805-NO,Resistors,,')
newPart.addTag('rawParts','R2,10K,RESISTOR0805_NOOUTLINE,0805-NO,Resistors,,')
newPart.addTag('rawParts','R3,1K,RESISTOR0805_NOOUTLINE,0805-NO,Resistors,,')
newPart.addTag('rawParts','SJ1,,SOLDERJUMPER_CLOSED,SOLDERJUMPER_CLOSEDWIRE,Solder Jumper - Closed,,')
newPart.addTag('rawParts','SJ2,,SOLDERJUMPER_CLOSED,SOLDERJUMPER_CLOSEDWIRE,Solder Jumper - Closed,,')
newPart.addTag('rawParts','U$1,MOUNTINGHOLE2.0,MOUNTINGHOLE2.0,MOUNTINGHOLE_2.0_PLATED,Mounting Hole,EXCLUDE,')
newPart.addTag('rawParts','U$4,MOUNTINGHOLE2.0,MOUNTINGHOLE2.0,MOUNTINGHOLE_2.0_PLATED,Mounting Hole,EXCLUDE,')