import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-2453-STAN-01")

newPart.addTag('rawParts','"C1","0.1uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","",')
newPart.addTag('rawParts','"C2","1uF","CAP_CERAMIC_0805MP","_0805MP","Ceramic Capacitors","","",')
newPart.addTag('rawParts','"C3","0.1uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","",')
newPart.addTag('rawParts','"C4","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","",')
newPart.addTag('rawParts','"C5","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","",')
newPart.addTag('rawParts','"C7","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","",')
newPart.addTag('rawParts','"C8","1uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","",')
newPart.addTag('rawParts','"D1","MM3Z24VT1G","DIODESMA","SMADIODE","Diode","","",')
newPart.addTag('rawParts','"D2","MBR0540","DIODESOD-123","SOD-123","Diode","","",')
newPart.addTag('rawParts','"D3","1N4148","DIODESOD-323","SOD-323","Diode","","",')
newPart.addTag('rawParts','"FB1","FERRITE","FERRITE_0805MP","_0805MP","Ferrite Bead","","",')
newPart.addTag('rawParts','"FB2","FERRITE","FERRITE_0805MP","_0805MP","Ferrite Bead","","",')
newPart.addTag('rawParts','"FB3","Ferrite","FERRITE_0805MP","_0805MP","Ferrite Bead","","",')
newPart.addTag('rawParts','"FB4","FERITE","FERRITE_0805MP","_0805MP","Ferrite Bead","","",')
newPart.addTag('rawParts','"FID1","FIDUCIAL""","FIDUCIAL""","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE","",')
newPart.addTag('rawParts','"FID2","FIDUCIAL""","FIDUCIAL""","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE","",')
newPart.addTag('rawParts','"FID3","FIDUCIAL""","FIDUCIAL""","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE","",')
newPart.addTag('rawParts','"IC1","AR1100_SSOP","AR1100_SSOP","TSSOP20-5.3MMBODY","","","",')
newPart.addTag('rawParts','"J1","40PINFPCM4-1734839-0","40PINFPCM4-1734839-0","4-1734839-0","OMRON FPC Connector","","",')
newPart.addTag('rawParts','"L1","6.8uH power L CID 2276","INDUCTORNR5040","INDUCTOR_5X5MM_NR5040_NOTHERMALS","Inductors","","",')
newPart.addTag('rawParts','"LED1","RED","LED0805_NOOUTLINE","CHIPLED_0805_NOOUTLINE","LED","","",')
newPart.addTag('rawParts','"R1","20K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","","",')
newPart.addTag('rawParts','"R2","6\xc3\xa2\xe2\x80\x9e\xc2\xa6","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","","",')
newPart.addTag('rawParts','"R3","12\xc3\xa2\xe2\x80\x9e\xc2\xa6","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","","",')
newPart.addTag('rawParts','"R4","12\xc3\xa2\xe2\x80\x9e\xc2\xa6","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","","",')
newPart.addTag('rawParts','"R5","20K","RESISTOR_0805MP","_0805MP","Resistors","","",')
newPart.addTag('rawParts','"R6","33","RESISTOR_4PACK","RESPACK_4X0603","Resistor Packs (4 resistors)","","",')
newPart.addTag('rawParts','"R7","12\xc3\xa2\xe2\x80\x9e\xc2\xa6","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","","",')
newPart.addTag('rawParts','"R8","33","RESISTOR_4PACK","RESPACK_4X0603","Resistor Packs (4 resistors)","","",')
newPart.addTag('rawParts','"R9","33","RESISTOR_4PACK","RESPACK_4X0603","Resistor Packs (4 resistors)","","",')
newPart.addTag('rawParts','"R10","33","RESISTOR_4PACK","RESPACK_4X0603","Resistor Packs (4 resistors)","","",')
newPart.addTag('rawParts','"R11","33","RESISTOR_4PACK","RESPACK_4X0603","Resistor Packs (4 resistors)","","",')
newPart.addTag('rawParts','"R12","33","RESISTOR_4PACK","RESPACK_4X0603","Resistor Packs (4 resistors)","","",')
newPart.addTag('rawParts','"R13","470","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","","",')
newPart.addTag('rawParts','"R14","20K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","","",')
newPart.addTag('rawParts','"RPI1","RASPBERRYPI_BPLUS-SMT+SLOTS","RASPBERRYPI_BPLUS-SMT+SLOTS","PI_HAT_SMT_SLOTS","","","",')
newPart.addTag('rawParts','"SJ1","+50mA","SOLDERJUMPER","SOLDERJUMPER_ARROW_NOPASTE","SMD Solder JUMPER","EXCLUDE","",')
newPart.addTag('rawParts','"SJ2","+25mA","SOLDERJUMPER","SOLDERJUMPER_ARROW_NOPASTE","SMD Solder JUMPER","EXCLUDE","",')
newPart.addTag('rawParts','"SJ3","+100mA","SOLDERJUMPER","SOLDERJUMPER_ARROW_NOPASTE","SMD Solder JUMPER","EXCLUDE","",')
newPart.addTag('rawParts','"TP1","TPTP15SQ","TPTP15SQ","TP15SQ","Test pad","","",')
newPart.addTag('rawParts','"TP2","TPTP15SQ","TPTP15SQ","TP15SQ","Test pad","","",')
newPart.addTag('rawParts','"TP3","TPTP15SQ","TPTP15SQ","TP15SQ","Test pad","","",')
newPart.addTag('rawParts','"TP4","TPTP15SQ","TPTP15SQ","TP15SQ","Test pad","","",')
newPart.addTag('rawParts','"TP5","TPTP15SQ","TPTP15SQ","TP15SQ","Test pad","","",')
newPart.addTag('rawParts','"TP6","TPTP15SQ","TPTP15SQ","TP15SQ","Test pad","","",')
newPart.addTag('rawParts','"TP7","TPTP15SQ","TPTP15SQ","TP15SQ","Test pad","","",')
newPart.addTag('rawParts','"TP8","TPTP15SQ","TPTP15SQ","TP15SQ","Test pad","","",')
newPart.addTag('rawParts','"TP9","TPTP15SQ","TPTP15SQ","TP15SQ","Test pad","","",')
newPart.addTag('rawParts','"TP10","TPTP15SQ","TPTP15SQ","TP15SQ","Test pad","","",')
newPart.addTag('rawParts','"TP11","TPTP15SQ","TPTP15SQ","TP15SQ","Test pad","","",')
newPart.addTag('rawParts','"TP12","TPTP15SQ","TPTP15SQ","TP15SQ","Test pad","","",')
newPart.addTag('rawParts','"TP13","TPTP15SQ","TPTP15SQ","TP15SQ","Test pad","","",')
newPart.addTag('rawParts','"U3","FAN5333BSX","FAN5331","SOT23-5@1","FAN5331 - LED/OLED 20V Boost Converter","","",')
newPart.addTag('rawParts','"X1","MicroUSB","USBMICRO_20329","4UCONN_20329","USB Connectors","","",')
newPart.addTag('rawParts','"Y1","12MHz","RESONATORSMD","RESONATOR-SMD","Resonator","","",')