import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-10406-STAN-01")

newPart.addTag('rawParts','"C1","0.1uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C2","22pF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C3","27pF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C4","27pF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C5","18pF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C6","18pF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C7","22pF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C8","0.1uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"JP1","XBee Regulated","M06SIP","1X06","Header 6","",')
newPart.addTag('rawParts','"JP2","LOGO-SFENEW","LOGO-SFENEW","SFE-NEW-WEBLOGO","Spark Fun Electronics PCB Logo","",')
newPart.addTag('rawParts','"JP3","STAND-OFF","STAND-OFF","STAND-OFF","Stand Off","",')
newPart.addTag('rawParts','"JP4","LOGO-SFESK","LOGO-SFESK","SFE-LOGO-FLAME","Spark Fun Electronics PCB Logo","",')
newPart.addTag('rawParts','"JP5","STAND-OFF","STAND-OFF","STAND-OFF","Stand Off","",')
newPart.addTag('rawParts','"JP6","","M05PTH","1X05","Header 5","",')
newPart.addTag('rawParts','"JP7","STAND-OFF","STAND-OFF","STAND-OFF","Stand Off","",')
newPart.addTag('rawParts','"JP8","LOGO-SFENEW","LOGO-SFENEW","SFE-NEW-WEBLOGO","Spark Fun Electronics PCB Logo","",')
newPart.addTag('rawParts','"JP10","STAND-OFF","STAND-OFF","STAND-OFF","Stand Off","",')
newPart.addTag('rawParts','"JP11","FIDUCIAL1X2","FIDUCIAL1X2","FIDUCIAL-1X2","Fiducial Alignment Points","",')
newPart.addTag('rawParts','"JP12","FIDUCIAL1X2","FIDUCIAL1X2","FIDUCIAL-1X2","Fiducial Alignment Points","",')
newPart.addTag('rawParts','"JP13","STAND-OFF","STAND-OFF","STAND-OFF","Stand Off","",')
newPart.addTag('rawParts','"LED1","yellow","LED0603","LED-0603","LEDs","",')
newPart.addTag('rawParts','"LED2","green","LED0603","LED-0603","LEDs","",')
newPart.addTag('rawParts','"LED3","red","LED0603","LED-0603","LEDs","",')
newPart.addTag('rawParts','"R1","10k","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R3","330","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R4","330","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R5","4.7k","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R6","4.7k","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R7","330","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R8","0 Ohm","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R9","0 Ohm","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"S1","Reset","SWITCH-MOMENTARY-2SMD","TACTILE_SWITCH_SMD","","",')
newPart.addTag('rawParts','"S2","Reset","SWITCH-MOMENTARY-2SMD","TACTILE_SWITCH_SMD","","",')
newPart.addTag('rawParts','"SJ1","","SOLDERJUMPER_2WAYPASTE2&3","SJ_3_PASTE2&3","Solder Jumper","",')
newPart.addTag('rawParts','"SJ2","","SOLDERJUMPER_2WAYPASTE2&3","SJ_3_PASTE2&3","Solder Jumper","",')
newPart.addTag('rawParts','"SJ3","","SOLDERJUMPER_2WAYPASTE2&3","SJ_3_PASTE2&3","Solder Jumper","",')
newPart.addTag('rawParts','"SJ4","","SOLDERJUMPER_2WAYPASTE2&3","SJ_3_PASTE2&3","Solder Jumper","",')
newPart.addTag('rawParts','"U1","DNP_SM130","SM130","SM130","13.56MHz RFID Mifare Read/Write Module","",')
newPart.addTag('rawParts','"U3","ARDUINO_SHIELDNOLABELS","ARDUINO_SHIELDNOLABELS","DUEMILANOVE_SHIELD_NOLABELS","","",')