import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-1755-STAN-01")

newPart.addTag('oompParts','LED1,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')
newPart.addTag('oompParts','R1,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')