import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-11113-STAN-01")

newPart.addTag('rawParts','C1,0.1uF,CAP0402-CAP,0402-CAP,Capacitor,,')
newPart.addTag('rawParts','C2,0.1uF,CAP0402-CAP,0402-CAP,Capacitor,,')
newPart.addTag('rawParts','C3,0.1uF,CAP0402-CAP,0402-CAP,Capacitor,,')
newPart.addTag('rawParts','C10,0.1uF,CAP0402-CAP,0402-CAP,Capacitor,,')
newPart.addTag('rawParts','C13,10uF,CAP_POL1206,EIA3216,Capacitor Polarized,,')
newPart.addTag('rawParts','C19,10uF,CAP_POL1206,EIA3216,Capacitor Polarized,,')
newPart.addTag('rawParts','D3,Green,LED0603,LED-0603,LEDs,,')
newPart.addTag('rawParts','FRAME1,FRAME-LETTER,FRAME-LETTER,CREATIVE_COMMONS,Schematic Frame,,')
newPart.addTag('rawParts','JP1,FTDI Basic,ARDUINO_SERIAL_PROGRAMPTH,1X06,,,')
newPart.addTag('rawParts','JP2,,M02PTH,1X02,Header 2,,')
newPart.addTag('rawParts','JP3,,M01PTH,1X01,Header 1,,')
newPart.addTag('rawParts','JP4,,M01PTH,1X01,Header 1,,')
newPart.addTag('rawParts','JP5,FIDUCIALUFIDUCIAL,FIDUCIALUFIDUCIAL,MICRO-FIDUCIAL,Fiducial Alignment Points,,')
newPart.addTag('rawParts','JP6,,M12PTH,1X12,Header 12,,')
newPart.addTag('rawParts','JP7,,M12PTH,1X12,Header 12,,')
newPart.addTag('rawParts','JP8,FIDUCIALUFIDUCIAL,FIDUCIALUFIDUCIAL,MICRO-FIDUCIAL,Fiducial Alignment Points,,')
newPart.addTag('rawParts','LED1,Red,LED0603,LED-0603,LEDs,,')
newPart.addTag('rawParts','Q1,8/16/20MHz,RESONATORSMD,RESONATOR-SMD,Resonator,,')
newPart.addTag('rawParts','R1,,RESISTOR0402-RES,0402-RES,Resistor,,')
newPart.addTag('rawParts','R2,10K,RESISTOR0402-RES,0402-RES,Resistor,,')
newPart.addTag('rawParts','R3,,RESISTOR0402-RES,0402-RES,Resistor,,')
newPart.addTag('rawParts','R6,330,RESISTOR0402-RES,0402-RES,Resistor,,')
newPart.addTag('rawParts','R11,10K,RESISTOR0402-RES,0402-RES,Resistor,,')
newPart.addTag('rawParts','S2,Reset,TAC_SWITCHSMD,TACTILE_SWITCH_SMD,Momentary Switch,,')
newPart.addTag('rawParts','U$1,LOGO-SFESK,LOGO-SFESK,SFE-LOGO-FLAME,Spark Fun Electronics PCB Logo,,')
newPart.addTag('rawParts','U$2,PRO_MINI_CANDY,PRO_MINI_CANDY,PRO_MINI_CANDY,,,')
newPart.addTag('rawParts','U$3,OSHW-LOGOS,OSHW-LOGOS,OSHW-LOGO-S,Open Source Hardware Logo This logo indicates the piece of hardware it is found on incorporates a OSHW license and/or adheres to the definition of open source hardware found here: http://freedomdefined.org/OSHW,,')
newPart.addTag('rawParts','U1,ATMEGA328,ATMEGA168,TQFP32-08,,,')
newPart.addTag('rawParts','U2,MIC5205,V_REG_LDOSMD,SOT23-5,Voltage Regulator LDO,,')