import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-10680-STAN-01")

newPart.addTag('oompParts','JP1,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')
newPart.addTag('oompParts','JP2,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')
newPart.addTag('oompParts','JP3,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')
newPart.addTag('oompParts','JP4,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')
newPart.addTag('oompParts','JP5,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')
newPart.addTag('oompParts','U$1,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')
newPart.addTag('oompParts','U$2,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')
newPart.addTag('oompParts','U1,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')