import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-2348-STAN-01")

newPart.addTag('oompParts','C1,CAPC-0805-X-NF100-V50')
newPart.addTag('oompParts','C3,CAPC-0805-X-NF100-V50')
newPart.addTag('oompParts','C4,CAPX-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','C5,CAPX-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','C6,CAPC-0805-X-UF10-V10')
newPart.addTag('oompParts','C10,CAPC-0805-X-UF10-V10')
newPart.addTag('oompParts','CONN1,HEAD-I01-X-PI25-01')
newPart.addTag('oompParts','IC1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','IC3,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','J1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','J3,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','JP1,HEAD-I01-X-PI04-01')
newPart.addTag('oompParts','LED1,LEDS-0805-G-STAN-01')
newPart.addTag('oompParts','MPOWER,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','Q1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','R1,RESE-0805-X-UNMATCHED-01')
newPart.addTag('oompParts','R2,RESE-0805-X-UNMATCHED-01')
newPart.addTag('oompParts','R3,RESE-0805-X-UNMATCHED-01')
newPart.addTag('oompParts','R4,RESE-0805-X-O103-01')
newPart.addTag('oompParts','R5,RESE-0805-X-O103-01')
newPart.addTag('oompParts','R6,RESE-0805-X-O103-01')
newPart.addTag('oompParts','R7,RESE-0805-X-O102-01')
newPart.addTag('oompParts','R8,RESE-0805-X-O103-01')
newPart.addTag('oompParts','R9,RESE-0805-X-O103-01')
newPart.addTag('oompParts','RPI1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','TP1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','TP2,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','TP3,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','TP4,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','TP5,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U2,UNMATCHED-UNMATCHED-X-UNMATCHED-01')