import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-3651-STAN-01")

newPart.addTag('rawParts','"C1","1uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C2","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C3","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C4","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C5","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C16","1uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C18","0.1uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C20","1uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"D1","MM3Z24VT1G","DIODESMA","SMADIODE","Diode","",')
newPart.addTag('rawParts','"D2","MBR0540","DIODESOD-123","SOD-123","Diode","",')
newPart.addTag('rawParts','"D3","MBR120","DIODESOD-123","SOD-123","Diode","",')
newPart.addTag('rawParts','"D4","MBR120","DIODESOD-123","SOD-123","Diode","",')
newPart.addTag('rawParts','"ENABLE","Slide Switch","SWITCH_DPDTEG1390","EG1390","Switch - DPDT","",')
newPart.addTag('rawParts','"IC4","APX803-SAG","AXP083-SAG","SOT23","","",')
newPart.addTag('rawParts','"L1","15uH","INDUCTORNR5040","INDUCTOR_5X5MM_NR5040_NOTHERMALS","Inductors","",')
newPart.addTag('rawParts','"MS2","FEATHERWING_SMTDUAL","FEATHERWING_SMTDUAL","FEATHERWING_SMT2","","",')
newPart.addTag('rawParts','"R1","12\xc3\xa2\xe2\x80\x9e\xc2\xa6","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R2","100K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R5","100K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R6","10K","R-US_R0805","R0805","RESISTOR, American symbol","",')
newPart.addTag('rawParts','"R8","100K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R12","10K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"SJ1","","SOLDERJUMPER_CLOSED","SOLDERJUMPER_CLOSEDWIRE","Solder Jumper - Closed","",')
newPart.addTag('rawParts','"SJ2","","SOLDERJUMPER_CLOSED","SOLDERJUMPER_CLOSEDWIRE","Solder Jumper - Closed","",')
newPart.addTag('rawParts','"SJ3","","SOLDERJUMPER_CLOSED","SOLDERJUMPER_CLOSEDWIRE","Solder Jumper - Closed","",')
newPart.addTag('rawParts','"SJ4","","SOLDERJUMPER_CLOSED","SOLDERJUMPER_CLOSEDWIRE","Solder Jumper - Closed","",')
newPart.addTag('rawParts','"SW1","EVQQ2","SWITCH_TACT_SMT_EVQQ2_SMALL","EVQ-Q2_SMALLER","SMT Tact Switches","",')
newPart.addTag('rawParts','"TP1","","TESTPOINTPAD2MM","TESTPOINT_PAD_2MM","Test Point","",')
newPart.addTag('rawParts','"TP2","","TESTPOINTPAD2MM","TESTPOINT_PAD_2MM","Test Point","",')
newPart.addTag('rawParts','"TP4","","TESTPOINTPAD2MM","TESTPOINT_PAD_2MM","Test Point","",')
newPart.addTag('rawParts','"TP5","","TESTPOINTPAD2MM","TESTPOINT_PAD_2MM","Test Point","",')
newPart.addTag('rawParts','"TP6","","TESTPOINTPAD2MM","TESTPOINT_PAD_2MM","Test Point","",')
newPart.addTag('rawParts','"TP7","","TESTPOINTPAD2MM","TESTPOINT_PAD_2MM","Test Point","",')
newPart.addTag('rawParts','"TP8","","TESTPOINTPAD2MM","TESTPOINT_PAD_2MM","Test Point","",')
newPart.addTag('rawParts','"TP9","","TESTPOINTPAD2MM","TESTPOINT_PAD_2MM","Test Point","",')
newPart.addTag('rawParts','"TP10","","TESTPOINTPAD2MM","TESTPOINT_PAD_2MM","Test Point","",')
newPart.addTag('rawParts','"TP11","","TESTPOINTPAD2MM","TESTPOINT_PAD_2MM","Test Point","",')
newPart.addTag('rawParts','"TP12","","TESTPOINTPAD2MM","TESTPOINT_PAD_2MM","Test Point","",')
newPart.addTag('rawParts','"TP13","","TESTPOINTPAD2MM","TESTPOINT_PAD_2MM","Test Point","",')
newPart.addTag('rawParts','"TP14","","TESTPOINTPAD2MM","TESTPOINT_PAD_2MM","Test Point","",')
newPart.addTag('rawParts','"TP15","","TESTPOINTPAD2MM","TESTPOINT_PAD_2MM","Test Point","",')
newPart.addTag('rawParts','"TP16","","TESTPOINTPAD2MM","TESTPOINT_PAD_2MM","Test Point","",')
newPart.addTag('rawParts','"TP17","","TESTPOINTPAD2MM","TESTPOINT_PAD_2MM","Test Point","",')
newPart.addTag('rawParts','"TP18","","TESTPOINTPAD2MM","TESTPOINT_PAD_2MM","Test Point","",')
newPart.addTag('rawParts','"TP19","","TESTPOINTPAD2MM","TESTPOINT_PAD_2MM","Test Point","",')
newPart.addTag('rawParts','"TP20","","TESTPOINTPAD2MM","TESTPOINT_PAD_2MM","Test Point","",')
newPart.addTag('rawParts','"TP21","","TESTPOINTPAD2MM","TESTPOINT_PAD_2MM","Test Point","",')
newPart.addTag('rawParts','"TP22","","TESTPOINTPAD2MM","TESTPOINT_PAD_2MM","Test Point","",')
newPart.addTag('rawParts','"TP23","","TESTPOINTPAD2MM","TESTPOINT_PAD_2MM","Test Point","",')
newPart.addTag('rawParts','"TP24","","TESTPOINTPAD2MM","TESTPOINT_PAD_2MM","Test Point","",')
newPart.addTag('rawParts','"TP25","","TESTPOINTPAD2MM","TESTPOINT_PAD_2MM","Test Point","",')
newPart.addTag('rawParts','"TP26","","TESTPOINTPAD2MM","TESTPOINT_PAD_2MM","Test Point","",')
newPart.addTag('rawParts','"TP27","","TESTPOINTPAD2MM","TESTPOINT_PAD_2MM","Test Point","",')
newPart.addTag('rawParts','"U$7","MOUNTINGHOLE3.0THIN","MOUNTINGHOLE3.0THIN","MOUNTINGHOLE_3.0_PLATEDTHIN","Mounting Hole","EXCLUDE",')
newPart.addTag('rawParts','"U$9","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"U$15","MOUNTINGHOLE3.0THIN","MOUNTINGHOLE3.0THIN","MOUNTINGHOLE_3.0_PLATEDTHIN","Mounting Hole","EXCLUDE",')
newPart.addTag('rawParts','"U$16","MOUNTINGHOLE3.0THIN","MOUNTINGHOLE3.0THIN","MOUNTINGHOLE_3.0_PLATEDTHIN","Mounting Hole","EXCLUDE",')
newPart.addTag('rawParts','"U$17","MOUNTINGHOLE3.0THIN","MOUNTINGHOLE3.0THIN","MOUNTINGHOLE_3.0_PLATEDTHIN","Mounting Hole","EXCLUDE",')
newPart.addTag('rawParts','"U$23","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"U2","STMPE811","STMPE610","QFN16_3MM","STMPE610 - 12-Bit Touch Screen Controller","",')
newPart.addTag('rawParts','"U3","FAN5333BSX","FAN5331","SOT23-5@1","FAN5331 - LED/OLED 20V Boost Converter","",')
newPart.addTag('rawParts','"X1","MicroSD","MICROSD","MICROSD","MicroSD/Transflash Card Holder with SPI pinout","",')
newPart.addTag('rawParts','"X2","3.5" TFT","DISP_LCD_3.5IN_320X480_50PIN","TFT_3.5IN_320X480_50PIN","DT350HV15-T - 3.5" 320x480 TFT Display, 50 Pin Connector","",')