import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-14891-STAN-01")

newPart.addTag('oompParts','D1,DIOD-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','LOGO7,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','R8,RESE-0603-X-O201-01')
newPart.addTag('oompParts','R9,RESE-0603-X-O101-01')
newPart.addTag('oompParts','R10,RESE-0603-X-O101-01')
newPart.addTag('oompParts','R11,RESE-0603-X-O103-01')
newPart.addTag('oompParts','U$10,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U$11,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U$12,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U$14,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U$15,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U$19,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U$22,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U$23,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U$24,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U$25,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U$26,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U$35,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U2,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U3,UNMATCHED-SO23-X-UNMATCHED-01')