import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-2927-STAN-01")

newPart.addTag('rawParts','"A0","","SOLDERJUMPERREFLOW_NOPASTE","SOLDERJUMPER_REFLOW_NOPASTE","SMD Solder JUMPER","",')
newPart.addTag('rawParts','"A1","","SOLDERJUMPERREFLOW_NOPASTE","SOLDERJUMPER_REFLOW_NOPASTE","SMD Solder JUMPER","",')
newPart.addTag('rawParts','"A2","","SOLDERJUMPERREFLOW_NOPASTE","SOLDERJUMPER_REFLOW_NOPASTE","SMD Solder JUMPER","",')
newPart.addTag('rawParts','"A3","","SOLDERJUMPERREFLOW_NOPASTE","SOLDERJUMPER_REFLOW_NOPASTE","SMD Solder JUMPER","",')
newPart.addTag('rawParts','"A4","","SOLDERJUMPERREFLOW_NOPASTE","SOLDERJUMPER_REFLOW_NOPASTE","SMD Solder JUMPER","",')
newPart.addTag('rawParts','"C2","0.1uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C4","47uF/16v","CAP_ELECTROLYTICPANASONIC_C","PANASONIC_C","Electrolytic Capacitors","",')
newPart.addTag('rawParts','"C5","47uF+/16v","CAP_ELECTROLYTICPANASONIC_C","PANASONIC_C","Electrolytic Capacitors","",')
newPart.addTag('rawParts','"C6","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C10","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"IC1","TB6612FNG","TB6612FNG","SSOP24","TB6612FNG","",')
newPart.addTag('rawParts','"IC3","TB6612FNG","TB6612FNG","SSOP24","TB6612FNG","",')
newPart.addTag('rawParts','"JP1","","HEADER-1X12","1X12_ROUND","","",')
newPart.addTag('rawParts','"JP2","","HEADER-1X16ROUND","1X16_ROUND","PIN HEADER","",')
newPart.addTag('rawParts','"LED1","Green","LED0805_NOOUTLINE","CHIPLED_0805_NOOUTLINE","LED","",')
newPart.addTag('rawParts','"MPOWER","1X2-3.5MM","1X2-3.5MM","1X2-3.5MM","3.5mm Terminal block","",')
newPart.addTag('rawParts','"MS1","FEATHERWING","FEATHERWING","FEATHERWING","","",')
newPart.addTag('rawParts','"Q1","AON7401","MOSFET-P-POWERDI3333","POWERDI3333","P-Channel Mosfet","",')
newPart.addTag('rawParts','"R4","1K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R9","10K","RESISTOR_4PACK","RESPACK_4X0603","Resistor Packs (4 resistors)","",')
newPart.addTag('rawParts','"R10","10K","RESISTOR_4PACK","RESPACK_4X0603","Resistor Packs (4 resistors)","",')
newPart.addTag('rawParts','"SW1","","SWITCH_TACT_SMT4.6X2.8","BTN_KMR2_4.6X2.8","SMT Tact Switches","",')
newPart.addTag('rawParts','"U$3","FIDUCIAL""","FIDUCIAL""","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"U$4","FIDUCIAL""","FIDUCIAL""","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"U2","PCA9685","PCA9685","TSSOP28","PCA9685 - 16 Channel 12-Bit I2C PWM Controller","",')
newPart.addTag('rawParts','"X1","","TERMBLOCK_1X2","TERMBLOCK_1X2-3.5MM","3.5mm Terminal block","",')
newPart.addTag('rawParts','"X2","","TERMBLOCK_1X2","TERMBLOCK_1X2-3.5MM","3.5mm Terminal block","",')
newPart.addTag('rawParts','"X4","","TERMBLOCK_1X2","TERMBLOCK_1X2-3.5MM","3.5mm Terminal block","",')
newPart.addTag('rawParts','"X6","","TERMBLOCK_1X2","TERMBLOCK_1X2-3.5MM","3.5mm Terminal block","",')