import OOMP
newPart = OOMP.getPartByID("PROJ-ARDU-MICRO-STAN-01")

newPart.addTag('rawParts','"C1","100n","C-EUC0402","C0402","CAPACITOR, European symbol","","","","","","","","",')
newPart.addTag('rawParts','"C2","100n","C-EUC0402","C0402","CAPACITOR, European symbol","","","","","","","","",')
newPart.addTag('rawParts','"C3","22u","CPOL-EUSMCB","SMC_B","POLARIZED CAPACITOR, European symbol","","","","","","","","",')
newPart.addTag('rawParts','"C4","1uF","C-EUC0402","C0402","CAPACITOR, European symbol","","","","","","","","",')
newPart.addTag('rawParts','"C5","1uF","C-EUC0402","C0402","CAPACITOR, European symbol","","","","","","","","",')
newPart.addTag('rawParts','"C6","100n","C-EUC0402","C0402","CAPACITOR, European symbol","","","","","","","","",')
newPart.addTag('rawParts','"C7","1uF","C-EUC0402","C0402","CAPACITOR, European symbol","","","","","","","","",')
newPart.addTag('rawParts','"C9","100n","C-EUC0402","C0402","CAPACITOR, European symbol","","","","","","","","",')
newPart.addTag('rawParts','"C10","100n","C-EUC0402","C0402","CAPACITOR, European symbol","","","","","","","","",')
newPart.addTag('rawParts','"C11","100n","C-EUC0402","C0402","CAPACITOR, European symbol","","","","","","","","",')
newPart.addTag('rawParts','"C12","22pF","C-EUC0402","C0402","CAPACITOR, European symbol","","","","","","","","",')
newPart.addTag('rawParts','"C13","22pF","C-EUC0402","C0402","CAPACITOR, European symbol","","","","","","","","",')
newPart.addTag('rawParts','"C14","22u","CPOL-EUSMCB","SMC_B","POLARIZED CAPACITOR, European symbol","","","","","","","","",')
newPart.addTag('rawParts','"D+","DNP","TPTP-1.00MM","TP-1.00MM","Testpoint","","DNP","DNP","DNP","DNP","DNP","","DNP",')
newPart.addTag('rawParts','"D-","DNP","TPTP-1.00MM","TP-1.00MM","Testpoint","","DNP","DNP","DNP","DNP","DNP","","DNP",')
newPart.addTag('rawParts','"D2","CD1206-S01575","DIODE-MINIMELF","MINIMELF","DIODE","","","","","","","","",')
newPart.addTag('rawParts','"F1","MF-MSMF050-2 500mA","L-EUL1812","L1812","INDUCTOR, European symbol","","","","","","","","",')
newPart.addTag('rawParts','"FRAME1","DNP","A3-FRAME","FRAME","","DNP","DNP","DNP","DNP","DNP","DNP","DNP","DNP",')
newPart.addTag('rawParts','"J3","USB Micro","USB-MICRO-LEGACY","CON2_USB_MICRO_B_AT","","","http://media.digikey.com/pdf/Data%20Sheets/FCI%20PDFs/10118193-0001LF_Webpage.PDF","http://www.digikey.it/product-detail/en/10118193-0001LF/609-4616-2-ND/2785388","609-4616-2-ND","FCI","10118193-0001LF","","USB Micro",')
newPart.addTag('rawParts','"J4","3x2M","PINHD-2X3","2X03","PIN HEADER","","","","","","","","",')
newPart.addTag('rawParts','"J5","HEAD17-NOSS","HEAD17-NOSS","HEAD17-NOSS","","","","","","","","","",')
newPart.addTag('rawParts','"J6","HEAD17-NOSS-1","HEAD17-NOSS-1","HEAD17-NOSS-1","","","","","","","","","",')
newPart.addTag('rawParts','"L","green","LEDCHIPLED_0805","CHIPLED_0805","LED","","","","","","","","",')
newPart.addTag('rawParts','"L2","MH2029-300Y","WE-CBF_0805","0805","SMD EMI Suppression Ferrite Beads","","","","","","","","",')
newPart.addTag('rawParts','"ON","blue","LEDCHIPLED_0805","CHIPLED_0805","LED","","","","","","","","",')
newPart.addTag('rawParts','"R1","10K","R-EU_R0402","R0402","RESISTOR, European symbol","","","","","","","","",')
newPart.addTag('rawParts','"R2","10K","R-EU_R0402","R0402","RESISTOR, European symbol","","","","","","","","",')
newPart.addTag('rawParts','"R4","10K","R-EU_R0402","R0402","RESISTOR, European symbol","","","","","","","","",')
newPart.addTag('rawParts','"R5","1K","R-EU_R0402","R0402","RESISTOR, European symbol","","","","","","","","",')
newPart.addTag('rawParts','"R6","1K","R-EU_R0402","R0402","RESISTOR, European symbol","","","","","","","","",')
newPart.addTag('rawParts','"R7","1K","R-EU_R0402","R0402","RESISTOR, European symbol","","","","","","","","",')
newPart.addTag('rawParts','"R8","1K","R-EU_R0402","R0402","RESISTOR, European symbol","","","","","","","","",')
newPart.addTag('rawParts','"R9","10K","R-EU_R0402","R0402","RESISTOR, European symbol","","","","","","","","",')
newPart.addTag('rawParts','"RESET","TS42","TS42","TS42","TS42","","","","","","","","",')
newPart.addTag('rawParts','"RP3","22R","4R-NCAY16","CAY16","Array Chip Resistor","","","","","","","","",')
newPart.addTag('rawParts','"RX","yellow","LEDCHIPLED_0805","CHIPLED_0805","LED","","","","","","","","",')
newPart.addTag('rawParts','"T1","FDN340P/PMV48XP","PMOSSOT23","SOT-23","MOS FET","","","","","","","","",')
newPart.addTag('rawParts','"T2","PMV48XP","PMOSSOT23","SOT-23","MOS FET","","","","","","","","",')
newPart.addTag('rawParts','"TX","yellow","LEDCHIPLED_0805","CHIPLED_0805","LED","","","","","","","","",')
newPart.addTag('rawParts','"U$37","DNP","FIDUCIAL-1.5MM","FD-1-1.5","Fiducial mount","","DNP","DNP","DNP","DNP","DNP","","DNP",')
newPart.addTag('rawParts','"U$53","DNP","FIDUCIAL-1.5MM","FD-1-1.5","Fiducial mount","","DNP","DNP","DNP","DNP","DNP","","DNP",')
newPart.addTag('rawParts','"U1","ATMEGA32U4-XUMU","ATMEGA32U4-XUMU","QFN44ML7X7","","","","","","","","","",')
newPart.addTag('rawParts','"U2","NCP1117-5","LINEAR_MC33269ST","SOT223","Adjustable Output Low Dropout Voltage Regulator 800 mA","","","","","","","","",')
newPart.addTag('rawParts','"U4","LP2985-33DBVR","LP2985-XXDBVR33","SOT23-DBV","ULTRALOW-POWER 50-mA LOW-DROPOUT LINEAR REGULATORS","","","","","","","","",')
newPart.addTag('rawParts','"Y3","16MHz KX-7","CRYSTAL-3.2-2.5","CRYSTAL-3.2-2.5","","","","","","","","","",')
newPart.addTag('rawParts','"Z1","CG0603MLC-05E","VARISTORCN0603","CT/CN0603","VARISTOR","","","","","","","","",')
newPart.addTag('rawParts','"Z2","CG0603MLC-05E","VARISTORCN0603","CT/CN0603","VARISTOR","","","","","","","","",')