import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-3015-STAN-01")

newPart.addTag('oompParts','B1,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')
newPart.addTag('oompParts','B2,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')
newPart.addTag('oompParts','B3,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')
newPart.addTag('oompParts','B4,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')
newPart.addTag('oompParts','HEADER,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')