import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-10888-STAN-01")

newPart.addTag('rawParts','"C1","10uF","CAP_POL1206","EIA3216","Capacitor Polarized","",')
newPart.addTag('rawParts','"C2","0.1uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C3","0.22uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C4","4.7uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C5","2.2uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C6","2.2uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C7","470pF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C8","470pF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"JP1","LOGO-SFENW2","LOGO-SFENW2","SFE-NEW-WEB","Spark Fun Electronics PCB Logo","",')
newPart.addTag('rawParts','"JP2","","M04PTH","1X04","Header 4","",')
newPart.addTag('rawParts','"JP3","FIDUCIAL1X2","FIDUCIAL1X2","FIDUCIAL-1X2","Fiducial Alignment Points","",')
newPart.addTag('rawParts','"JP4","FIDUCIAL1X2","FIDUCIAL1X2","FIDUCIAL-1X2","Fiducial Alignment Points","",')
newPart.addTag('rawParts','"JP5","","M04PTH","1X04","Header 4","",')
newPart.addTag('rawParts','"JP6","LOGO-SFESK","LOGO-SFESK","SFE-LOGO-FLAME","Spark Fun Electronics PCB Logo","",')
newPart.addTag('rawParts','"Q1","MOSFET-N-CH","MOSFET-NCHANNELSMD","SOT23-3","","",')
newPart.addTag('rawParts','"Q2","MOSFET-N-CH","MOSFET-NCHANNELSMD","SOT23-3","","",')
newPart.addTag('rawParts','"R1","4.7k","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R2","4.7k","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R3","4.7k","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R4","4.7k","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"SJ1","","SOLDERJUMPER_2WAYPASTE2&3","SJ_3_PASTE2&3","Solder Jumper","",')
newPart.addTag('rawParts','"U$5","CREATIVE_COMMONS","CREATIVE_COMMONS","CREATIVE_COMMONS","","",')
newPart.addTag('rawParts','"U$8","OSHW-LOGOS","OSHW-LOGOS","OSHW-LOGO-S","Open Source Hardware Logo This logo indicates the piece of hardware it is found on incorporates a OSHW license and/or adheres to the definition of open source hardware found here: http://freedomdefined.org/OSHW","",')
newPart.addTag('rawParts','"U1","LSM303DLHSMD","LSM303DLHSMD","LGA28-5X5","","",')
newPart.addTag('rawParts','"U2","1.8V","V_REG_LDOSMD2","SC70","Voltage Regulator LDO","",')
newPart.addTag('rawParts','"U3","3.3V","V_REG_LDOSMD","SOT23-5","Voltage Regulator LDO","",')