import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-10730-STAN-01")

newPart.addTag('oompParts','BAT1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U$1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U$2,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U$3,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U$4,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U$6,UNMATCHED-UNMATCHED-X-UNMATCHED-01')