import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-5297-STAN-01")

newPart.addTag('rawParts','"C1","0.1uF","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C2","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C3","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C7","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C8","0.1uF","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C14","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C15","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C16","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C17","1uF","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"CONN1","STEMMA_I2C_QT","STEMMA_I2C_QT","JST_SH4","","",')
newPart.addTag('rawParts','"CONN4","STEMMA_I2C_QT","STEMMA_I2C_QT","JST_SH4","","",')
newPart.addTag('rawParts','"D1","GREEN","LED0603_NOOUTLINE","CHIPLED_0603_NOOUTLINE","LED","",')
newPart.addTag('rawParts','"D2","MBR120","DIODESOD-123","SOD-123","Diode","",')
newPart.addTag('rawParts','"D3","1N4148","DIODESOD-323","SOD-323","Diode","",')
newPart.addTag('rawParts','"D4","1N4148","DIODESOD-323","SOD-323","Diode","",')
newPart.addTag('rawParts','"D5","1N4148","DIODESOD-323","SOD-323","Diode","",')
newPart.addTag('rawParts','"FID3","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"FID4","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"IC5","APX803","AXP083-SAG","SOT23","","",')
newPart.addTag('rawParts','"JP2","","HEADER-1X876MIL","1X08_ROUND_76","PIN HEADER","",')
newPart.addTag('rawParts','"L1","10uH","INDUCTOR","INDUCTOR_1007","Inductors","",')
newPart.addTag('rawParts','"Q2","BSS138","MOSFET-N_DUAL","SOT363","Dual N-Channel MOSFET","",')
newPart.addTag('rawParts','"R1","10K","RESISTOR_0603_NOOUT","0603-NO","Resistors","",')
newPart.addTag('rawParts','"R2","10K","RESISTOR_4PACK","RESPACK_4X0603","Resistor Packs (4 resistors)","",')
newPart.addTag('rawParts','"R3","10K","RESISTOR_4PACK","RESPACK_4X0603","Resistor Packs (4 resistors)","",')
newPart.addTag('rawParts','"R6","100K","RESISTOR_0603_NOOUT","0603-NO","Resistors","",')
newPart.addTag('rawParts','"R7","10K","RESISTOR_0603_NOOUT","0603-NO","Resistors","",')
newPart.addTag('rawParts','"R9","390K","RESISTOR_0603_NOOUT","0603-NO","Resistors","",')
newPart.addTag('rawParts','"SJ1","","SOLDERJUMPERCLOSED","SOLDERJUMPER_CLOSEDWIRE","SMD Solder JUMPER","",')
newPart.addTag('rawParts','"SJ2","","SOLDERJUMPER","SOLDERJUMPER_ARROW_NOPASTE","SMD Solder JUMPER","EXCLUDE",')
newPart.addTag('rawParts','"SJ3","","SOLDERJUMPER","SOLDERJUMPER_ARROW_NOPASTE","SMD Solder JUMPER","EXCLUDE",')
newPart.addTag('rawParts','"U$1","MOUNTINGHOLE3.0THIN","MOUNTINGHOLE3.0THIN","MOUNTINGHOLE_3.0_PLATEDTHIN","Mounting Hole","EXCLUDE",')
newPart.addTag('rawParts','"U$17","MOUNTINGHOLE3.0THIN","MOUNTINGHOLE3.0THIN","MOUNTINGHOLE_3.0_PLATEDTHIN","Mounting Hole","EXCLUDE",')
newPart.addTag('rawParts','"U$19","MOUNTINGHOLE3.0THIN","MOUNTINGHOLE3.0THIN","MOUNTINGHOLE_3.0_PLATEDTHIN","Mounting Hole","EXCLUDE",')
newPart.addTag('rawParts','"U$21","MOUNTINGHOLE3.0THIN","MOUNTINGHOLE3.0THIN","MOUNTINGHOLE_3.0_PLATEDTHIN","Mounting Hole","EXCLUDE",')
newPart.addTag('rawParts','"U2","AP2112K-3.3","VREG_SOT23-5","SOT23-5","SOT23-5 Fixed Voltage Regulators","",')
newPart.addTag('rawParts','"U3","FAN5331SX","FAN5331","SOT23-5@1","FAN5331 - LED/OLED 20V Boost Converter","",')
newPart.addTag('rawParts','"X2","OLED_1.12_128X128_MONO","OLED_1.12_128X128_MONO","OLED_1.12IN_128X128MONO","","",')