import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-3964-STAN-01")

newPart.addTag('rawParts','"C1","0.1uF","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C2","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C3","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"FID1","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"FID2","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"JP2","","HEADER-1X5ROUND","1X05_ROUND","PIN HEADER","",')
newPart.addTag('rawParts','"Q2","2N7002D","MOSFET-N_DUAL","SOT363","Dual N-Channel MOSFET","",')
newPart.addTag('rawParts','"R3","10K","RESISTOR_4PACK","RESPACK_4X0603","Resistor Packs (4 resistors)","",')
newPart.addTag('rawParts','"U$3","MOUNTINGHOLE2.5","MOUNTINGHOLE2.5","MOUNTINGHOLE_2.5_PLATED","Mounting Hole","EXCLUDE",')
newPart.addTag('rawParts','"U$4","MOUNTINGHOLE2.5","MOUNTINGHOLE2.5","MOUNTINGHOLE_2.5_PLATED","Mounting Hole","EXCLUDE",')
newPart.addTag('rawParts','"U$12","VEML6075","VEML6075","VEML6075","UVA and UVB Light Sensor with I2C Interface","",')
newPart.addTag('rawParts','"U2","MIC5225-3.3","VREG_SOT23-5","SOT23-5","SOT23-5 Fixed Voltage Regulators","",')