import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-11561-STAN-01")

newPart.addTag('oompParts','C1,CAPX-UNMATCHED-X-UF100-01')
newPart.addTag('oompParts','C2,CAPX-UNMATCHED-X-UF220-01')
newPart.addTag('oompParts','C3,CAPX-UNMATCHED-X-NF100-01')
newPart.addTag('oompParts','IC1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','IC2,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','IC3,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','J1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','JP1,TERS-35D-L-PI02-01')
newPart.addTag('oompParts','JP2,TERS-35D-L-PI02-01')
newPart.addTag('oompParts','JP3,HEAD-I01-X-PI02-01')
newPart.addTag('oompParts','JP4,HEAD-I01-X-PI02-01')
newPart.addTag('oompParts','JP5,HEAD-I01-X-PI02-01')
newPart.addTag('oompParts','JP6,HEAD-I01-X-PI02-01')
newPart.addTag('oompParts','JP7,HEAD-I01-X-PI04-01')
newPart.addTag('oompParts','JP8,HEAD-I01-X-PI04-01')
newPart.addTag('oompParts','JP9,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','LED1,LEDS-UNMATCHED-G-STAN-01')
newPart.addTag('oompParts','LED2,LEDS-UNMATCHED-G-STAN-01')
newPart.addTag('oompParts','R1,RESE-UNMATCHED-X-O271-01')
newPart.addTag('oompParts','R2,RESE-UNMATCHED-X-O271-01')
newPart.addTag('oompParts','R3,RESE-UNMATCHED-X-O102-01')
newPart.addTag('oompParts','R4,RESE-UNMATCHED-X-O102-01')
newPart.addTag('oompParts','R5,RESE-UNMATCHED-X-O271-01')
newPart.addTag('oompParts','R6,RESE-UNMATCHED-X-O471-01')
newPart.addTag('oompParts','R7,RESE-UNMATCHED-X-O102-01')
newPart.addTag('oompParts','R8,RESE-UNMATCHED-X-O102-01')