import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-8245-STAN-01")

newPart.addTag('rawParts','C5,10uF,CAP_POL1206,EIA3216,Capacitor Polarized,,')
newPart.addTag('rawParts','C11,0.1uF,CAP0402,C0402,Capacitor,,')
newPart.addTag('rawParts','C14,0.1uF,CAP0402,C0402,Capacitor,,')
newPart.addTag('rawParts','F1,500mA-PTC,PTCSMD,PTC-1206,Resettable Fuse PTC,,')
newPart.addTag('rawParts','JP1,,M04PTH,1X04,Header 4,,')
newPart.addTag('rawParts','LED2,Red,LED0603,LED-0603,LEDs,,')
newPart.addTag('rawParts','LED3,Green,LED0603,LED-0603,LEDs,,')
newPart.addTag('rawParts','POWER,Red,LED0603,LED-0603,LEDs,,')
newPart.addTag('rawParts','R1,330,RESISTOR0402,C0402,Resistor,,')
newPart.addTag('rawParts','R2,1K,RESISTOR0402,C0402,Resistor,,')
newPart.addTag('rawParts','R3,1K,RESISTOR0402,C0402,Resistor,,')
newPart.addTag('rawParts','SJ1,SOLDERJUMPERNC2,SOLDERJUMPERNC2,SJ_2S,Solder Jumper,,')
newPart.addTag('rawParts','U$1,STAND-OFF,STAND-OFF,STAND-OFF,Stand Off,,')
newPart.addTag('rawParts','U$2,IPOD_CONNECTOR_FEMALE,IPOD_CONNECTOR_FEMALE,IPOD_FEMALE_CONNECTOR,iPod Female Connector,,')
newPart.addTag('rawParts','U$3,LOGO-SFENEW,LOGO-SFENEW,SFE-NEW-WEBLOGO,Spark Fun Electronics PCB Logo,,')
newPart.addTag('rawParts','U$4,FIDUCIAL1X2,FIDUCIAL1X2,FIDUCIAL-1X2,Fiducial Alignment Points,,')
newPart.addTag('rawParts','U$5,STAND-OFF,STAND-OFF,STAND-OFF,Stand Off,,')
newPart.addTag('rawParts','U$6,STAND-OFF,STAND-OFF,STAND-OFF,Stand Off,,')
newPart.addTag('rawParts','U$7,STAND-OFF,STAND-OFF,STAND-OFF,Stand Off,,')
newPart.addTag('rawParts','U$8,FIDUCIAL1X2,FIDUCIAL1X2,FIDUCIAL-1X2,Fiducial Alignment Points,,')
newPart.addTag('rawParts','U$9,CREATIVE_COMMONS,CREATIVE_COMMONS,CREATIVE_COMMONS,,,')
newPart.addTag('rawParts','U1,FT232RL-BASICSSOP,FT232RL-BASICSSOP,SSOP28DB,USB UART,,')
newPart.addTag('rawParts','X1,USBSMD,USBSMD,USB-MINIB,USB Connectors,,')