import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-11257-STAN-01")

newPart.addTag('oompParts','C1,CAPC-0402-X-NF100-V10')
newPart.addTag('oompParts','C2,CAPC-0402-X-NF100-V10')
newPart.addTag('oompParts','C3,CAPC-0402-X-NF100-V10')
newPart.addTag('oompParts','C4,CAPT-3216-X-UF10-V10')
newPart.addTag('oompParts','C5,CAPX-3528-X-UF68-01')
newPart.addTag('oompParts','C10,CAPC-0402-X-NF100-V10')
newPart.addTag('oompParts','D1,DIOD-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','IC1,UNMATCHED-SO235-X-UNMATCHED-01')
newPart.addTag('oompParts','JP1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','JP2,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','JP3,HEAD-I01-X-UNMATCHED-01')
newPart.addTag('oompParts','JP4,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','JP5,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','JP6,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','JP7,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','JP8,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','JP9,HEAD-I01-X-PI06-01')
newPart.addTag('oompParts','JP10,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','L1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','LED2,LEDS-UNMATCHED-R-STAN-01')
newPart.addTag('oompParts','LED3,LEDS-UNMATCHED-R-STAN-01')
newPart.addTag('oompParts','Q1,UNMATCHED-SO23-X-UNMATCHED-01')
newPart.addTag('oompParts','R1,RESE-UNMATCHED-X-O102-01')
newPart.addTag('oompParts','R2,RESE-0402-X-O103-01')
newPart.addTag('oompParts','R3,RESE-UNMATCHED-X-O102-01')
newPart.addTag('oompParts','R4,RESE-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','R5,RESE-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','R6,RESE-0402-X-O103-01')
newPart.addTag('oompParts','SG1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','TP1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U3,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U4,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','Y1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')