import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-11168-STAN-01")

newPart.addTag('rawParts','"$$U$1","CREATIVE_COMMONS","CREATIVE_COMMONS","CREATIVE_COMMONS","","",')
newPart.addTag('rawParts','"IC1","AVR-MEGA-PZIF_SOCKET","AVR-MEGA8-PZIF_SOCKET","DIL28-3-ZIF_SOCKET","MICROCONTROLLER","",')
newPart.addTag('rawParts','"J1","AVR_SPI_PRG_6PTH","AVR_SPI_PRG_6PTH","2X3","AVR ISP 6 Pin","",')
newPart.addTag('rawParts','"JP5","FIDUCIAL1X2.5","FIDUCIAL1X2.5","FIDUCIAL-1X2.5","Fiducial Alignment Points","",')
newPart.addTag('rawParts','"JP6","FIDUCIAL1X2.5","FIDUCIAL1X2.5","FIDUCIAL-1X2.5","Fiducial Alignment Points","",')
newPart.addTag('rawParts','"LED1","GREEN","LED0603","LED-0603","LEDs","",')
newPart.addTag('rawParts','"LED2","GREEN","LED0603","LED-0603","LEDs","",')
newPart.addTag('rawParts','"LED3","RED","LED0603","LED-0603","LEDs","",')
newPart.addTag('rawParts','"LED4","BLUE","LED0603","LED-0603","LEDs","",')
newPart.addTag('rawParts','"Q1","8/16/20MHz","RESONATORSMD","RESONATOR-SMD","Resonator","",')
newPart.addTag('rawParts','"R1","330","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R2","330","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R3","10K","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R4","330","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R5","330","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R6","100","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"S2","","SWITCH-SPSTSMD","AYZ0202","SPST Switch","",')
newPart.addTag('rawParts','"S3","Reset","SWITCH-MOMENTARY-2SMD","TACTILE_SWITCH_SMD","","",')
newPart.addTag('rawParts','"SJ1","SOLDERJUMPERNO","SOLDERJUMPERNO","SJ_2S-NO","Solder Jumper","",')
newPart.addTag('rawParts','"U$4","OSHW-LOGOS","OSHW-LOGOS","OSHW-LOGO-S","Open Source Hardware Logo This logo indicates the piece of hardware it is found on incorporates a OSHW license and/or adheres to the definition of open source hardware found here: http://freedomdefined.org/OSHW","",')
newPart.addTag('rawParts','"U$9","AVR_SPI_PROG","AVR_SPI_PROG","AVR_ICSP","AVR ICSP Header","",')
newPart.addTag('rawParts','"U1","ARDUINO_SHIELDLABEL","ARDUINO_SHIELDLABEL","DUEMILANOVE_SHIELD","","",')