import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-1377-STAN-01")

newPart.addTag('oompParts','JP1,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')
newPart.addTag('oompParts','JP2,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')
newPart.addTag('oompParts','U$1,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')
newPart.addTag('oompParts','U$2,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')