import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-17725-STAN-01")

newPart.addTag('oompParts','C3,CAPC-0603-X-NF100-V50')
newPart.addTag('oompParts','CTS,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','D1,LEDS-0603-L-STAN-01')
newPart.addTag('oompParts','DCD,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','DSR,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','DTR,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','J1,HEAD-I01-X-PI01-01')
newPart.addTag('oompParts','J2,HEAD-I01-X-PI01-01')
newPart.addTag('oompParts','J5,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','LOGO2,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','R1,RESE-0603-X-O102-01')
newPart.addTag('oompParts','RI,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','RTS,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','RXI,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','TXO,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U2,UNMATCHED-UNMATCHED-X-UNMATCHED-01')