import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-10936-STAN-01")

newPart.addTag('oompParts','C1,CAPX-UNMATCHED-X-UF1D-01')
newPart.addTag('oompParts','C2,CAPX-UNMATCHED-X-UF1D-01')
newPart.addTag('oompParts','C3,CAPX-UNMATCHED-X-UF1D-01')
newPart.addTag('oompParts','C4,CAPX-UNMATCHED-X-UF1D-01')
newPart.addTag('oompParts','C5,CAPX-UNMATCHED-X-UF10-01')
newPart.addTag('oompParts','D1,LEDS-UNMATCHED-G-STAN-01')
newPart.addTag('oompParts','D2,LEDS-UNMATCHED-G-STAN-01')
newPart.addTag('oompParts','D3,LEDS-UNMATCHED-G-STAN-01')
newPart.addTag('oompParts','IC1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','IC2,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','IC3,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','IC4,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','JP1,HEAD-I01-X-PI06-01')
newPart.addTag('oompParts','JP2,HEAD-I01-X-PI06-01')
newPart.addTag('oompParts','JP3,HEAD-I01-X-PI02-01')
newPart.addTag('oompParts','R1,RESE-UNMATCHED-X-O102-01')
newPart.addTag('oompParts','R2,RESE-UNMATCHED-X-O331-01')
newPart.addTag('oompParts','R3,RESE-UNMATCHED-X-O331-01')
newPart.addTag('oompParts','R4,RESE-UNMATCHED-X-O331-01')
newPart.addTag('oompParts','R5,RESE-UNMATCHED-X-O331-01')
newPart.addTag('oompParts','R6,RESE-UNMATCHED-X-O331-01')
newPart.addTag('oompParts','R7,RESE-UNMATCHED-X-O331-01')