import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-11373-STAN-01")

newPart.addTag('rawParts','"C1","10uF","CAP_POL1206","EIA3216","Capacitor Polarized","",')
newPart.addTag('rawParts','"C2","0.1uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C3","10uF","CAP_POL1206","EIA3216","Capacitor Polarized","",')
newPart.addTag('rawParts','"JP2","M11PTH","M11PTH","1X11","Header 11","",')
newPart.addTag('rawParts','"JP3","M11PTH","M11PTH","1X11","Header 11","",')
newPart.addTag('rawParts','"JP4","","ARDUINO_SERIAL_PROGRAMPTH","1X06","","",')
newPart.addTag('rawParts','"LED1","Red","LED0603","LED-0603","LEDs","",')
newPart.addTag('rawParts','"LED2","Red","LED0603","LED-0603","LEDs","",')
newPart.addTag('rawParts','"LED3","Green","LED0603","LED-0603","LEDs","",')
newPart.addTag('rawParts','"LED4","Green","LED0603","LED-0603","LEDs","",')
newPart.addTag('rawParts','"Q1","MOSFET-NCHANNELSMD","MOSFET-NCHANNELSMD","SOT23-3","Generic NMOS footprint","",')
newPart.addTag('rawParts','"Q2","MOSFET-NCHANNELSMD","MOSFET-NCHANNELSMD","SOT23-3","Generic NMOS footprint","",')
newPart.addTag('rawParts','"R1","1k","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R3","1k","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R4","1k","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R5","1k","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R6","1k","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R7","1k","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R8","1k","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R11","1k","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"SJ1","SOLDERJUMPERNO","SOLDERJUMPERNO","SJ_2S-NO","Solder Jumper","",')
newPart.addTag('rawParts','"U$1","LOGO-SFESK","LOGO-SFESK","SFE-LOGO-FLAME","Spark Fun Electronics PCB Logo","",')
newPart.addTag('rawParts','"U$3","OSHW-LOGOS","OSHW-LOGOS","OSHW-LOGO-S","Open Source Hardware Logo This logo indicates the piece of hardware it is found on incorporates a OSHW license and/or adheres to the definition of open source hardware found here: http://freedomdefined.org/OSHW","",')
newPart.addTag('rawParts','"U$4","LOGO-SFENEW","LOGO-SFENEW","SFE-NEW-WEBLOGO","Spark Fun Electronics PCB Logo","",')
newPart.addTag('rawParts','"U$5","STAND-OFF","STAND-OFF","STAND-OFF","Stand Off","",')
newPart.addTag('rawParts','"U$7","FIDUCIAL1X2","FIDUCIAL1X2","FIDUCIAL-1X2","Fiducial Alignment Points","",')
newPart.addTag('rawParts','"U$8","CREATIVE_COMMONS","CREATIVE_COMMONS","CREATIVE_COMMONS","Creative Commons License summary","",')
newPart.addTag('rawParts','"U$9","STAND-OFF","STAND-OFF","STAND-OFF","Stand Off","",')
newPart.addTag('rawParts','"U$10","STAND-OFF","STAND-OFF","STAND-OFF","Stand Off","",')
newPart.addTag('rawParts','"U$11","STAND-OFF","STAND-OFF","STAND-OFF","Stand Off","",')
newPart.addTag('rawParts','"U$16","FIDUCIAL1X2","FIDUCIAL1X2","FIDUCIAL-1X2","Fiducial Alignment Points","",')
newPart.addTag('rawParts','"U2","XBEE-1B3","XBEE-1B3","XBEE-SMD","","",')
newPart.addTag('rawParts','"U3","V_REG_LDOSMD","V_REG_LDOSMD","SOT23-5","Voltage Regulator LDO","",')