import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-11187-STAN-01")

newPart.addTag('rawParts','"JP1","","M07","1X07","Header 7","",')
newPart.addTag('rawParts','"JP2","FIDUCIALUFIDUCIAL","FIDUCIALUFIDUCIAL","MICRO-FIDUCIAL","Fiducial Alignment Points","",')
newPart.addTag('rawParts','"JP3","STAND-OFF","STAND-OFF","STAND-OFF","Stand Off","",')
newPart.addTag('rawParts','"JP4","STAND-OFF","STAND-OFF","STAND-OFF","Stand Off","",')
newPart.addTag('rawParts','"JP5","STAND-OFF","STAND-OFF","STAND-OFF","Stand Off","",')
newPart.addTag('rawParts','"JP6","STAND-OFF","STAND-OFF","STAND-OFF","Stand Off","",')
newPart.addTag('rawParts','"JP7","FIDUCIALUFIDUCIAL","FIDUCIALUFIDUCIAL","MICRO-FIDUCIAL","Fiducial Alignment Points","",')
newPart.addTag('rawParts','"JP9","LOGO-SFESK","LOGO-SFESK","SFE-LOGO-FLAME","Spark Fun Electronics PCB Logo","",')
newPart.addTag('rawParts','"JP10","LOGO-SFENW2","LOGO-SFENW2","SFE-NEW-WEB","Spark Fun Electronics PCB Logo","",')
newPart.addTag('rawParts','"R1","10K","RESISTOR0603-RES","0603-RES","Resistor","",')
newPart.addTag('rawParts','"R2","10K","RESISTOR0603-RES","0603-RES","Resistor","",')
newPart.addTag('rawParts','"R3","10K","RESISTOR0603-RES","0603-RES","Resistor","",')
newPart.addTag('rawParts','"R4","10K","RESISTOR0603-RES","0603-RES","Resistor","",')
newPart.addTag('rawParts','"R5","10K","RESISTOR0603-RES","0603-RES","Resistor","",')
newPart.addTag('rawParts','"S1","5-WAY-TACTILE-SWITCH","JOYSTICK_MINI","JOYSTICK_MINI","Small 5-way tactile joystick, COM-10063","",')
newPart.addTag('rawParts','"U$1","OSHW-LOGOS","OSHW-LOGOS","OSHW-LOGO-S","Open Source Hardware Logo This logo indicates the piece of hardware it is found on incorporates a OSHW license and/or adheres to the definition of open source hardware found here: http://freedomdefined.org/OSHW","",')
newPart.addTag('rawParts','"U$2","CREATIVE_COMMONS","CREATIVE_COMMONS","CREATIVE_COMMONS","","",')