import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-2466-STAN-01")

newPart.addTag('rawParts','"AD","20609","HEADER-1X6","1X06_OVAL","PIN HEADER","","","","","",')
newPart.addTag('rawParts','"C1","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","",')
newPart.addTag('rawParts','"C2","0.1uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","",')
newPart.addTag('rawParts','"C3","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","",')
newPart.addTag('rawParts','"C4","0.1uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","",')
newPart.addTag('rawParts','"C5","0.1uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","",')
newPart.addTag('rawParts','"C6","0.1uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","",')
newPart.addTag('rawParts','"C7","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","",')
newPart.addTag('rawParts','"C9","0.1uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","",')
newPart.addTag('rawParts','"C10","0.1uF","CAP_CERAMIC0805_10MGAP","0805_10MGAP","Ceramic Capacitors","","","","","",')
newPart.addTag('rawParts','"C12","0.1uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","",')
newPart.addTag('rawParts','"C13","0.1uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","",')
newPart.addTag('rawParts','"C15","0.1uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","",')
newPart.addTag('rawParts','"D1","MBR120","DIODE-SCHOTTKYSOD-123","SOD-123","","","","","","",')
newPart.addTag('rawParts','"D2","1N4148","DIODESOD-323","SOD-323","Diode","","","","","",')
newPart.addTag('rawParts','"F2","500mA","PTC_1206NO","1206-NO","PTC (Resettable Fuse)","","","","","",')
newPart.addTag('rawParts','"FB1","FERRITE","FERRITE-0805NO","0805-NO","Ferrite Bead","","","","","",')
newPart.addTag('rawParts','"FB2","FERRITE","FERRITE-0805NO","0805-NO","Ferrite Bead","","","","","",')
newPart.addTag('rawParts','"FD1","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE","","","","",')
newPart.addTag('rawParts','"FD2","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE","","","","",')
newPart.addTag('rawParts','"FD3","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE","","","","",')
newPart.addTag('rawParts','"GROUND1","","SJ","SJ","SMD solder JUMPER","","","","","",')
newPart.addTag('rawParts','"ICSP","3x2 M","HEADER-2X3","2X03_ROUND_70MIL","PIN HEADER","","","","","",')
newPart.addTag('rawParts','"IOH","20611","HEADER-1X10","1X10_OVAL","PIN HEADER","","","","","",')
newPart.addTag('rawParts','"IOL","20610","HEADER-1X8","1X08_OVAL","PIN HEADER","","","","","",')
newPart.addTag('rawParts','"JP1","","HEADER-1X1ROUND","1X01_ROUND","PIN HEADER","","","","","",')
newPart.addTag('rawParts','"L","RED","LED0805_NOOUTLINE","CHIPLED_0805_NOOUTLINE","LED","","","","","",')
newPart.addTag('rawParts','"ON","GREEN","LED0805_NOOUTLINE","CHIPLED_0805_NOOUTLINE","LED","","","","","",')
newPart.addTag('rawParts','"PC1","47uF/25V","CAP_ELECTROLYTICPANASONIC_D","PANASONIC_D","Electrolytic Capacitors","","","","","",')
newPart.addTag('rawParts','"PC2","47uF+/6.3V+","CAP_ELECTROLYTICPANASONIC_D","PANASONIC_D","Electrolytic Capacitors","","","","","",')
newPart.addTag('rawParts','"POWER","20610","HEADER-1X8","1X08_OVAL","PIN HEADER","","","","","",')
newPart.addTag('rawParts','"R1","1K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","","","","","",')
newPart.addTag('rawParts','"R3","1K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","","","","","",')
newPart.addTag('rawParts','"R6","1K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","","","","","",')
newPart.addTag('rawParts','"R7","10K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","","","","","",')
newPart.addTag('rawParts','"R8","10K","RESISTOR_0805MP","_0805MP","Resistors","","","","","",')
newPart.addTag('rawParts','"R9","1K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","","","","","",')
newPart.addTag('rawParts','"R10","1K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","","","","","",')
newPart.addTag('rawParts','"R11","1K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","","","","","",')
newPart.addTag('rawParts','"R12","1K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","","","","","",')
newPart.addTag('rawParts','"R13","10K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","","","","","",')
newPart.addTag('rawParts','"R14","10K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","","","","","",')
newPart.addTag('rawParts','"R15","10K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","","","","","",')
newPart.addTag('rawParts','"R16","10K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","","","","","",')
newPart.addTag('rawParts','"RESET","6mm","SWITCH_TACT_SMT","EVQ-Q2","SMT Tact Switches","","","","","",')
newPart.addTag('rawParts','"RESET-EN","","SOLDERJUMPER_CLOSED","SOLDERJUMPER_CLOSEDWIRE","Solder Jumper - Closed","","","","","",')
newPart.addTag('rawParts','"RXLED","YELLOW","LED0805_NOOUTLINE","CHIPLED_0805_NOOUTLINE","LED","","","","","",')
newPart.addTag('rawParts','"SW2","","SWITCH_SPDT","SPDT_SMT_SSSS811101","Switch - SPDT","","","","","",')
newPart.addTag('rawParts','"T1","DMP3098L","PMOSSOT23","SOT-23","MOS FET","","","","unknown","unknown",')
newPart.addTag('rawParts','"T2","DMP3098L","PMOSSOT23","SOT-23","MOS FET","","","","unknown","unknown",')
newPart.addTag('rawParts','"TXLED","YELLOW","LED0805_NOOUTLINE","CHIPLED_0805_NOOUTLINE","LED","","","","","",')
newPart.addTag('rawParts','"U1","NCP1117ST50T3G","LM1117SOT223-REFLOW","SOT223-R","LM1117 Voltage Regulator","","","","","",')
newPart.addTag('rawParts','"U3","CP2104","CP2104","QFN24_4MM_SMSC","CP2104 - USB to UART Bridge","","","","","",')
newPart.addTag('rawParts','"U4","AP2112-3.3","VREG_SOT23-5","SOT23-5","SOT23-5 Fixed Voltage Regulators","","","","","",')
newPart.addTag('rawParts','"U5","LMV358IDGKR","LMV358MMX","MSOP08","Dual General Purpose, Low Voltage, Rail-to-Rail Output Operational Amplifiers","","","","","",')
newPart.addTag('rawParts','"VSELECT","","SOLDERJUMPER_2WAY","SOLDERJUMPER_2WAY_OPEN_NOPASTE","2-Way Solder Jumper","","","","","",')
newPart.addTag('rawParts','"X2","","DCBARRELPTH","DCJACK_2MM_PTH","DC Barrel Jack","","","","","",')
newPart.addTag('rawParts','"X3","20329","USB_W_SHIELD_V2","4UCONN_20329_V2","","","","","","",')
newPart.addTag('rawParts','"Y2","CSTCE16M0V53-R0 16MHZ","RESONATORMU","RESONATOR","","","","","","",')
newPart.addTag('rawParts','"ZU4","ATMEGA328P-AU","ATMEGA328P-AU","TQFP32-08","MICROCONTROLLER","","","","","",')