import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-11083-STAN-01")

newPart.addTag('rawParts','"C1","0.1uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C2","22nF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C3","22pF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C4","22pF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C5","4.7pF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C6","1uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"C7","1uF","CAP0402-CAP","0402-CAP","Capacitor","",')
newPart.addTag('rawParts','"JP1","M10"","M10"","1X10","Header 10","",')
newPart.addTag('rawParts','"JP2","LOGO-SFENW2","LOGO-SFENW2","SFE-NEW-WEB","Spark Fun Electronics PCB Logo","",')
newPart.addTag('rawParts','"JP3","LOGO-SFESK","LOGO-SFESK","SFE-LOGO-FLAME","Spark Fun Electronics PCB Logo","",')
newPart.addTag('rawParts','"JP4","FIDUCIALUFIDUCIAL","FIDUCIALUFIDUCIAL","MICRO-FIDUCIAL","Fiducial Alignment Points","",')
newPart.addTag('rawParts','"JP5","M01PTH","M01PTH","1X01","Header 1","",')
newPart.addTag('rawParts','"JP6","FIDUCIALUFIDUCIAL","FIDUCIALUFIDUCIAL","MICRO-FIDUCIAL","Fiducial Alignment Points","",')
newPart.addTag('rawParts','"L1","ferrite","INDUCTOR0402","C0402","Inductors","75 Ohm",')
newPart.addTag('rawParts','"R1","10k","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R2","10k","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R3","4.7k","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R8","4.7k","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R9","330","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R10","330","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R11","330","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"R12","330","RESISTOR0402-RES","0402-RES","Resistor","",')
newPart.addTag('rawParts','"U$1","CREATIVE_COMMONS","CREATIVE_COMMONS","CREATIVE_COMMONS","Creative Commons License summary","",')
newPart.addTag('rawParts','"U$3","OSHW-LOGOS","OSHW-LOGOS","OSHW-LOGO-S","Open Source Hardware Logo This logo indicates the piece of hardware it is found on incorporates a OSHW license and/or adheres to the definition of open source hardware found here: http://freedomdefined.org/OSHW","",')
newPart.addTag('rawParts','"U1","SI4703","SPARKFUN_SI470X","SPARKFUN_SI470X","Description: This is a powerful FM receiver IC. Tested with Si4703. You really only need SEN, RST, SCLK, and SDIO to get a full FM radio working. Antenna comes from headphone jack. See breakout board on SparkFun website for more information.","",')
newPart.addTag('rawParts','"Y1","32.768kHz","CRYSTAL32-SMD","CRYSTAL-32KHZ-SMD","Crystals","",')