import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-12670-STAN-01")

newPart.addTag('rawParts','"C1","0.1uF","CAP0603-CAP","0603-CAP","Capacitor","",')
newPart.addTag('rawParts','"C2","0.1uF","CAP0603-CAP","0603-CAP","Capacitor","",')
newPart.addTag('rawParts','"C3","0.1uF","CAP0603-CAP","0603-CAP","Capacitor","",')
newPart.addTag('rawParts','"C4","1uF","CAP0603-CAP","0603-CAP","Capacitor","",')
newPart.addTag('rawParts','"C5","0.1uF","CAP0603-CAP","0603-CAP","Capacitor","",')
newPart.addTag('rawParts','"FID1","FIDUCIAL1X2","FIDUCIAL1X2","FIDUCIAL-1X2","Fiducial Alignment Points","",')
newPart.addTag('rawParts','"FID2","FIDUCIAL1X2","FIDUCIAL1X2","FIDUCIAL-1X2","Fiducial Alignment Points","",')
newPart.addTag('rawParts','"FRAME2","FRAME-LETTER","FRAME-LETTER","CREATIVE_COMMONS","Schematic Frame","",')
newPart.addTag('rawParts','"JP1","breakout","M05PTH","1X05","Header 5","",')
newPart.addTag('rawParts','"JP2","STAND-OFF","STAND-OFF","STAND-OFF","Stand Off","",')
newPart.addTag('rawParts','"JP3","STAND-OFF","STAND-OFF","STAND-OFF","Stand Off","",')
newPart.addTag('rawParts','"JP7","LOGO-SFESK","LOGO-SFESK","SFE-LOGO-FLAME","Spark Fun Electronics PCB Logo","",')
newPart.addTag('rawParts','"LOGO1","OSHW-LOGOS","OSHW-LOGOS","OSHW-LOGO-S","Open Source Hardware Logo This logo indicates the piece of hardware it is found on incorporates a OSHW license and/or adheres to the definition of open source hardware found here: http://freedomdefined.org/OSHW","",')
newPart.addTag('rawParts','"R1","4.7k","RESISTOR0603-RES","0603-RES","Resistor","",')
newPart.addTag('rawParts','"R2","4.7k","RESISTOR0603-RES","0603-RES","Resistor","",')
newPart.addTag('rawParts','"SJ1","","SOLDERJUMPER_2WAYPASTE1&2&3","SJ_3_PASTE1&2&3","Solder Jumper","",')
newPart.addTag('rawParts','"U1","MAG31101:1","MAG31101:1","DFN-10-W","3-axis digital (I2C) magnetometer","",')