import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-163-STAN-01")

newPart.addTag('oompParts','C1,CAPC-0805-X-UNMATCHED-01')
newPart.addTag('oompParts','C2,CAPC-0805-X-UNMATCHED-01')
newPart.addTag('oompParts','C3,CAPC-0805-X-UNMATCHED-01')
newPart.addTag('oompParts','C4,CAPC-0805-X-UNMATCHED-01')
newPart.addTag('oompParts','C5,CAPC-0805-X-UNMATCHED-01')
newPart.addTag('oompParts','JP2,HEAD-I01-X-PI07-01')
newPart.addTag('oompParts','U$2,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U$3,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U$17,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U$18,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U2,UNMATCHED-SO235-X-UNMATCHED-01')