import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-14010-STAN-01")

newPart.addTag('oompParts','D1,LEDS-1206-G-STAN-01')
newPart.addTag('oompParts','D2,LEDS-1206-G-STAN-01')
newPart.addTag('oompParts','D3,LEDS-1206-G-STAN-01')
newPart.addTag('oompParts','D4,LEDS-1206-G-STAN-01')
newPart.addTag('oompParts','D5,LEDS-1206-G-STAN-01')
newPart.addTag('oompParts','LED+1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','LED+2,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','LED+3,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','LED+4,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','LED+5,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','LED-1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','LED-2,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','LED-3,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','LED-4,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','LED-5,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','R1,RESE-0603-X-O151-01')
newPart.addTag('oompParts','R2,RESE-0603-X-O151-01')
newPart.addTag('oompParts','R3,RESE-0603-X-O151-01')
newPart.addTag('oompParts','R4,RESE-0603-X-O151-01')
newPart.addTag('oompParts','R5,RESE-0603-X-O151-01')
newPart.addTag('oompParts','U$6,UNMATCHED-UNMATCHED-X-UNMATCHED-01')