import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-1535-STAN-01")

newPart.addTag('rawParts','"C1","10uF","C-USC0805","C0805","CAPACITOR, American symbol","",')
newPart.addTag('rawParts','"C4","10uF","C-USC0805","C0805","CAPACITOR, American symbol","",')
newPart.addTag('rawParts','"D1","1N4148","DIODESOD-323","SOD-323","Diode","",')
newPart.addTag('rawParts','"FID1","FIDUCIAL""","FIDUCIAL""","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"FID2","FIDUCIAL""","FIDUCIAL""","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"FID3","FIDUCIAL""","FIDUCIAL""","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"JP1","","PINHD-1X12-CB","1X12-CB","PIN HEADER","",')
newPart.addTag('rawParts','"JP2","","PINHD-1X12-CB","1X12-CB","PIN HEADER","",')
newPart.addTag('rawParts','"JP3","","PINHD-1X6B","1X06-BIG","PIN HEADER","",')
newPart.addTag('rawParts','"LED1","RED","LED0805_NOOUTLINE","CHIPLED_0805_NOOUTLINE","LED","",')
newPart.addTag('rawParts','"LED2","GREEN","LED0805_NOOUTLINE","CHIPLED_0805_NOOUTLINE","LED","",')
newPart.addTag('rawParts','"R1","10K","R-US_R0805","R0805","RESISTOR, American symbol","",')
newPart.addTag('rawParts','"R2","1K","R-US_R0805","R0805","RESISTOR, American symbol","",')
newPart.addTag('rawParts','"R3","1K","R-US_R0805","R0805","RESISTOR, American symbol","",')
newPart.addTag('rawParts','"R4","10K","R-US_R0805","R0805","RESISTOR, American symbol","",')
newPart.addTag('rawParts','"R5","2.2K","R-US_R0805","R0805","RESISTOR, American symbol","",')
newPart.addTag('rawParts','"SW1","SPST_TACT-KMR2","SPST_TACT-KMR2","KMR2","SMT 6mm switch, EVQQ2 series","",')
newPart.addTag('rawParts','"U1","BlueFruit","BLUETOOTH_MODULE","BLUETOOTH_MODULE","BLUETOOTH MODULE","",')
newPart.addTag('rawParts','"U2","MIC5225","VREG_SOT23-5","SOT23-5","SOT23-5 Fixed Voltage Regulators","",')