import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-12918-STAN-01")

newPart.addTag('rawParts','"C1","0.1uF","CAP0603-CAP","0603-CAP","Capacitor","","","","",')
newPart.addTag('rawParts','"FID1","FIDUCIAL1X2","FIDUCIAL1X2","FIDUCIAL-1X2","Fiducial Alignment Points","","","","",')
newPart.addTag('rawParts','"FID2","FIDUCIAL1X2","FIDUCIAL1X2","FIDUCIAL-1X2","Fiducial Alignment Points","","","","",')
newPart.addTag('rawParts','"FRAME2","","FRAME-LETTER","CREATIVE_COMMONS","Schematic Frame","NAME","","","v01",')
newPart.addTag('rawParts','"GND","LOGO-SFESK","LOGO-SFESK","SFE-LOGO-FLAME","Spark Fun Electronics PCB Logo","","","","",')
newPart.addTag('rawParts','"JP5","","M04PTH","1X04","Header 4","","","","",')
newPart.addTag('rawParts','"JP6","M02PTH","M02PTH","1X02","Standard 2-pin 0.1" header. Use with","","","","",')
newPart.addTag('rawParts','"LOGO1","OSHW-LOGOS","OSHW-LOGOS","OSHW-LOGO-S","Open Source Hardware Logo This logo indicates the piece of hardware it is found on incorporates a OSHW license and/or adheres to the definition of open source hardware found here: http://freedomdefined.org/OSHW","","","","",')
newPart.addTag('rawParts','"R1","4.7k","RESISTOR0603-RES","0603-RES","Resistor","","","","",')
newPart.addTag('rawParts','"R2","4.7k","RESISTOR0603-RES","0603-RES","Resistor","","","","",')
newPart.addTag('rawParts','"R3","10k","RESISTOR0603-RES","0603-RES","Resistor","","","","",')
newPart.addTag('rawParts','"SJ1","","JUMPER-PAD-3-NC_BY_TRACE","PAD-JUMPER-3-3OF3_NC_BY_TRACE_YES_SILK_FULL_BOX","","","","","",')
newPart.addTag('rawParts','"SJ2","JUMPER-PAD-3-2OF3_NC_BY_PASTE","JUMPER-PAD-3-2OF3_NC_BY_PASTE","PAD-JUMPER-3-2OF3_NC_BY_PASTE_YES_SILK_FULL_BOX","","","","","",')
newPart.addTag('rawParts','"STANDOFF1","STAND-OFF","STAND-OFF","STAND-OFF","#4 Stand Off","","","","",')
newPart.addTag('rawParts','"STANDOFF2","STAND-OFF","STAND-OFF","STAND-OFF","#4 Stand Off","","","","",')
newPart.addTag('rawParts','"U1","MCP4725","MCP4725SOT-23","SOT23-6","Microchip 12-bit I2C DAC, SOT23-6","","IC-08886","MCP4725","",')