import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-12037-STAN-01")

newPart.addTag('rawParts','BAT1,AA,BATTERYAA-KIT,BATTERY-AA-KIT,Battery Holders,BATT-08316,')
newPart.addTag('rawParts','BAT2,AA,BATTERYAA-KIT,BATTERY-AA-KIT,Battery Holders,BATT-08316,')
newPart.addTag('rawParts','C1,0.1uF,0.1UF-50V-20%(PTH)KIT-EZ,CAP-PTH-SMALL-KIT,CAP-08370,CAP-08370,')
newPart.addTag('rawParts','C2,0.1uF,0.1UF-50V-20%(PTH)KIT-EZ,CAP-PTH-SMALL-KIT,CAP-08370,CAP-08370,')
newPart.addTag('rawParts','FRAME1,FRAME-LETTER,FRAME-LETTER,CREATIVE_COMMONS,Schematic Frame,,')
newPart.addTag('rawParts','JP1,Serial,M06-SFENOSILK,1X06-NOSILK,Header 6,,')
newPart.addTag('rawParts','JP2,STAND-OFF,STAND-OFF,STAND-OFF,Stand Off,,')
newPart.addTag('rawParts','JP3,,AVR_SPI_PRG_6NS,2X3-NS,AVR ISP 6 Pin,,')
newPart.addTag('rawParts','JP4,,JUMPER-3SMD,SJ_3,,,')
newPart.addTag('rawParts','JP5,STAND-OFF,STAND-OFF,STAND-OFF,Stand Off,,')
newPart.addTag('rawParts','JP6,STAND-OFF,STAND-OFF,STAND-OFF,Stand Off,,')
newPart.addTag('rawParts','JP7,STAND-OFF,STAND-OFF,STAND-OFF,Stand Off,,')
newPart.addTag('rawParts','JP8,,JUMPER-3SMD,SJ_3,,,')
newPart.addTag('rawParts','JP9,,JUMPER-3SMD,SJ_3,,,')
newPart.addTag('rawParts','JP10,,JUMPER-3SMD,SJ_3,,,')
newPart.addTag('rawParts','JP11,,JUMPER-3SMD,SJ_3,,,')
newPart.addTag('rawParts','JP12,,JUMPER-3SMD,SJ_3,,,')
newPart.addTag('rawParts','JP13,,JUMPER-3SMD,SJ_3,,,')
newPart.addTag('rawParts','JP14,,JUMPER-3SMD,SJ_3,,,')
newPart.addTag('rawParts','LOGO1,LOGO-SFENEW,LOGO-SFENEW,SFE-NEW-WEBLOGO,Spark Fun Electronics PCB Logo,,')
newPart.addTag('rawParts','LOGO2,LOGO-SFENEW,LOGO-SFENEW,SFE-NEW-WEBLOGO,Spark Fun Electronics PCB Logo,,')
newPart.addTag('rawParts','R1,10K,10KOHM1/6W5%(PTH)KIT,AXIAL-0.3-KIT,RES-08375,RES-08375,')
newPart.addTag('rawParts','S1,Power,SWITCH-SPDTKIT,SWITCH-SPDT_KIT,SPDT Switch,SWCH-08261,')
newPart.addTag('rawParts','S2,,SWITCH-SPDTKIT,SWITCH-SPDT_KIT,SPDT Switch,SWCH-08261,')
newPart.addTag('rawParts','S3,,SWITCH-MOMENTARY-LEDEZ,TACTILE-PTH-LED-12MM-EZ,EZ is for Kits. There is no tStop (covering up the top side of the pads with mask). This helps the beginner see which side they should be soldering too.,,')
newPart.addTag('rawParts','S4,,SWITCH-MOMENTARY-LEDEZ,TACTILE-PTH-LED-12MM-EZ,EZ is for Kits. There is no tStop (covering up the top side of the pads with mask). This helps the beginner see which side they should be soldering too.,,')
newPart.addTag('rawParts','S5,,SWITCH-MOMENTARY-LEDEZ,TACTILE-PTH-LED-12MM-EZ,EZ is for Kits. There is no tStop (covering up the top side of the pads with mask). This helps the beginner see which side they should be soldering too.,,')
newPart.addTag('rawParts','S6,,SWITCH-MOMENTARY-LEDEZ,TACTILE-PTH-LED-12MM-EZ,EZ is for Kits. There is no tStop (covering up the top side of the pads with mask). This helps the beginner see which side they should be soldering too.,,')
newPart.addTag('rawParts','SG1,BUZZER,BUZZERPTH-KIT,BUZZER-12MM-KIT,Buzzer 12mm,COMP-08253,')
newPart.addTag('rawParts','U$1,7-SEGMENT-DISPLAY-1-REDEZ,7-SEGMENT-DISPLAY-1-REDEZ,7-SEGMENT-1PTH-EZ,7-Segment Display 1 Red (COM-08546),,')
newPart.addTag('rawParts','U$2,OSHW-LOGOL,OSHW-LOGOL,OSHW-LOGO-L,Open Source Hardware Logo This logo indicates the piece of hardware it is found on incorporates a OSHW license and/or adheres to the definition of open source hardware found here: http://freedomdefined.org/OSHW,,')
newPart.addTag('rawParts','U$3,OSHW-LOGOS,OSHW-LOGOS,OSHW-LOGO-S,Open Source Hardware Logo This logo indicates the piece of hardware it is found on incorporates a OSHW license and/or adheres to the definition of open source hardware found here: http://freedomdefined.org/OSHW,,')
newPart.addTag('rawParts','U$6,7-SEGMENT-DISPLAY-1-REDEZ,7-SEGMENT-DISPLAY-1-REDEZ,7-SEGMENT-1PTH-EZ,7-Segment Display 1 Red (COM-08546),,')
newPart.addTag('rawParts','U$7,AVR-MEGA8-P-KEYED-14,AVR-MEGA8-P-KEYED-14,DIL28-3_KEYED-14,,,')