import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-3422-STAN-01")

newPart.addTag('rawParts','"B0","CON_JST_XH_2PIN-SM4","CON_JST_XH_2PIN-SM4","JST-XH-2-SM4","","","","","","",')
newPart.addTag('rawParts','"B1","CON_JST_XH_2PIN-SM4","CON_JST_XH_2PIN-SM4","JST-XH-2-SM4","","","","","","",')
newPart.addTag('rawParts','"B2","CON_JST_XH_2PIN-SM4","CON_JST_XH_2PIN-SM4","JST-XH-2-SM4","","","","","","",')
newPart.addTag('rawParts','"B3","CON_JST_XH_2PIN-SM4","CON_JST_XH_2PIN-SM4","JST-XH-2-SM4","","","","","","",')
newPart.addTag('rawParts','"B4","CON_JST_XH_2PIN-SM4","CON_JST_XH_2PIN-SM4","JST-XH-2-SM4","","","","","","",')
newPart.addTag('rawParts','"B5","CON_JST_XH_2PIN-SM4","CON_JST_XH_2PIN-SM4","JST-XH-2-SM4","","","","","","",')
newPart.addTag('rawParts','"C1","0.1uF","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","","","","","",')
newPart.addTag('rawParts','"C2","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","",')
newPart.addTag('rawParts','"CONN1","HEADER-1X25","HEADER-1X25","1X25_ROUND_70MIL","","","","","","",')
newPart.addTag('rawParts','"D1","red","LED0805_NOOUTLINE","CHIPLED_0805_NOOUTLINE","LED","","","","","",')
newPart.addTag('rawParts','"FID2","FIDUCIAL""","FIDUCIAL""","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE","","","","",')
newPart.addTag('rawParts','"FID3","FIDUCIAL""","FIDUCIAL""","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE","","","","",')
newPart.addTag('rawParts','"IC1","MCP23017ML","MCP23017ML","QFN28-ML_6X6MM","http://ww1.microchip.com/downloads/en/DeviceDoc/21952a.pdf","","MICROCHIP","MCP23017-E/SS","1467674","31K2960",')
newPart.addTag('rawParts','"IC2","LM339P","LM339P","TSSOP14","Low Power Low Offset Voltage Quad Comparators","","","","","",')
newPart.addTag('rawParts','"JOY1","","HEADER-1X5","1X05_OVAL","PIN HEADER","","","","","",')
newPart.addTag('rawParts','"JP1","","HEADER-1X4","1X04_OVAL","PIN HEADER","","","","","",')
newPart.addTag('rawParts','"JP2","","HEADER-1X3ROUND","1X03_ROUND","PIN HEADER","","","","","",')
newPart.addTag('rawParts','"JP3","","HEADER-1X3ROUND","1X03_ROUND","PIN HEADER","","","","","",')
newPart.addTag('rawParts','"JP4","","HEADER-1X2","1X02_OVAL","PIN HEADER","","","","","",')
newPart.addTag('rawParts','"JP6","","HEADER-1X2","1X02_OVAL","PIN HEADER","","","","","",')
newPart.addTag('rawParts','"JP7","","HEADER-1X2","1X02_OVAL","PIN HEADER","","","","","",')
newPart.addTag('rawParts','"JP8","","HEADER-1X2","1X02_OVAL","PIN HEADER","","","","","",')
newPart.addTag('rawParts','"JP9","","HEADER-1X2","1X02_OVAL","PIN HEADER","","","","","",')
newPart.addTag('rawParts','"JP10","","HEADER-1X2","1X02_OVAL","PIN HEADER","","","","","",')
newPart.addTag('rawParts','"R1","10K","RESISTOR0805_10MGAP","0805_10MGAP","Resistors","","","","","",')
newPart.addTag('rawParts','"R2","10K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","","","","","",')
newPart.addTag('rawParts','"R3","10K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","","","","","",')
newPart.addTag('rawParts','"R4","1M","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","",')
newPart.addTag('rawParts','"R5","1K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","",')
newPart.addTag('rawParts','"RPI1","RASPBERRYPI_BPLUS_PHAT","RASPBERRYPI_BPLUS_PHAT","PI_BONNET","","","","","","",')
newPart.addTag('rawParts','"SJ1","ADDR","SOLDERJUMPER_2WAY","SOLDERJUMPER_2WAY_OPEN_NOPASTE","2-Way Solder Jumper","","","","","",')
newPart.addTag('rawParts','"SJ2","","SOLDERJUMPERCLOSED","SOLDERJUMPER_CLOSEDWIRE","SMD Solder JUMPER","","","","","",')
newPart.addTag('rawParts','"SPKR","3.5mm","TERMBLOCK_1X2","TERMBLOCK_1X2-3.5MM","3.5mm Terminal block","","","","","",')
newPart.addTag('rawParts','"U1","MAX98357A","AUDIOAMP_MAX98357","QFN16_3MM","MAX98357 - 3.2W I2S Mono Audio Amp","","","","","",')