import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-4409-STAN-01")

newPart.addTag('rawParts','C1,10uF,CAP_CERAMIC0805-NOOUTLINE,0805-NO,Ceramic Capacitors,,')
newPart.addTag('rawParts','D1,1N4148,DIODESOD-323,SOD-323,Diode,,')
newPart.addTag('rawParts','D2,RED,LED0805_NOOUTLINE,CHIPLED_0805_NOOUTLINE,LED,,')
newPart.addTag('rawParts','FID2,FIDUCIAL_1MM,FIDUCIAL_1MM,FIDUCIAL_1MM,Fiducial Alignment Points,EXCLUDE,')
newPart.addTag('rawParts','FID3,FIDUCIAL_1MM,FIDUCIAL_1MM,FIDUCIAL_1MM,Fiducial Alignment Points,EXCLUDE,')
newPart.addTag('rawParts','JP1,0.1 Header,HEADER-1X3,1X03_OVAL,PIN HEADER,,')
newPart.addTag('rawParts','Q1,MMBT2222,TRANSISTOR_NPN,SOT23-R,NPN Transistor,,')
newPart.addTag('rawParts','R1,1K,RESISTOR_0603_NOOUT,0603-NO,Resistors,,')
newPart.addTag('rawParts','R2,10K,RESISTOR_0603_NOOUT,0603-NO,Resistors,,')
newPart.addTag('rawParts','R3,1K,RESISTOR_0603_NOOUT,0603-NO,Resistors,,')
newPart.addTag('rawParts','SJ1,,SOLDERJUMPER_CLOSED,SOLDERJUMPER_CLOSEDWIRE,Solder Jumper - Closed,,')
newPart.addTag('rawParts','U$1,MOUNTINGHOLE2.5,MOUNTINGHOLE2.5,MOUNTINGHOLE_2.5_PLATED,Mounting Hole,EXCLUDE,')
newPart.addTag('rawParts','U$8,MOUNTINGHOLE2.5,MOUNTINGHOLE2.5,MOUNTINGHOLE_2.5_PLATED,Mounting Hole,EXCLUDE,')
newPart.addTag('rawParts','U$9,MOUNTINGHOLE2.5,MOUNTINGHOLE2.5,MOUNTINGHOLE_2.5_PLATED,Mounting Hole,EXCLUDE,')
newPart.addTag('rawParts','U$10,MOUNTINGHOLE2.5,MOUNTINGHOLE2.5,MOUNTINGHOLE_2.5_PLATED,Mounting Hole,EXCLUDE,')
newPart.addTag('rawParts','X1,RELAY_NONLATCHING-EE2NUH,RELAY_NONLATCHING-EE2NUH,RELAY_EE2_NOLATCH,,,')
newPart.addTag('rawParts','X3,3.5mm Terminal,TERMBLOCK_1X3,TERMBLOCK_1X3-3.5MM,3.5mm Terminal block,,')
newPart.addTag('rawParts','X4,JST PH 3,CON_JST_PH_3PIN,JSTPH3,,,')
newPart.addTag('rawParts','X5,2060-403/998-404,2060-403/998-404,P-2060-403/998-404,Serie 2060,  SMD-Leiterplattenklemme mit Bet\xc3\x83\xc2\xa4tigungsdr\xc3\x83\xc2\xbcckern im Gurt 3-polig / Series 2060,  SMD terminal block with push-buttons in tape-and-reel packing 3-polePolzahl / Pole No.: 3 Rasterma\xc3\x83\xc5\xb8 / Pitch: 4  mmBemessungsspannung / Rated Voltage: 160 VNennstrom / Nominal Current: 9 ALeiterquerschnitt / Conductor Size: 0.2 - 0.75 mm2Anschlusstechnik / Connection Technology: CAGE CLAMP\xc3\x82\xc2\xae S Leitereinf\xc3\x83\xc2\xbchrung (zur Platine) / Conductor entry angle (to PCB): 0 \xc3\x82\xc2\xb0Farbe / Color: lichtgrau / light gray Stand: 01.01.2014. Die jeweils aktuellen Daten zu diesem Artikel finden Sie in unserem Produktkatalog, den Sie unter www.wago.com einsehen k\xc3\x83\xc2\xb6nnen.  As of: 01/01/2014. Please find the newest data for this article in our product catalogue, which can be viewed under www.wago.com.,,')