import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-3538-STAN-01")

newPart.addTag('rawParts','"C1","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C2","1uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C3","2.2uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C4","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C5","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C6","0.1uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"FID2","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"FID3","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"JP1","","HEADER-1X670MIL","1X06_ROUND_70","PIN HEADER","",')
newPart.addTag('rawParts','"JP2","","HEADER-1X670MIL","1X06_ROUND_70","PIN HEADER","",')
newPart.addTag('rawParts','"Q1","BSS138","MOSFET-NWIDE","SOT23-WIDE","N-Channel Mosfet","",')
newPart.addTag('rawParts','"Q2","BSS138","MOSFET-NWIDE","SOT23-WIDE","N-Channel Mosfet","",')
newPart.addTag('rawParts','"R1","10K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R2","22","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R3","10K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R4","10K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R5","10K","RESISTOR0805_NOOUTLINE","0805-NO","Resistors","",')
newPart.addTag('rawParts','"R6","10K","RESISTOR0805_10MGAP","0805_10MGAP","Resistors","",')
newPart.addTag('rawParts','"R7","10K","RESISTOR0805_10MGAP","0805_10MGAP","Resistors","",')
newPart.addTag('rawParts','"SJ1","ADDR","SOLDERJUMPER","SOLDERJUMPER_ARROW_NOPASTE","SMD Solder JUMPER","EXCLUDE",')
newPart.addTag('rawParts','"U$16","MOUNTINGHOLE2.5","MOUNTINGHOLE2.5","MOUNTINGHOLE_2.5_PLATED","Mounting Hole","EXCLUDE",')
newPart.addTag('rawParts','"U$17","MOUNTINGHOLE2.5","MOUNTINGHOLE2.5","MOUNTINGHOLE_2.5_PLATED","Mounting Hole","EXCLUDE",')
newPart.addTag('rawParts','"U$18","MOUNTINGHOLE2.5","MOUNTINGHOLE2.5","MOUNTINGHOLE_2.5_PLATED","Mounting Hole","EXCLUDE",')
newPart.addTag('rawParts','"U$19","MOUNTINGHOLE2.5","MOUNTINGHOLE2.5","MOUNTINGHOLE_2.5_PLATED","Mounting Hole","EXCLUDE",')
newPart.addTag('rawParts','"U1","AMG8833","AMG8833","AMG8833","AMG8833 8x8 IR Grid Sensor","",')
newPart.addTag('rawParts','"U2","mic5225-3.3","VREG_SOT23-5","SOT23-5","SOT23-5 Fixed Voltage Regulators","",')