import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-14350-STAN-01")

newPart.addTag('rawParts','"C1","0.1uF","0.1UF-0603-25V-5%","0603","0.1\xc3\x82\xc2\xb5F ceramic capacitors","CAP-08604","0.1uF",')
newPart.addTag('rawParts','"FD1","FIDUCIALUFIDUCIAL","FIDUCIALUFIDUCIAL","FIDUCIAL-MICRO","Fiducial Alignment Points","","",')
newPart.addTag('rawParts','"FD2","FIDUCIALUFIDUCIAL","FIDUCIALUFIDUCIAL","FIDUCIAL-MICRO","Fiducial Alignment Points","","",')
newPart.addTag('rawParts','"FD3","FIDUCIALUFIDUCIAL","FIDUCIALUFIDUCIAL","FIDUCIAL-MICRO","Fiducial Alignment Points","","",')
newPart.addTag('rawParts','"FD4","FIDUCIALUFIDUCIAL","FIDUCIALUFIDUCIAL","FIDUCIAL-MICRO","Fiducial Alignment Points","","",')
newPart.addTag('rawParts','"FRAME1","FRAME-LETTER","FRAME-LETTER","CREATIVE_COMMONS","Schematic Frame - Letter","","",')
newPart.addTag('rawParts','"J1","","I2C_STANDARD","1X04","SparkFun I2C Standard Pinout Header","","",')
newPart.addTag('rawParts','"J2","","CONN_01","1X01","Single connection point. Often used as Generic Header-pin footprint for 0.1 inch spaced/style header connections","","",')
newPart.addTag('rawParts','"JP1","JUMPER-SMT_3_NO_SILK","JUMPER-SMT_3_NO_SILK","SMT-JUMPER_3_NO_SILK","Normally open jumper","","",')
newPart.addTag('rawParts','"LOGO1","SFE_LOGO_FLAME.1_INCH","SFE_LOGO_FLAME.1_INCH","SFE_LOGO_FLAME_.1","SparkFun Flame Logo","","",')
newPart.addTag('rawParts','"LOGO2","OSHW-LOGOS","OSHW-LOGOS","OSHW-LOGO-S","Open-Source Hardware (OSHW) Logo","","",')
newPart.addTag('rawParts','"R1","4.7k","4.7KOHM-0603-1/10W-1%","0603","4.7k\xc3\x8e\xc2\xa9 resistor","RES-07857","4.7k",')
newPart.addTag('rawParts','"R2","4.7k","4.7KOHM-0603-1/10W-1%","0603","4.7k\xc3\x8e\xc2\xa9 resistor","RES-07857","4.7k",')
newPart.addTag('rawParts','"R3","10k","10KOHM-0603-1/10W-1%","0603","10k\xc3\x8e\xc2\xa9 resistor","RES-00824","10k",')
newPart.addTag('rawParts','"R4","10k","10KOHM-0603-1/10W-1%","0603","10k\xc3\x8e\xc2\xa9 resistor","RES-00824","10k",')
newPart.addTag('rawParts','"U1","APDS-9301","APDS-9301","CHIPLED-6","","IC-13662","APDS-9301",')