import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-1231-STAN-0B")

newPart.addTag('rawParts','C1,0.1uF,CAP_CERAMIC0805-NOOUTLINE,0805-NO,Ceramic Capacitors,,')
newPart.addTag('rawParts','C3,10\xc3\x82\xc2\xb5F,CAP_CERAMIC0805-NOOUTLINE,0805-NO,Ceramic Capacitors,,')
newPart.addTag('rawParts','D1,1N4148,DIODE_SOD323MINI,SOD-323_MINI,Diode,,')
newPart.addTag('rawParts','JP1,,HEADER-1X970MIL,1X09_ROUND_70,PIN HEADER,,')
newPart.addTag('rawParts','Q1,BSS138,MOSFET-NWIDE,SOT23-WIDE,N-Channel Mosfet,,')
newPart.addTag('rawParts','Q2,BSS138,MOSFET-NWIDE,SOT23-WIDE,N-Channel Mosfet,,')
newPart.addTag('rawParts','R1,10K,RESISTOR0805_NOOUTLINE,0805-NO,Resistors,,')
newPart.addTag('rawParts','R2,10K,RESISTOR0805_NOOUTLINE,0805-NO,Resistors,,')
newPart.addTag('rawParts','R3,10K,RESISTOR0805_NOOUTLINE,0805-NO,Resistors,,')
newPart.addTag('rawParts','R5,10K,RESISTOR0805_NOOUTLINE,0805-NO,Resistors,,')
newPart.addTag('rawParts','R6,10K,RESISTOR0805_NOOUTLINE,0805-NO,Resistors,,')
newPart.addTag('rawParts','R7,10K,RESISTOR0805_NOOUTLINE,0805-NO,Resistors,,')
newPart.addTag('rawParts','U$1,FIDUCIAL,FIDUCIAL,FIDUCIAL_1MM,For use by pick and place machines to calibrate the vision/machine, 1mm,,')
newPart.addTag('rawParts','U$3,FIDUCIAL,FIDUCIAL,FIDUCIAL_1MM,For use by pick and place machines to calibrate the vision/machine, 1mm,,')
newPart.addTag('rawParts','U$4,MOUNTINGHOLE2.5,MOUNTINGHOLE2.5,MOUNTINGHOLE_2.5_PLATED,Mounting Hole,EXCLUDE,')
newPart.addTag('rawParts','U$6,MOUNTINGHOLE2.5,MOUNTINGHOLE2.5,MOUNTINGHOLE_2.5_PLATED,Mounting Hole,EXCLUDE,')
newPart.addTag('rawParts','U1,,ACCEL_ADXL345,LGA14,ADXL345 - Digital 3-Axis Accelerometer (I2C/SPI),,')
newPart.addTag('rawParts','U2,,VREG_SOT23-5,SOT23-5,SOT23-5 Fixed Voltage Regulators,,')