import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-4026-STAN-01")

newPart.addTag('rawParts','"C3","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","",')
newPart.addTag('rawParts','"C5","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","",')
newPart.addTag('rawParts','"D1","RED","LED0805_NOOUTLINE","CHIPLED_0805_NOOUTLINE","LED","","",')
newPart.addTag('rawParts','"FID1","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE","",')
newPart.addTag('rawParts','"FID2","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE","",')
newPart.addTag('rawParts','"IC1","ATSAMD10D14A","ATSAMD10D14A","QFN24_4MM","","","",')
newPart.addTag('rawParts','"Q3","2N7002D","MOSFET-N_DUAL","SOT363","Dual N-Channel MOSFET","","",')
newPart.addTag('rawParts','"R1","1K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","",')
newPart.addTag('rawParts','"R2","1K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","",')
newPart.addTag('rawParts','"R6","10K","RESISTOR_4PACK","RESPACK_4X0603","Resistor Packs (4 resistors)","","",')
newPart.addTag('rawParts','"SJ8","","SOLDERJUMPER","SOLDERJUMPER_ARROW_NOPASTE","SMD Solder JUMPER","EXCLUDE","",')
newPart.addTag('rawParts','"SJ9","","SOLDERJUMPER","SOLDERJUMPER_ARROW_NOPASTE","SMD Solder JUMPER","EXCLUDE","",')
newPart.addTag('rawParts','"TP1","TPTP15R","TPTP15R","TP15R","Test pad","","",')
newPart.addTag('rawParts','"TP2","TPTP15R","TPTP15R","TP15R","Test pad","","",')
newPart.addTag('rawParts','"TP3","TPTP10R","TPTP10R","TP10R","Test pad","","",')
newPart.addTag('rawParts','"TP4","TPTP15R","TPTP15R","TP15R","Test pad","","",')
newPart.addTag('rawParts','"U2","MIC5225-3.3","VREG_SOT23-5","SOT23-5","SOT23-5 Fixed Voltage Regulators","","",')
newPart.addTag('rawParts','"X1","STEMMA_I2C_RASMT","STEMMA_I2C_RASMT","JSTPH4","","","",')