import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-10930-STAN-01")

newPart.addTag('rawParts','"C1","","CAPCAP-PTH-SMALL-KIT","CAP-PTH-SMALL-KIT","Capacitor","",')
newPart.addTag('rawParts','"C2","","CAPCAP-PTH-SMALL-KIT","CAP-PTH-SMALL-KIT","Capacitor","",')
newPart.addTag('rawParts','"C5","10uF","CAP_POLCPOL-RADIAL-10UF-25V-KIT","CPOL-RADIAL-10UF-25V-KIT","Capacitor Polarized","",')
newPart.addTag('rawParts','"C6","0.1uF","CAPCAP-PTH-SMALL-KIT","CAP-PTH-SMALL-KIT","Capacitor","",')
newPart.addTag('rawParts','"J1","POWER_JACKKIT","POWER_JACKKIT","POWER-BARRELJACK-PTH-LOCK-KIT","Power Jack","",')
newPart.addTag('rawParts','"JP2","AVR_SPI_PRG_6PTH","AVR_SPI_PRG_6PTH","2X3","AVR ISP 6 Pin","",')
newPart.addTag('rawParts','"LED1","7-SEGMENT-4DIGIT-YOUNGSUNKIT","7-SEGMENT-4DIGIT-YOUNGSUNKIT","7-SEGMENT-4DIGIT-YOUNGSUN-KIT","This is a part for the 4-Digit 7-segment LEDs from Young Sun.  Different from the Digikey LEDs, all 16 pins are used.","",')
newPart.addTag('rawParts','"Q1","16MHz","CRYSTALHC49US-KIT","HC49US-KIT","Crystals","",')
newPart.addTag('rawParts','"R1","10K","RESISTORAXIAL-0.3-KIT","AXIAL-0.3-KIT","Resistor","",')
newPart.addTag('rawParts','"S1","SWITCH-MOMENTARY-2TACTILE-PTH-KIT","SWITCH-MOMENTARY-2TACTILE-PTH-KIT","TACTILE-PTH-KIT","","",')
newPart.addTag('rawParts','"S2","SWITCH-MOMENTARY-2TACTILE-PTH-KIT","SWITCH-MOMENTARY-2TACTILE-PTH-KIT","TACTILE-PTH-KIT","","",')
newPart.addTag('rawParts','"S3","","SWITCH-SPSTKIT","SWITCH-SPDT_KIT","SPST Switch","",')
newPart.addTag('rawParts','"S4","SWITCH-MOMENTARY-2TACTILE-PTH-KIT","SWITCH-MOMENTARY-2TACTILE-PTH-KIT","TACTILE-PTH-KIT","","",')
newPart.addTag('rawParts','"SG2","BUZZERKIT","BUZZERKIT","BUZZER-12MM-KIT","Buzzer 12mm","",')
newPart.addTag('rawParts','"U$1","LOGO-SFESK","LOGO-SFESK","SFE-LOGO-FLAME","Spark Fun Electronics PCB Logo","",')
newPart.addTag('rawParts','"U$2","CREATIVE_COMMONS","CREATIVE_COMMONS","CREATIVE_COMMONS","","",')
newPart.addTag('rawParts','"U$3","LOGO-SFENEW","LOGO-SFENEW","SFE-NEW-WEBLOGO","Spark Fun Electronics PCB Logo","",')
newPart.addTag('rawParts','"U$8","STAND-OFF","STAND-OFF","STAND-OFF","Stand Off","",')
newPart.addTag('rawParts','"U$9","STAND-OFF","STAND-OFF","STAND-OFF","Stand Off","",')
newPart.addTag('rawParts','"U1","AVR-MEGA8-PKIT","AVR-MEGA8-PKIT","DIL28-3-KIT","MICROCONTROLLER","",')