import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-13343-STAN-01")

newPart.addTag('oompParts','FRAME1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','S1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')