import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-3229-STAN-01")

newPart.addTag('rawParts','C1,10uF,CAP_CERAMIC0805-NOOUTLINE,0805-NO,Ceramic Capacitors,,')
newPart.addTag('rawParts','FID1,FIDUCIAL,FIDUCIAL,FIDUCIAL_1MM,Fiducial Alignment Points,EXCLUDE,')
newPart.addTag('rawParts','FID2,FIDUCIAL,FIDUCIAL,FIDUCIAL_1MM,Fiducial Alignment Points,EXCLUDE,')
newPart.addTag('rawParts','JP1,,HEADER-1X970MIL,1X09_ROUND_70,PIN HEADER,,')
newPart.addTag('rawParts','JP2,,HEADER-1X570MIL,1X05_ROUND_70,PIN HEADER,,')
newPart.addTag('rawParts','JP3,,HEADER-1X570MIL,1X05_ROUND_70,PIN HEADER,,')
newPart.addTag('rawParts','JP4,,HEADER-1X376MIL,1X03_ROUND_76,PIN HEADER,,')
newPart.addTag('rawParts','JP5,,HEADER-1X376MIL,1X03_ROUND_76,PIN HEADER,,')
newPart.addTag('rawParts','JP6,,HEADER-1X2ROUND,1X02_ROUND,PIN HEADER,,')
newPart.addTag('rawParts','JP7,,HEADER-1X576MIL,1X05_ROUND_76,PIN HEADER,,')
newPart.addTag('rawParts','MS1,FEATHERWING_NOHOLES,FEATHERWING_NOHOLES,FEATHERWING_NOHOLES,,,')
newPart.addTag('rawParts','R1,100k,RESISTOR_0603_NOOUT,0603-NO,Resistors,,')
newPart.addTag('rawParts','R2,100k,RESISTOR_0603_NOOUT,0603-NO,Resistors,,')
newPart.addTag('rawParts','SW1,,SWITCH_TACT_SMT4.6X2.8,BTN_KMR2_4.6X2.8,SMT Tact Switches,,')
newPart.addTag('rawParts','U$7,MOUNTINGHOLE2.5,MOUNTINGHOLE2.5,MOUNTINGHOLE_2.5_PLATED,Mounting Hole,EXCLUDE,')
newPart.addTag('rawParts','U$8,MOUNTINGHOLE2.5,MOUNTINGHOLE2.5,MOUNTINGHOLE_2.5_PLATED,Mounting Hole,EXCLUDE,')
newPart.addTag('rawParts','U4,RFM69/9x,RFM69HCW_SMT,RFMHCW_SMT,RFM69HCW - ISM Band RF Transceiver,,')
newPart.addTag('rawParts','X1,uFL/SMA,SMACONNECTOR_EDGE_UFL,SMA_EDGELAUNCH_UFL,SMA Connector,,')