import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-4393-STAN-01")

newPart.addTag('rawParts','"C1","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C2","1uF","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C10","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","",')
newPart.addTag('rawParts','"CONN1","STEMMA_I2C_QT","STEMMA_I2C_QT","JST_SH4","","",')
newPart.addTag('rawParts','"DISPLAY1","DISP_LCD_ST7789_1.3IN","DISP_LCD_ST7789_1.3IN","TFT_1.3IN_240X240_24P","","",')
newPart.addTag('rawParts','"FID1","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"FID2","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"FID3","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"FID4","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"IC5","APX803","AXP083-SAG","SOT23","","",')
newPart.addTag('rawParts','"Q1","MMBT2222","TRANSISTOR_NPNWIDE","SOT23-WIDE","NPN Transistor","",')
newPart.addTag('rawParts','"R1","10K","RESISTOR_0603_NOOUT","0603-NO","Resistors","",')
newPart.addTag('rawParts','"R2","10K","RESISTOR_0603_NOOUT","0603-NO","Resistors","",')
newPart.addTag('rawParts','"R3","10K","RESISTOR_0603_NOOUT","0603-NO","Resistors","",')
newPart.addTag('rawParts','"R5","10","RESISTOR_0603_NOOUT","0603-NO","Resistors","",')
newPart.addTag('rawParts','"R7","1K","RESISTOR_0603_NOOUT","0603-NO","Resistors","",')
newPart.addTag('rawParts','"R8","10K","RESISTOR_0603_NOOUT","0603-NO","Resistors","",')
newPart.addTag('rawParts','"RASPI1","RASPBERRYPI_2X12_SMT","RASPBERRYPI_2X12_SMT","RASPBERRYPI_2X12_SMT","","",')
newPart.addTag('rawParts','"SJ1","","SOLDERJUMPER_CLOSED","SOLDERJUMPER_CLOSEDWIRE","Solder Jumper - Closed","",')
newPart.addTag('rawParts','"SW1","","SWITCH_TACT_SMT_EVQQ2_SMALL","EVQ-Q2_SMALLER","SMT Tact Switches","",')
newPart.addTag('rawParts','"SW2","","SWITCH_TACT_SMT_EVQQ2_SMALL","EVQ-Q2_SMALLER","SMT Tact Switches","",')