import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-2088-STAN-01")

newPart.addTag('oompParts','C1,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')
newPart.addTag('oompParts','C2,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')
newPart.addTag('oompParts','C4,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')
newPart.addTag('oompParts','IC1,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')
newPart.addTag('oompParts','IC2,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')
newPart.addTag('oompParts','JP1,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')
newPart.addTag('oompParts','Q2,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')
newPart.addTag('oompParts','Q3,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')
newPart.addTag('oompParts','R3,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')
newPart.addTag('oompParts','TFT2,UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED-UNMATCHED')