import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-9370-STAN-01")

newPart.addTag('rawParts','C1,100uF-25V,CAP_POL,NIPPON_F80,Capacitor Polarized,,')
newPart.addTag('rawParts','C2,22uF-35v,CAP_POLC,PANASONIC_C,Capacitor Polarized,,')
newPart.addTag('rawParts','C3,0.1uF,CAP0603-CAP,0603-CAP,Capacitor,,')
newPart.addTag('rawParts','FID1,FIDUCIAL1X2,FIDUCIAL1X2,FIDUCIAL-1X2,Fiducial Alignment Points,,')
newPart.addTag('rawParts','FID2,FIDUCIAL1X2,FIDUCIAL1X2,FIDUCIAL-1X2,Fiducial Alignment Points,,')
newPart.addTag('rawParts','IN,,M05PTH,1X05,Header 5,,')
newPart.addTag('rawParts','OUT,,M03PTH,1X03,Header 3,,')
newPart.addTag('rawParts','Q1,MOSFET-NCHANNELSMD,MOSFET-NCHANNELSMD,SOT23-3,,,')
newPart.addTag('rawParts','R1,22K,RESISTOR0603-RES,0603-RES,Resistor,,')
newPart.addTag('rawParts','R2,100K,RESISTOR0603-RES,0603-RES,Resistor,,')
newPart.addTag('rawParts','U$1,STAND-OFF,STAND-OFF,STAND-OFF,Stand Off,,')
newPart.addTag('rawParts','U$2,LOGO-SFENEW,LOGO-SFENEW,SFE-NEW-WEBLOGO,Spark Fun Electronics PCB Logo,,')
newPart.addTag('rawParts','U$3,STAND-OFF,STAND-OFF,STAND-OFF,Stand Off,,')
newPart.addTag('rawParts','U$4,STAND-OFF,STAND-OFF,STAND-OFF,Stand Off,,')
newPart.addTag('rawParts','U$5,STAND-OFF,STAND-OFF,STAND-OFF,Stand Off,,')
newPart.addTag('rawParts','U1,DC-DC_CONVERTER,DC-DC_CONVERTER,DC-DC_CONVERTER,,,')