import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-3464-STAN-01")

newPart.addTag('oompParts','1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','2,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','JOY1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','RPI1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','SW1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','SW2,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','SW3,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','SW4,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','SW5,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','SW8,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')