import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-2324-STAN-01")

newPart.addTag('rawParts','B1,CR1220,BATTERYCR1220_SMT,CR1220,CR1220 SMT - Digikey: 3001K-ND,,')
newPart.addTag('rawParts','C1,0.1uF,CAP_CERAMIC0805-NOOUTLINE,0805-NO,Ceramic Capacitors,,')
newPart.addTag('rawParts','C2,10uF,CAP_CERAMIC0805-NOOUTLINE,0805-NO,Ceramic Capacitors,,')
newPart.addTag('rawParts','CONN1,HEADER-1X25,HEADER-1X25,1X25_ROUND_70MIL,,,')
newPart.addTag('rawParts','FB1,Ferrite,FERRITE0805,0805,Ferrite Bead,,')
newPart.addTag('rawParts','FID1,FIDUCIAL,FIDUCIAL,FIDUCIAL_1MM,Fiducial Alignment Points,EXCLUDE,')
newPart.addTag('rawParts','FID2,FIDUCIAL,FIDUCIAL,FIDUCIAL_1MM,Fiducial Alignment Points,EXCLUDE,')
newPart.addTag('rawParts','FID3,FIDUCIAL,FIDUCIAL,FIDUCIAL_1MM,Fiducial Alignment Points,EXCLUDE,')
newPart.addTag('rawParts','JP1,,PINHD-1X1CB,1X01-CLEANBIG,Pin header 1x1 for 0.1 spacing,,')
newPart.addTag('rawParts','LED1,RED,LED0805,CHIPLED_0805,LED,,')
newPart.addTag('rawParts','R1,3.9K,RESISTOR0805_NOOUTLINE,0805-NO,Resistors,,')
newPart.addTag('rawParts','R2,3.9K,RESISTOR0805_NOOUTLINE,0805-NO,Resistors,,')
newPart.addTag('rawParts','R3,3.9K,RESISTOR0805_NOOUTLINE,0805-NO,Resistors,,')
newPart.addTag('rawParts','R4,470,RESISTOR0805_NOOUTLINE,0805-NO,Resistors,,')
newPart.addTag('rawParts','RPI1,RASPBERRYPI_BPLUS_HATSLOTS,RASPBERRYPI_BPLUS_HATSLOTS,PI_HAT_SLOTS,,,')
newPart.addTag('rawParts','SJ1,WP,SOLDERJUMPER_CLOSED,SOLDERJUMPER_CLOSEDWIRE,Solder Jumper - Closed,,')
newPart.addTag('rawParts','SJ2,PPS,SOLDERJUMPER_CLOSED,SOLDERJUMPER_CLOSEDWIRE,Solder Jumper - Closed,,')
newPart.addTag('rawParts','U$20,U.FL,U.FL,U.FL,U.FL Antenna Connector,,')
newPart.addTag('rawParts','U1,CAT24C32,EEPROM_I2C_SOIC8_GENERIC,SOIC8_150MIL,Note: The same pinout is used for many I2C EEPROMs in SOIC8(150mil) from a variety of manufacturers and in various sizes.,,')
newPart.addTag('rawParts','U2,FGPMMOPA6H,GPS_FGPMMOPA6H,FGPMMOPA6H,GPS Module - MTK MT3339 Chipset, -165dBm sensitivity, 22 channels, 10Hz, auto-select external antenna options,,')