import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-14666-STAN-01")

newPart.addTag('rawParts','"C1","0.1uF","0.1UF-0603-25V-(+80/-20%)","0603","0.1\xc3\x82\xc2\xb5F ceramic capacitors","CAP-00810","0.1uF",')
newPart.addTag('rawParts','"D1","RED","LED-RED0603","LED-0603","Red SMD LED","DIO-00819","RED",')
newPart.addTag('rawParts','"FD1","FIDUCIALUFIDUCIAL","FIDUCIALUFIDUCIAL","FIDUCIAL-MICRO","Fiducial Alignment Points","","",')
newPart.addTag('rawParts','"FD2","FIDUCIALUFIDUCIAL","FIDUCIALUFIDUCIAL","FIDUCIAL-MICRO","Fiducial Alignment Points","","",')
newPart.addTag('rawParts','"FD3","FIDUCIALUFIDUCIAL","FIDUCIALUFIDUCIAL","FIDUCIAL-MICRO","Fiducial Alignment Points","","",')
newPart.addTag('rawParts','"FD4","FIDUCIALUFIDUCIAL","FIDUCIALUFIDUCIAL","FIDUCIAL-MICRO","Fiducial Alignment Points","","",')
newPart.addTag('rawParts','"FRAME1","FRAME-LETTER","FRAME-LETTER","CREATIVE_COMMONS","Schematic Frame - Letter","","",')
newPart.addTag('rawParts','"J1","","QWIIC_CONNECTORJS-1MM","1X04_1MM_RA","SparkFun I2C Standard Qwiic Connector","CONN-13694","",')
newPart.addTag('rawParts','"J2","","QWIIC_CONNECTORJS-1MM","1X04_1MM_RA","SparkFun I2C Standard Qwiic Connector","CONN-13694","",')
newPart.addTag('rawParts','"J3","","CONN_02","1X02","Multi connection point. Often used as Generic Header-pin footprint for 0.1 inch spaced/style header connections","","",')
newPart.addTag('rawParts','"J4","","CONN_02","1X02","Multi connection point. Often used as Generic Header-pin footprint for 0.1 inch spaced/style header connections","","",')
newPart.addTag('rawParts','"JP1","JUMPER-SMT_3_2-NC_TRACE_NO-SILK","JUMPER-SMT_3_2-NC_TRACE_NO-SILK","SMT-JUMPER_3_2-NC_TRACE_NO-SILK","Normally closed trace jumper (2 of 2 connections)","","",')
newPart.addTag('rawParts','"JP2","JUMPER-SMT_3_1-NC_TRACE_NO-SILK","JUMPER-SMT_3_1-NC_TRACE_NO-SILK","SMT-JUMPER_3_1-NC_TRACE_NO-SILK","Normally closed trace jumper (1 of 2 connections)","","",')
newPart.addTag('rawParts','"JP3","JUMPER-SMT_3_NO_NO_SILK","JUMPER-SMT_3_NO_NO_SILK","SMT-JUMPER_3_0-NO_TRACE_NO-SILK","Normally open jumper","","",')
newPart.addTag('rawParts','"LOGO1","SFE_LOGO_NAME_FLAME.1_INCH","SFE_LOGO_NAME_FLAME.1_INCH","SFE_LOGO_NAME_FLAME_.1","SparkFun Font Logo w/ Flame","","",')
newPart.addTag('rawParts','"LOGO2","OSHW-LOGOS","OSHW-LOGOS","OSHW-LOGO-S","Open-Source Hardware (OSHW) Logo","","",')
newPart.addTag('rawParts','"LOGO3","SFE_LOGO_FLAME.1_INCH","SFE_LOGO_FLAME.1_INCH","SFE_LOGO_FLAME_.1","SparkFun Flame Logo","","",')
newPart.addTag('rawParts','"R1","4.7k","4.7KOHM-0603-1/10W-1%","0603","4.7k\xc3\x8e\xc2\xa9 resistor","RES-07857","4.7k",')
newPart.addTag('rawParts','"R2","4.7k","4.7KOHM-0603-1/10W-1%","0603","4.7k\xc3\x8e\xc2\xa9 resistor","RES-07857","4.7k",')
newPart.addTag('rawParts','"R3","100k","100KOHM-0603-1/10W-1%","0603","100k\xc3\x8e\xc2\xa9 resistor","RES-07828","100k",')
newPart.addTag('rawParts','"R4","100k","100KOHM-0603-1/10W-1%","0603","100k\xc3\x8e\xc2\xa9 resistor","RES-07828","100k",')
newPart.addTag('rawParts','"R5","1k","1KOHM-0603-1/10W-1%","0603","1k\xc3\x8e\xc2\xa9 resistor","RES-07856","1k",')
newPart.addTag('rawParts','"R6","FLEX_SENSOR-4.5"","FLEX_SENSOR-4.5"","FLEX_SENSOR","Spectra Symbol Flex Sensor (2.2", 4.5") - A flexible resistor that changes its resistance as it bends.","COMP-13078","",')
newPart.addTag('rawParts','"R7","FLEX_SENSOR-4.5"","FLEX_SENSOR-4.5"","FLEX_SENSOR","Spectra Symbol Flex Sensor (2.2", 4.5") - A flexible resistor that changes its resistance as it bends.","COMP-13078","",')
newPart.addTag('rawParts','"TP1","TEST-POINT3","TEST-POINT3","PAD.03X.03","SparkFun Test Points","","",')
newPart.addTag('rawParts','"TP2","TEST-POINT3","TEST-POINT3","PAD.03X.03","SparkFun Test Points","","",')
newPart.addTag('rawParts','"U1","ADS1015","ADS1015","MSOP10","ADS1015 12-BIT ADC","IC-12270","ADS1015",')
newPart.addTag('rawParts','"U4","LMV358","LMV358SOIC","SO08","IC LMV358 DUAL OP AMP","IC-09657","LMV358",')