import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-14666-STAN-01")

newPart.addTag('oompParts','C1,CAPC-0603-X-NF100-V50')
newPart.addTag('oompParts','D1,LEDS-0603-G-STAN-01')
newPart.addTag('oompParts','J1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','J2,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','J3,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','J4,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','JP1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','JP2,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','JP3,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','R1,RESE-0603-X-UNMATCHED-01')
newPart.addTag('oompParts','R2,RESE-0603-X-UNMATCHED-01')
newPart.addTag('oompParts','R3,RESE-0603-X-O1003-01')
newPart.addTag('oompParts','R4,RESE-0603-X-O1003-01')
newPart.addTag('oompParts','R5,RESE-0603-X-O102-01')
newPart.addTag('oompParts','R6,RESE-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','R7,RESE-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','TP1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','TP2,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','U4,UNMATCHED-UNMATCHED-X-UNMATCHED-01')