import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-10995-STAN-01")

newPart.addTag('rawParts','C1,1uF,CAP0402-CAP,0402-CAP,Capacitor,,')
newPart.addTag('rawParts','C2,10uF,CAP_POL1206,EIA3216,Capacitor Polarized,,')
newPart.addTag('rawParts','C3,0.1uF,CAP0402-CAP,0402-CAP,Capacitor,,')
newPart.addTag('rawParts','C4,10uF,CAP_POL1206,EIA3216,Capacitor Polarized,,')
newPart.addTag('rawParts','JP1,M01PTH,M01PTH,1X01,Header 1,,')
newPart.addTag('rawParts','JP2,STAND-OFF,STAND-OFF,STAND-OFF,Stand Off,,')
newPart.addTag('rawParts','JP3,STAND-OFF,STAND-OFF,STAND-OFF,Stand Off,,')
newPart.addTag('rawParts','JP4,LOGO-SFESK,LOGO-SFESK,SFE-LOGO-FLAME,Spark Fun Electronics PCB Logo,,')
newPart.addTag('rawParts','JP5,LOGO-SFENEW,LOGO-SFENEW,SFE-NEW-WEBLOGO,Spark Fun Electronics PCB Logo,,')
newPart.addTag('rawParts','JP6,FTDI_BASICPTH,FTDI_BASICPTH,FTDI_BASIC,FTDI Basic: 3.3V and 5V,,')
newPart.addTag('rawParts','JP7,M01PTH,M01PTH,1X01,Header 1,,')
newPart.addTag('rawParts','JP8,FIDUCIALUFIDUCIAL,FIDUCIALUFIDUCIAL,MICRO-FIDUCIAL,Fiducial Alignment Points,,')
newPart.addTag('rawParts','JP9,FIDUCIALUFIDUCIAL,FIDUCIALUFIDUCIAL,MICRO-FIDUCIAL,Fiducial Alignment Points,,')
newPart.addTag('rawParts','LED1,red,LED0603,LED-0603,LEDs,,')
newPart.addTag('rawParts','Q1,MOSFET-NCHANNELSMD,MOSFET-NCHANNELSMD,SOT23-3,,,')
newPart.addTag('rawParts','Q2,MOSFET-NCHANNELSMD,MOSFET-NCHANNELSMD,SOT23-3,,,')
newPart.addTag('rawParts','Q3,MOSFET-NCHANNELSMD,MOSFET-NCHANNELSMD,SOT23-3,,,')
newPart.addTag('rawParts','Q4,MOSFET-NCHANNELSMD,MOSFET-NCHANNELSMD,SOT23-3,,,')
newPart.addTag('rawParts','R1,10k,RESISTOR0402-RES,0402-RES,Resistor,,')
newPart.addTag('rawParts','R2,10k,RESISTOR0402-RES,0402-RES,Resistor,,')
newPart.addTag('rawParts','R3,10k,RESISTOR0402-RES,0402-RES,Resistor,,')
newPart.addTag('rawParts','R4,10k,RESISTOR0402-RES,0402-RES,Resistor,,')
newPart.addTag('rawParts','R5,10k,RESISTOR0402-RES,0402-RES,Resistor,,')
newPart.addTag('rawParts','R6,10k,RESISTOR0402-RES,0402-RES,Resistor,,')
newPart.addTag('rawParts','R7,10k,RESISTOR0402-RES,0402-RES,Resistor,,')
newPart.addTag('rawParts','R8,10k,RESISTOR0402-RES,0402-RES,Resistor,,')
newPart.addTag('rawParts','R9,0.27,RESISTOR0402-RES,0402-RES,Resistor,,')
newPart.addTag('rawParts','S1,SWITCH-MOMENTARY-2SMD,SWITCH-MOMENTARY-2SMD,TACTILE_SWITCH_SMD,,,')
newPart.addTag('rawParts','SJ1,SOLDERJUMPERTRACE,SOLDERJUMPERTRACE,SJ_2S-TRACE,Solder Jumper,,')
newPart.addTag('rawParts','U$7,OSHW-LOGOS,OSHW-LOGOS,OSHW-LOGO-S,Open Source Hardware Logo This logo indicates the piece of hardware it is found on incorporates a OSHW license and/or adheres to the definition of open source hardware found here: http://freedomdefined.org/OSHW,,')
newPart.addTag('rawParts','U$8,CREATIVE_COMMONS,CREATIVE_COMMONS,CREATIVE_COMMONS,,,')
newPart.addTag('rawParts','U1,GP-2106,GP-2106,GP-2106,GP-2106 GPS SiRF IV,,')
newPart.addTag('rawParts','U2,V_REG_LDOSMD2,V_REG_LDOSMD2,SC70,Voltage Regulator LDO,,')