import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-3321-STAN-01")

newPart.addTag('rawParts','"FID1","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"FID2","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"IC2","ATSAMD09D14A-MU","ATSAMD09D14A-MU","QFN24_4MM","","",')
newPart.addTag('rawParts','"MS1","FEATHERWING","FEATHERWING","FEATHERWING","","",')
newPart.addTag('rawParts','"R1","10","RESISTOR_0603_NOOUT","0603-NO","Resistors","",')
newPart.addTag('rawParts','"R5","10K","RESISTOR_0603_NOOUT","0603-NO","Resistors","",')
newPart.addTag('rawParts','"R6","10k","RESISTOR_0603_NOOUT","0603-NO","Resistors","",')
newPart.addTag('rawParts','"R7","1k","RESISTOR_0603_NOOUT","0603-NO","Resistors","",')
newPart.addTag('rawParts','"SJ1","","SOLDERJUMPER_CLOSED","SOLDERJUMPER_CLOSEDWIRE","Solder Jumper - Closed","",')
newPart.addTag('rawParts','"SJ2","","SOLDERJUMPER_CLOSED","SOLDERJUMPER_CLOSEDWIRE","Solder Jumper - Closed","",')
newPart.addTag('rawParts','"SJ3","","SOLDERJUMPER","SOLDERJUMPER_ARROW_NOPASTE","SMD Solder JUMPER","EXCLUDE",')
newPart.addTag('rawParts','"SJ4","","SOLDERJUMPER","SOLDERJUMPER_ARROW_NOPASTE","SMD Solder JUMPER","EXCLUDE",')
newPart.addTag('rawParts','"SJ5","","SOLDERJUMPER","SOLDERJUMPER_ARROW_NOPASTE","SMD Solder JUMPER","EXCLUDE",')
newPart.addTag('rawParts','"SJ6","","SOLDERJUMPER","SOLDERJUMPER_ARROW_NOPASTE","SMD Solder JUMPER","EXCLUDE",')
newPart.addTag('rawParts','"SJ8","","SOLDERJUMPER","SOLDERJUMPER_ARROW_NOPASTE","SMD Solder JUMPER","EXCLUDE",')
newPart.addTag('rawParts','"SJ9","","SOLDERJUMPER","SOLDERJUMPER_ARROW_NOPASTE","SMD Solder JUMPER","EXCLUDE",')
newPart.addTag('rawParts','"SW1","KMR2","SWITCH_TACT_SMT4.6X2.8","BTN_KMR2_4.6X2.8","SMT Tact Switches","",')
newPart.addTag('rawParts','"SW2","EVQQ","SWITCH_TACT_SMT_EVQQ2_SMALL","EVQ-Q2_SMALLER","SMT Tact Switches","",')
newPart.addTag('rawParts','"SW3","EVQQ","SWITCH_TACT_SMT_EVQQ2_SMALL","EVQ-Q2_SMALLER","SMT Tact Switches","",')
newPart.addTag('rawParts','"SW4","NAVSWITCHSKQUABAUE010","NAVSWITCHSKQUABAUE010","SKQUBAE010","","",')
newPart.addTag('rawParts','"TP1","","TESTPOINTROUND2MM","TESTPOINT_ROUND_2MM","Test Point","",')
newPart.addTag('rawParts','"TP2","","TESTPOINTROUND2MM","TESTPOINT_ROUND_2MM","Test Point","",')
newPart.addTag('rawParts','"U$2","DISP_LCD_0.9IN_160X80","DISP_LCD_0.9IN_160X80","TFT_0.96IN_160X80","","",')