import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-198-STAN-01")

newPart.addTag('rawParts','C1,1uF,1.0UF-16V-10%(0603),0603-CAP,CAP-00868,CAP-00868,1.0uF,')
newPart.addTag('rawParts','C2,0.1uF,0.1UF-25V(+80/-20%)(0603),0603-CAP,CAP-00810,CAP-00810,0.1uF,')
newPart.addTag('rawParts','C3,10uF,CAP_POL1206,EIA3216,Capacitor Polarized,,,')
newPart.addTag('rawParts','FID1,FIDUCIAL1X2,FIDUCIAL1X2,FIDUCIAL-1X2,Fiducial Alignment Points,,,')
newPart.addTag('rawParts','FID2,FIDUCIAL1X2,FIDUCIAL1X2,FIDUCIAL-1X2,Fiducial Alignment Points,,,')
newPart.addTag('rawParts','FRAME1,FRAME-LETTER,FRAME-LETTER,CREATIVE_COMMONS,Schematic Frame,,,')
newPart.addTag('rawParts','JP1,,M02PTH,1X02,Header 2,,,')
newPart.addTag('rawParts','JP2,,M02PTH,1X02,Header 2,,,')
newPart.addTag('rawParts','JP3,,M04PTH,1X04,Header 4,,,')
newPart.addTag('rawParts','JP4,M100.1,M100.1,1X10,Header 10,,,')
newPart.addTag('rawParts','LED1,Red,LED1206,LED-1206,LEDs,,,')
newPart.addTag('rawParts','LOGO1,OSHW-LOGOS,OSHW-LOGOS,OSHW-LOGO-S,Open Source Hardware Logo This logo indicates the piece of hardware it is found on incorporates a OSHW license and/or adheres to the definition of open source hardware found here: http://freedomdefined.org/OSHW,,,')
newPart.addTag('rawParts','R1,330,330OHM1/10W1%(0603),0603-RES,RES-00818,RES-00818,330,')
newPart.addTag('rawParts','U$1,LOGO-SFENEW,LOGO-SFENEW,SFE-NEW-WEBLOGO,Spark Fun Electronics PCB Logo,,,')
newPart.addTag('rawParts','U$4,REVISION,REVISION,REVISION,,,,')
newPart.addTag('rawParts','U$6,STAND-OFF,STAND-OFF,STAND-OFF,Stand Off,,,')
newPart.addTag('rawParts','U$7,STAND-OFF,STAND-OFF,STAND-OFF,Stand Off,,,')
newPart.addTag('rawParts','U$8,STAND-OFF,STAND-OFF,STAND-OFF,Stand Off,,,')
newPart.addTag('rawParts','U$9,STAND-OFF,STAND-OFF,STAND-OFF,Stand Off,,,')
newPart.addTag('rawParts','U1,CP2102,CP210X_USB_UART,MLP28,Single-Chip USB to UART Bridge,,,')
newPart.addTag('rawParts','X1,USBPTH,USBPTH,USB-B-PTH,USB Connectors,,,')