import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-280-STAN-01")

newPart.addTag('rawParts','BATT_IN,,JST_2PIN,JSTPH2,JST 2-Pin Right-Angle Connector,,')
newPart.addTag('rawParts','BATT_OUT,,JST_2PIN,JSTPH2,JST 2-Pin Right-Angle Connector,,')
newPart.addTag('rawParts','C3,0.47uF,C-USC0805K,C0805K,CAPACITOR, American symbol,,')
newPart.addTag('rawParts','C4,10uF,CPOL-USA/3216-18R,A/3216-18R,POLARIZED CAPACITOR, American symbol,,')
newPart.addTag('rawParts','C5,10uF,CPOL-USA/3216-18R,A/3216-18R,POLARIZED CAPACITOR, American symbol,,')
newPart.addTag('rawParts','CHG,ORANGE,LEDCHIPLED_0805,CHIPLED_0805,LED,,')
newPart.addTag('rawParts','D1,B120,DIODESMA,SMADIODE,Diode,,')
newPart.addTag('rawParts','D2,B120,DIODESMA,SMADIODE,Diode,,')
newPart.addTag('rawParts','ERR,RED,LEDCHIPLED_0805,CHIPLED_0805,LED,,')
newPart.addTag('rawParts','IC1,,MCP7386XS,SO16,MCP7386x,,')
newPart.addTag('rawParts','IN,1X2-3.5MM,1X2-3.5MM,3.5MMTERM,3.5mm Terminal block,,')
newPart.addTag('rawParts','OUT,1X2-3.5MM,1X2-3.5MM,3.5MMTERM,3.5mm Terminal block,,')
newPart.addTag('rawParts','PG,GREEN,LEDCHIPLED_0805,CHIPLED_0805,LED,,')
newPart.addTag('rawParts','R1,adj,R-US_FLIPFLOP,0805-THM,RESISTOR, American symbol,,')
newPart.addTag('rawParts','R6,6.19K,R-US_R0805,R0805,RESISTOR, American symbol,,')
newPart.addTag('rawParts','R7,7.3k,R-US_R0805,R0805,RESISTOR, American symbol,,')
newPart.addTag('rawParts','R11,470,R-US_R0805,R0805,RESISTOR, American symbol,,')
newPart.addTag('rawParts','RTH,10K @ 25degC,R-US_FLIPFLOP,0805-THM,RESISTOR, American symbol,,')
newPart.addTag('rawParts','STAT3,,PINHD-1X1,1X01,Pin header 1x1 for 0.1 spacing,,')
newPart.addTag('rawParts','STAT4,,PINHD-1X1,1X01,Pin header 1x1 for 0.1 spacing,,')
newPart.addTag('rawParts','U$1,2.1MMJACKSMT,2.1MMJACKSMT,DCJACK_2MM_SMT,2.1mm x 5.5mm THM DC jack with internal switch. Digikey part #PJ-102A, 4UCON part #05537,,')
newPart.addTag('rawParts','U$3,FIDUCIAL,FIDUCIAL,FIDUCIAL_1MM,For use by pick and place machines to calibrate the vision/machine, 1mm,,')
newPart.addTag('rawParts','U$4,FIDUCIAL,FIDUCIAL,FIDUCIAL_1MM,For use by pick and place machines to calibrate the vision/machine, 1mm,,')
newPart.addTag('rawParts','USB,MINI-USB,USBMINIB,USB-MINIB,USB Connectors,,')
newPart.addTag('rawParts','VIN,1X2-3.5MM,1X2-3.5MM,3.5MMTERM,3.5mm Terminal block,,')