import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-10967-STAN-01")

newPart.addTag('rawParts','"C1","10uF","CAP_POL1206","EIA3216","Capacitor Polarized","",')
newPart.addTag('rawParts','"C2","68uF","CAP_POL3528","EIA3528","Capacitor Polarized","",')
newPart.addTag('rawParts','"D1","MBRA140","DIODESMA","SMA-DIODE","Diode","",')
newPart.addTag('rawParts','"FID1","FIDUCIAL1X2","FIDUCIAL1X2","FIDUCIAL-1X2","Fiducial Alignment Points","",')
newPart.addTag('rawParts','"FID2","FIDUCIAL1X2","FIDUCIAL1X2","FIDUCIAL-1X2","Fiducial Alignment Points","",')
newPart.addTag('rawParts','"FRAME1","FRAME-LETTER","FRAME-LETTER","CREATIVE_COMMONS","Schematic Frame","",')
newPart.addTag('rawParts','"JP1","","M03PTH","1X03","Header 3","",')
newPart.addTag('rawParts','"JP2","LOGO-SFESK","LOGO-SFESK","SFE-LOGO-FLAME","Spark Fun Electronics PCB Logo","",')
newPart.addTag('rawParts','"L1","47uH","INDUCTORCR54","CR54","Inductors","",')
newPart.addTag('rawParts','"U$1","OSHW-LOGOS","OSHW-LOGOS","OSHW-LOGO-S","Open Source Hardware Logo This logo indicates the piece of hardware it is found on incorporates a OSHW license and/or adheres to the definition of open source hardware found here: http://freedomdefined.org/OSHW","",')
newPart.addTag('rawParts','"U$2","CREATIVE_COMMONS","CREATIVE_COMMONS","CREATIVE_COMMONS","","",')
newPart.addTag('rawParts','"U1","NCP1402","V_REG_NCP1400SOT23-5","SOT23-5","Switching step-up voltage regulator","",')