import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-11801-STAN-01")

newPart.addTag('rawParts','C1,0.1uF,CAP0402-CAP,0402-CAP,Capacitor,,')
newPart.addTag('rawParts','C2,18pF,CAP0402-CAP,0402-CAP,Capacitor,,')
newPart.addTag('rawParts','C3,10uF,CAP0402-CAP,0402-CAP,Capacitor,,')
newPart.addTag('rawParts','C4,18pF,CAP0402-CAP,0402-CAP,Capacitor,,')
newPart.addTag('rawParts','D1,3.3V,DIODE-ZENER-BZT52,SOD-323,Zener Diode,,')
newPart.addTag('rawParts','D2,3.3V,DIODE-ZENER-BZT52,SOD-323,Zener Diode,,')
newPart.addTag('rawParts','FRAME1,FRAME-LETTER,FRAME-LETTER,CREATIVE_COMMONS,Schematic Frame,,')
newPart.addTag('rawParts','JP1,,M04PTH,1X04,Header 4,,')
newPart.addTag('rawParts','JP2,,M04PTH,1X04,Header 4,,')
newPart.addTag('rawParts','JP3,,M04SMD_STRAIGHT_COMBO,1X04_SMD_STRAIGHT_COMBO,Header 4,,')
newPart.addTag('rawParts','JP4,,M04SMD_STRAIGHT_COMBO,1X04_SMD_STRAIGHT_COMBO,Header 4,,')
newPart.addTag('rawParts','JP5,LOGO-SFENW2,LOGO-SFENW2,SFE-NEW-WEB,Spark Fun Electronics PCB Logo,,')
newPart.addTag('rawParts','JP6,LOGO-SFESK,LOGO-SFESK,SFE-LOGO-FLAME,Spark Fun Electronics PCB Logo,,')
newPart.addTag('rawParts','JP7,FIDUCIALUFIDUCIAL,FIDUCIALUFIDUCIAL,MICRO-FIDUCIAL,Fiducial Alignment Points,,')
newPart.addTag('rawParts','JP8,FIDUCIALUFIDUCIAL,FIDUCIALUFIDUCIAL,MICRO-FIDUCIAL,Fiducial Alignment Points,,')
newPart.addTag('rawParts','JP9,,AVR_SPI_PRG_6PTH,2X3,AVR ISP 6 Pin,,')
newPart.addTag('rawParts','JP11,LOGO-SFESK,LOGO-SFESK,SFE-LOGO-FLAME,Spark Fun Electronics PCB Logo,,')
newPart.addTag('rawParts','JP12,,M06SIP,1X06,Header 6,,')
newPart.addTag('rawParts','LED1,Yellow,LED0603,LED-0603,LEDs,,')
newPart.addTag('rawParts','Q1,16MHz,CRYSTAL5X3,CRYSTAL-SMD-5X3,Various standard crystals. Proven footprints. Spark Fun Electronics SKU : COM-00534,,')
newPart.addTag('rawParts','R1,68,RESISTOR0402-RES,0402-RES,Resistor,,')
newPart.addTag('rawParts','R2,68,RESISTOR0402-RES,0402-RES,Resistor,,')
newPart.addTag('rawParts','R3,1.5K,RESISTOR0402-RES,0402-RES,Resistor,,')
newPart.addTag('rawParts','R4,10k,RESISTOR0402-RES,0402-RES,Resistor,,')
newPart.addTag('rawParts','R5,330,RESISTOR0402-RES,0402-RES,Resistor,,')
newPart.addTag('rawParts','SJ1,SOLDERJUMPERNO,SOLDERJUMPERNO,SJ_2S-NO,Solder Jumper,,')
newPart.addTag('rawParts','SJ2,NC,SOLDERJUMPERNC,SJ_2S,Solder Jumper,,')
newPart.addTag('rawParts','TP1,TEST-POINT3,TEST-POINT3,PAD.03X.03,Bare copper test points for troubleshooting or ICT,,')
newPart.addTag('rawParts','U$1,OSHW-LOGOS,OSHW-LOGOS,OSHW-LOGO-S,Open Source Hardware Logo This logo indicates the piece of hardware it is found on incorporates a OSHW license and/or adheres to the definition of open source hardware found here: http://freedomdefined.org/OSHW,,')
newPart.addTag('rawParts','U1,ATTINY84,ATTINY84,SO14,Atmel 14-pin 2/4/8kB flash uC,,')
newPart.addTag('rawParts','X1,USB-A-H,USB-A-H,USB-A-H,USB Connectors,,')