import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-17156-STAN-01")

newPart.addTag('oompParts','3V3_ISO,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','D1,DIOD-S323-X-UNMATCHED-01')
newPart.addTag('oompParts','D1_BP,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','J1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','J2,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','J3,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','J4,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','J5,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','J6,HEAD-I01-X-PI02-01')
newPart.addTag('oompParts','R3,RESE-0603-X-O472-01')
newPart.addTag('oompParts','R4,RESE-0603-X-O472-01')
newPart.addTag('oompParts','S1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')