import OOMP
newPart = OOMP.getPartByID("PROJ-SPAR-14607-STAN-01")

newPart.addTag('oompParts','C1,CAPC-0603-X-UNMATCHED-01')
newPart.addTag('oompParts','C2,CAPC-0603-X-UNMATCHED-01')
newPart.addTag('oompParts','C3,CAPC-0603-X-UF10-01')
newPart.addTag('oompParts','C4,CAPC-0603-X-NF100-V50')
newPart.addTag('oompParts','J1,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','J2,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','J3,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','J4,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','JP7,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','LOGO2,UNMATCHED-UNMATCHED-X-UNMATCHED-01')
newPart.addTag('oompParts','R1,RESE-0603-X-O21-01')
newPart.addTag('oompParts','R2,RESE-0603-X-O103-01')
newPart.addTag('oompParts','R4,RESE-0603-X-UNMATCHED-01')
newPart.addTag('oompParts','R5,RESE-0603-X-UNMATCHED-01')
newPart.addTag('oompParts','U2,UNMATCHED-UNMATCHED-X-UNMATCHED-01')