import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-512-STAN-01")

newPart.addTag('rawParts','"C1","10nF","CAP_CERAMIC_0805MP","_0805MP","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C2","470nF","CAP_CERAMIC_0805MP","_0805MP","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C3","0.1uF","CAP_CERAMIC_0805MP","_0805MP","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C5","10uF","CAP_CERAMIC_0805MP","_0805MP","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C6","4.7uF","CAP_CERAMIC_0805MP","_0805MP","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C7","0.22\xc3\x82\xc2\xb5F","CAP_CERAMIC_0805MP","_0805MP","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C8","10uF","CAP_CERAMIC_0805MP","_0805MP","Ceramic Capacitors","",')
newPart.addTag('rawParts','"C9","10uF","CAP_CERAMIC_0805MP","_0805MP","Ceramic Capacitors","",')
newPart.addTag('rawParts','"FID1","FIDUCIAL""","FIDUCIAL""","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"FID2","FIDUCIAL""","FIDUCIAL""","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"FID3","FIDUCIAL""","FIDUCIAL""","FIDUCIAL_1MM","Fiducial Alignment Points","EXCLUDE",')
newPart.addTag('rawParts','"JP1","","HEADER-1X10ROUND","1X10_ROUND","PIN HEADER","",')
newPart.addTag('rawParts','"Q1","BSS138","MOSFET-NWIDE","SOT23-WIDE","N-Channel Mosfet","",')
newPart.addTag('rawParts','"Q2","BSS138","MOSFET-NWIDE","SOT23-WIDE","N-Channel Mosfet","",')
newPart.addTag('rawParts','"R1","10K","RESISTOR_0805MP","_0805MP","Resistors","",')
newPart.addTag('rawParts','"R2","10K","RESISTOR_0805MP","_0805MP","Resistors","",')
newPart.addTag('rawParts','"R3","10K","RESISTOR_0805MP","_0805MP","Resistors","",')
newPart.addTag('rawParts','"R4","10K","RESISTOR_0805MP","_0805MP","Resistors","",')
newPart.addTag('rawParts','"R5","10K","RESISTOR_0805MP","_0805MP","Resistors","",')
newPart.addTag('rawParts','"R6","10K","RESISTOR_0805MP","_0805MP","Resistors","",')
newPart.addTag('rawParts','"R7","10K","RESISTOR_0805MP","_0805MP","Resistors","",')
newPart.addTag('rawParts','"U$28","MOUNTINGHOLE2.5_THICK","MOUNTINGHOLE2.5_THICK","MOUNTINGHOLE_2.5_PLATED_THICK","Mounting Hole","EXCLUDE",')
newPart.addTag('rawParts','"U$29","MOUNTINGHOLE2.5_THICK","MOUNTINGHOLE2.5_THICK","MOUNTINGHOLE_2.5_PLATED_THICK","Mounting Hole","EXCLUDE",')
newPart.addTag('rawParts','"U$30","MOUNTINGHOLE2.5_THICK","MOUNTINGHOLE2.5_THICK","MOUNTINGHOLE_2.5_PLATED_THICK","Mounting Hole","EXCLUDE",')
newPart.addTag('rawParts','"U$31","MOUNTINGHOLE2.5_THICK","MOUNTINGHOLE2.5_THICK","MOUNTINGHOLE_2.5_PLATED_THICK","Mounting Hole","EXCLUDE",')
newPart.addTag('rawParts','"U1","L3GD20","GYRO_L3G2400D","L3G4200D_LGA16L","L3G4200D - 3-Axis MEMS gyroscope/motion sensor","",')
newPart.addTag('rawParts','"U2","LSM303DLHC","LSM303DLHC","LGA14","LSM303DLHC 3-Axis I2C Accelerometer and 3-Axis Magnetometer","",')
newPart.addTag('rawParts','"U4","MIC5225-3.3","VREG_SOT23-5","SOT23-5","SOT23-5 Fixed Voltage Regulators","",')