import OOMP
newPart = OOMP.getPartByID("PROJ-ADAF-4985-STAN-01")

newPart.addTag('rawParts','"C1","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C2","0.1uF","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C3","10\xc3\x82\xc2\xb5F","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C4","10\xc3\x82\xc2\xb5F","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C5","0.1uF","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C6","1uF","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C7","10\xc3\x82\xc2\xb5F","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C9","10uF/10V+","CAP_CERAMIC0805_10MGAP","0805_10MGAP","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C10","10\xc3\x82\xc2\xb5F","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C11","10\xc3\x82\xc2\xb5F","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C12","1uF","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C13","10\xc3\x82\xc2\xb5F","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C14","1uF","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C15","0.1uF","CAP_CERAMIC0603_NO","0603-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C17","10\xc3\x82\xc2\xb5F","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"C20","10uF","CAP_CERAMIC0805-NOOUTLINE","0805-NO","Ceramic Capacitors","","","","","","","","",')
newPart.addTag('rawParts','"CONN1","STEMMA_I2C_QT","STEMMA_I2C_QT","JST_SH4","","","","","","","","","",')
newPart.addTag('rawParts','"D1","3.6V","DIODE-ZENERSOD323","SOD-323","Zener Diode","","","","","","","","",')
newPart.addTag('rawParts','"D2","3.6V","DIODE-ZENERSOD323","SOD-323","Zener Diode","","","","","","","","",')
newPart.addTag('rawParts','"D3","1N4148","DIODESOD-323F","SOD-323F","Diode","","","","","","","","",')
newPart.addTag('rawParts','"D6","3.6V","DIODE-ZENERSOD323","SOD-323","Zener Diode","","","","","","","","",')
newPart.addTag('rawParts','"DS0","APA102-2020","APA1022020","APA102_2020","APA102/DotStar Pixels","","","","","","","","",')
newPart.addTag('rawParts','"DS1","APA102-2020","APA1022020","APA102_2020","APA102/DotStar Pixels","","","","","","","","",')
newPart.addTag('rawParts','"DS2","APA102-2020","APA1022020","APA102_2020","APA102/DotStar Pixels","","","","","","","","",')
newPart.addTag('rawParts','"DS3","APA102-2020","APA1022020","APA102_2020","APA102/DotStar Pixels","","","","","","","","",')
newPart.addTag('rawParts','"DS4","APA102-2020","APA1022020","APA102_2020","APA102/DotStar Pixels","","","","","","","","",')
newPart.addTag('rawParts','"FID1","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","","EXCLUDE","","","","","","",')
newPart.addTag('rawParts','"FID2","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","","EXCLUDE","","","","","","",')
newPart.addTag('rawParts','"FID3","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","","EXCLUDE","","","","","","",')
newPart.addTag('rawParts','"FID4","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","","EXCLUDE","","","","","","",')
newPart.addTag('rawParts','"FID5","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","","EXCLUDE","","","","","","",')
newPart.addTag('rawParts','"FID6","FIDUCIAL_1MM","FIDUCIAL_1MM","FIDUCIAL_1MM","Fiducial Alignment Points","","EXCLUDE","","","","","","",')
newPart.addTag('rawParts','"JP1","2x3 SMT","HEADER-2X314113","2X03_SMT_4UCON_14113","PIN HEADER","","","","","","","","",')
newPart.addTag('rawParts','"JP2","","HEADER-2X3_SMTTHM","2X03_SMTTHM","PIN HEADER","","","","","","","","",')
newPart.addTag('rawParts','"L","RED","LED0603_NOOUTLINE","CHIPLED_0603_NOOUTLINE","LED","","","","","","","","",')
newPart.addTag('rawParts','"ON","GREEN","LED0603_NOOUTLINE","CHIPLED_0603_NOOUTLINE","LED","","","","","","","","",')
newPart.addTag('rawParts','"Q1","BSS138","MOSFET-NWIDE","SOT23-WIDE","N-Channel Mosfet","","","","","","","","",')
newPart.addTag('rawParts','"Q3","DMG3415U-7","MOSFET-P","SOT23-R","P-Channel Mosfet","","","","","","","","",')
newPart.addTag('rawParts','"Q4","BSS138","MOSFET-NREFLOW","SOT23-R","N-Channel Mosfet","","","","","","","","",')
newPart.addTag('rawParts','"R1","10K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R2","1K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R3","5.1K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R4","10K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R5","10K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R6","47K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R7","10K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R8","5.1K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R9","10K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R10","10K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R11","100","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R12","10K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R13","10K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R14","1Meg","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R16","1K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R17","1Meg","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R18","1K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"R20","10K","RESISTOR_0603_NOOUT","0603-NO","Resistors","","","","","","","","",')
newPart.addTag('rawParts','"SENSE","JST PH 3","CON_JST_PH_3PIN","JSTPH3","","","","","","","","","",')
newPart.addTag('rawParts','"SENSE1","JST PH 3","CON_JST_PH_3PIN","JSTPH3","","","","","","","","","",')
newPart.addTag('rawParts','"SENSE3","JST PH 3","CON_JST_PH_3PIN","JSTPH3","","","","","","","","","",')
newPart.addTag('rawParts','"SJ1","","SOLDERJUMPERCLOSED","SOLDERJUMPER_CLOSEDWIRE","SMD Solder JUMPER","","","","","","","","",')
newPart.addTag('rawParts','"SJ2","","SOLDERJUMPER_2WAY","SOLDERJUMPER_2WAY_OPEN_NOPASTE","2-Way Solder Jumper","","","","","","","","",')
newPart.addTag('rawParts','"SP1","7.5mm SPK","SPEAKER_7.5MM","BUZZER_SMT_7.5MM","SPEAKER Source: BuerklinAdded PS12 (for part # PS1240 piezo) http://www.ladyada.net/library/pcb/eaglelibrary.html","","","","","","","","",')
newPart.addTag('rawParts','"SW2","FSM2JMTR","SWITCH_PUSHBUTTON_3.5X6MM","TACTILE_3X6MM","Buttons","","","","","","","","",')
newPart.addTag('rawParts','"SW3","EG1390","SWITCH_DPDTEG1390","EG1390","Switch - DPDT","","","","","","","","",')
newPart.addTag('rawParts','"SW4","SPST_TACT-KMR2","SPST_TACT-KMR2","KMR2","SMT 6mm switch, EVQQ2 series","","","","","","","","",')
newPart.addTag('rawParts','"SW5","FSM2JMTR","SWITCH_PUSHBUTTON_3.5X6MM","TACTILE_3X6MM","Buttons","","","","","","","","",')
newPart.addTag('rawParts','"SW6","FSM2JMTR","SWITCH_PUSHBUTTON_3.5X6MM","TACTILE_3X6MM","Buttons","","","","","","","","",')
newPart.addTag('rawParts','"SW7","FSM2JMTR","SWITCH_PUSHBUTTON_3.5X6MM","TACTILE_3X6MM","Buttons","","","","","","","","",')
newPart.addTag('rawParts','"TFT1","DISP_TFT_1.54IN_240X240_22P","DISP_TFT_1.54IN_240X240_22P","TFT_1.54IN_240X240_22PIN","","","","","","","","","",')
newPart.addTag('rawParts','"TP1","","TESTPOINTROUND1.5MMNO","TESTPOINT_ROUND_1.5MM_NO","Test Point","","","","","","","","",')
newPart.addTag('rawParts','"TP2","","TESTPOINTROUND1.5MMNO","TESTPOINT_ROUND_1.5MM_NO","Test Point","","","","","","","","",')
newPart.addTag('rawParts','"TP3","","TESTPOINTROUND1.5MMNO","TESTPOINT_ROUND_1.5MM_NO","Test Point","","","","","","","","",')
newPart.addTag('rawParts','"TP4","SEWTAP_SMTNUTM3","SEWTAP_SMTNUTM3","SMT_NUT_3MM","","","","","","","","","",')
newPart.addTag('rawParts','"TP5","SEWTAP_SMTNUTM3","SEWTAP_SMTNUTM3","SMT_NUT_3MM","","","","","","","","","",')
newPart.addTag('rawParts','"TP6","","TESTPOINTROUND1.5MMNO","TESTPOINT_ROUND_1.5MM_NO","Test Point","","","","","","","","",')
newPart.addTag('rawParts','"TP7","SEWTAP_SMTNUTM3","SEWTAP_SMTNUTM3","SMT_NUT_3MM","","","","","","","","","",')
newPart.addTag('rawParts','"TP8","SEWTAP_SMTNUTM3","SEWTAP_SMTNUTM3","SMT_NUT_3MM","","","","","","","","","",')
newPart.addTag('rawParts','"U1","DPS3","BMP280_COMBO","BMX280_COMBO","BMP280 - Digital Pressure Sensor","","","","","","","","",')
newPart.addTag('rawParts','"U2","ALS-PT19","PHOTOTRANSISTOR_PT19-315C","ALS-PT19-315C","ALS-PT19-315C - Analog Light Sensor","","","","","","","","",')
newPart.addTag('rawParts','"U3","ESP32-S2-MODULE_WROVER","ESP32-S2-MODULE_WROVER","MODULE_ESP32-S2-WROVER","WiFi 802.11b/g/n Transceiver Module 2.4GHz Antenna Not Included Surface Mount Check prices","Warning",""," WiFi 802.11b/g/n Transceiver Module 2.4GHz Antenna Not Included Surface Mount ","https://snapeda.com/shop?store=DigiKey&id=4614060","Espressif Systems","ESP32-S2-WROVER","VFQFN-56 Espressif Systems","None",')
newPart.addTag('rawParts','"U4","AP2112K-3.3","VREG_SOT23-5","SOT23-5","SOT23-5 Fixed Voltage Regulators","","","","","","","","",')
newPart.addTag('rawParts','"U5","AHT20","SENSOR-AHT20","SNR6-1.0-3X3X1MM","","","","","","","","","",')
newPart.addTag('rawParts','"X1","CAPTOUCH_10MM","CAPTOUCH_MONOPAD_6X9","CAPTOUCH_6X9MM","","","","","","","","","",')
newPart.addTag('rawParts','"X3","CAPTOUCH_10MM","CAPTOUCH_MONOPAD_7X9","CAPTOUCH_7X9MM","","","","","","","","","",')
newPart.addTag('rawParts','"X4","USB C","USB_C","USB_C_CUSB31-CFM2AX-01-X","USB Type-C USB 2.0 Connector","","","","","","","","",')
newPart.addTag('rawParts','"X5","CAPTOUCH_10MM","CAPTOUCH_MONOPAD_7X9","CAPTOUCH_7X9MM","","","","","","","","","",')
newPart.addTag('rawParts','"X6","CAPTOUCH_5SLIDER_10MM","CAPTOUCH_5SLIDER_10MM","CAPTOUCH_5SLIDER","","","","","","","","","",')